/* HeiBen — Rund ums Auto: Panne, Wartung, Kosten.
   Datenbasis für auto.html. Schema je Eintrag:
   {id,n,kat,typ:"panne"|"wartung"|"kosten",selbst(opt true = gut selbst machbar),
    kurz:`Ein-Satz-Kern`,lage:`Worum es geht`,schritte:[`3–6 Schritte`],
    fehler:`Häufiger Fehler`,werkstatt(opt):`Wann in die Werkstatt`,warn(opt):`Sicherheit`,tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten.
   Bewusst ohne markenspezifische Anleitungen; Bordbuch schlägt Faustregel. */

window.AU_KAT={panne:"Panne & Notfall",reifen:"Reifen & Räder",motor:"Motor & Flüssigkeiten",licht:"Licht, Elektrik & Warnleuchten",pflege:"Pflege & Innenraum",kosten:"Kosten & Kauf"};
window.AU_TYP={panne:"Panne",wartung:"Wartung",kosten:"Kosten & Entscheidung"};

window.AUTO=[
/* -- Panne & Notfall -- */
{id:"panne",n:"Liegengeblieben — die Absicherung",kat:"panne",typ:"panne",
 kurz:`Erst die Menschen sichern, dann das Auto — in genau dieser Reihenfolge.`,
 lage:`Ob Reifenplatzer oder Motor aus: Die ersten 60 Sekunden entscheiden über die Sicherheit. Die feste Reihenfolge schützt dich und den nachfolgenden Verkehr.`,
 schritte:[
  `Warnblinker sofort einschalten — schon beim Ausrollen.`,
  `Möglichst rechts ranfahren, auf der Autobahn auf den Standstreifen, Räder leicht nach rechts einschlagen.`,
  `Warnweste anziehen, BEVOR du aussteigst — und auf der Verkehrsseite besonders vorsichtig.`,
  `Alle Insassen hinter die Leitplanke bringen, nicht im Auto sitzen bleiben.`,
  `Warndreieck in ausreichendem Abstand aufstellen (innerorts ca. 50 m, Landstraße 100 m, Autobahn 150–200 m).`,
  `Erst dann Pannenhilfe rufen.`],
 fehler:`Im Auto auf dem Standstreifen sitzen bleiben oder ohne Warnweste aussteigen — die häufigste tödliche Fehlentscheidung bei Pannen.`,
 warn:`Auf der Autobahn NIE die Fahrbahn betreten. Warnweste gehört griffbereit ins Türfach, nicht in den Kofferraum.`,
 tipp:`Merksatz in fester Reihenfolge: Warnblinker – Weste – raus – hinter die Leitplanke – Dreieck – Hilfe. In dieser Ordnung, immer.`},
{id:"warndreieck",n:"Pannenset: Weste, Dreieck, Verbandkasten",kat:"panne",typ:"panne",
 kurz:`Drei Dinge sind Pflicht — und der Verbandkasten hat ein Ablaufdatum.`,
 lage:`Warnweste, Warndreieck und Verbandkasten sind in Deutschland vorgeschrieben. Fehlen sie oder ist der Verbandkasten abgelaufen, gibt es bei einer Kontrolle ein Verwarnungsgeld.`,
 schritte:[
  `Warnweste griffbereit im Innenraum (Türfach), nicht im Kofferraum — du brauchst sie VOR dem Aussteigen.`,
  `Warndreieck im Kofferraum an fester Stelle; jeder im Haushalt sollte wissen, wo es liegt.`,
  `Verbandkasten auf Verfallsdatum prüfen — der Inhalt läuft ab (meist nach einigen Jahren).`,
  `Sinnvolle Ergänzung: zweite Warnweste pro Sitzplatz, Taschenlampe, Starthilfekabel, Handyladekabel.`],
 fehler:`Nur eine Warnweste im Auto — bei Familienausflügen braucht jeder Aussteigende eine.`,
 tipp:`Beim Hausapotheken-TÜV (zweimal im Jahr) den Auto-Verbandkasten gleich mitprüfen — ein Termin, zwei erledigte Pflichten.`},
{id:"starthilfe",n:"Starthilfe geben & bekommen",kat:"panne",typ:"panne",selbst:true,
 kurz:`Rot an Plus, Schwarz an Masse — und die Reihenfolge ist alles.`,
 lage:`Eine leere Starterbatterie (Licht angelassen, Kälte, kurze Strecken) lässt sich mit einem Spenderfahrzeug oder Booster überbrücken. Die richtige Reihenfolge schützt die Elektronik.`,
 schritte:[
  `Beide Motoren aus. Rotes Kabel an PLUS der leeren, dann an PLUS der vollen Batterie.`,
  `Schwarzes Kabel an MINUS der vollen Batterie, das andere Ende an ein Metallteil (Masse) am Motorblock des Pannenautos — NICHT an den Minuspol der leeren Batterie.`,
  `Spenderauto starten, dann das Pannenauto starten lassen.`,
  `Beim Abklemmen exakt umgekehrte Reihenfolge; danach das gestartete Auto eine längere Strecke fahren.`],
 fehler:`Das schwarze Kabel an den Minuspol der leeren Batterie klemmen — hier kann sich Knallgas entzünden. Immer an Masse.`,
 werkstatt:`Ist die Batterie nach dem Aufladen schnell wieder leer oder älter als 5–6 Jahre, steht ein Wechsel an — bei modernen Autos oft mit Anlernen in der Werkstatt.`,
 warn:`Keine Funken in Batterienähe; keine beschädigten Kabel verwenden. Bei Rauch oder Zischen sofort abklemmen.`,
 tipp:`Ein Lithium-Booster (Powerbank fürs Auto) macht dich unabhängig vom zweiten Auto — er passt ins Handschuhfach.`},
{id:"reifenpanne",n:"Reifenpanne unterwegs",kat:"panne",typ:"panne",selbst:true,
 kurz:`Ersatzrad, Faltrad oder Pannenset — wissen, was der Kofferraum hergibt, BEVOR es knallt.`,
 lage:`Viele neue Autos haben kein Ersatzrad mehr, sondern ein Pannenset (Dichtmittel + Kompressor) oder Notlaufreifen. Der Wechsel selbst folgt immer demselben Muster.`,
 schritte:[
  `Sicher anhalten und absichern (siehe „Liegengeblieben“).`,
  `Radschrauben eine Vierteldrehung lösen, SOLANGE das Rad noch am Boden steht.`,
  `Wagenheber an der dafür vorgesehenen Aufnahme (Bordbuch!) ansetzen, Auto anheben.`,
  `Schrauben herausdrehen, Rad wechseln, Schrauben über Kreuz handfest anziehen.`,
  `Auto ablassen, Schrauben über Kreuz fest anziehen; mit Faltrad (Notrad) nur langsam und kurz fahren.`],
 fehler:`Die Radschrauben erst nach dem Anheben lösen wollen — dann dreht das Rad frei mit.`,
 werkstatt:`Nach jedem Pannenset-Einsatz und bei Notrad zeitnah in die Werkstatt; Notlaufreifen mit Reifenschaden ersetzen, nicht flicken.`,
 tipp:`Schau HEUTE in den Kofferraum: Ersatzrad, Faltrad oder Pannenset? Und liegt der Radschlüssel dabei? Das willst du nicht erst im Regen herausfinden.`},
{id:"unfall",n:"Nach einem Unfall: das Wichtigste",kat:"panne",typ:"panne",
 kurz:`Sichern, helfen, dokumentieren — und niemals ein Schuldanerkenntnis unterschreiben.`,
 lage:`Auch ein kleiner Blechschaden folgt festen Schritten. Ruhe und Reihenfolge verhindern Folgefehler — rechtlich wie finanziell.`,
 schritte:[
  `Unfallstelle absichern (Warnblinker, Weste, Dreieck), Verletzten helfen, bei Personenschaden 112.`,
  `Bei größerem Schaden, Streit oder Personenschaden: Polizei rufen.`,
  `Beweise sichern: Fotos von Fahrzeugen, Kennzeichen, Endstellung, Schäden, Umgebung.`,
  `Daten austauschen: Name, Anschrift, Kfz-Kennzeichen, Versicherung; den Europäischen Unfallbericht gemeinsam ausfüllen.`,
  `Schaden der eigenen Versicherung melden.`],
 fehler:`Ein Schuldanerkenntnis unterschreiben oder Bargeld annehmen/geben — beides kann teuer werden und ist rechtlich heikel.`,
 warn:`Unerlaubtes Entfernen vom Unfallort ist eine Straftat — auch beim „nur“ angefahrenen Parkauto: Warten und/oder Polizei informieren, ein Zettel allein reicht rechtlich nicht.`,
 tipp:`Der Europäische Unfallbericht (leer im Handschuhfach) führt euch am Unfallort durch alle wichtigen Angaben — ausdrucken und einlegen.`},

/* -- Reifen & Räder -- */
{id:"reifenwechsel",n:"Räder wechseln (Sommer/Winter)",kat:"reifen",typ:"wartung",selbst:true,
 kurz:`O bis O — von Ostern bis Oktober — und über Kreuz anziehen.`,
 lage:`Der saisonale Radwechsel ist eine der lohnendsten Selbermach-Arbeiten. Faustregel für die Zeit: „von O bis O“ (Ostern bis Oktober Sommerreifen).`,
 schritte:[
  `Auf festem, ebenem Untergrund; Handbremse an, Gang/P eingelegt.`,
  `Schrauben am stehenden Rad eine Vierteldrehung lösen, dann aufbocken.`,
  `Räder markieren (VL/VR/HL/HR), damit die Laufrichtung stimmt und du nächstes Mal rotieren kannst.`,
  `Neue Räder ansetzen, Schrauben über Kreuz handfest, dann ablassen und mit Drehmomentschlüssel festziehen (Wert im Bordbuch).`,
  `Reifendruck prüfen und nach etwa 50 km die Schrauben nachziehen.`],
 fehler:`Schrauben „nach Gefühl“ zu fest oder zu locker — beides ist gefährlich. Drehmomentschlüssel ist Pflicht.`,
 warn:`Nie unter ein nur vom Wagenheber gehaltenes Auto greifen — bei längeren Arbeiten Unterstellböcke verwenden.`,
 tipp:`Reifen einlagern mit dem Merksatz „Vorher fotografieren“: Ein Bild vom Reifendruck-Aufkleber in der Türsäule erspart später das Suchen.`},
{id:"reifendruck",n:"Reifendruck & Profil prüfen",kat:"reifen",typ:"wartung",selbst:true,
 kurz:`Zwei Minuten an der Tankstelle sparen Sprit, Reifen und im Ernstfall den Bremsweg.`,
 lage:`Falscher Luftdruck kostet Sprit, nutzt Reifen ungleich ab und verlängert den Bremsweg. Der richtige Wert steht in der Türsäule oder im Tankdeckel.`,
 schritte:[
  `Druck bei KALTEN Reifen prüfen (nicht nach langer Fahrt).`,
  `Sollwert aus Türsäule/Tankdeckel ablesen — bei voller Beladung den höheren Wert nehmen.`,
  `An der Tankstelle alle vier Reifen (und ggf. das Ersatzrad) füllen.`,
  `Profiltiefe prüfen: gesetzlich min. 1,6 mm, sinnvoll Sommer 3 mm, Winter 4 mm. Der 1-Euro-Trick: Verschwindet der Goldrand im Profil, ist genug da.`],
 fehler:`Nur nach Optik gehen — ein Reifen kann fast platt aussehen und noch Druck haben, oder umgekehrt. Immer messen.`,
 warn:`Zu wenig Druck kann bei hoher Geschwindigkeit zum Reifenplatzer führen. Vor jeder langen Urlaubsfahrt prüfen.`,
 tipp:`Der 1-Euro-Münz-Trick fürs Profil funktioniert überall und kostet nichts: Goldrand rein — verschwindet er, ist alles gut.`},
{id:"reifenalter",n:"Reifenalter & Wann ersetzen",kat:"reifen",typ:"kosten",
 kurz:`Auch mit viel Profil ist ein Reifen irgendwann zu alt — die DOT-Nummer verrät es.`,
 lage:`Gummi altert und wird hart und rissig, auch ohne gefahren zu werden. Das Herstellungsdatum steht als vierstellige DOT-Nummer auf der Flanke (z. B. „2223“ = 22. Woche 2023).`,
 schritte:[
  `DOT-Nummer an der Reifenflanke ablesen: die letzten vier Ziffern = Woche + Jahr.`,
  `Richtwert: nach etwa 6 Jahren kritisch prüfen, spätestens nach rund 8–10 Jahren ersetzen — unabhängig vom Profil.`,
  `Auf feine Risse in der Flanke und im Profilgrund achten (Sprödigkeit).`,
  `Beim Neukauf ebenfalls auf ein aktuelles DOT achten — „neu“ heißt nicht „frisch produziert“.`],
 fehler:`Nur aufs Profil schauen — ein 12 Jahre alter Reifen mit viel Profil ist trotzdem gefährlich.`,
 tipp:`Beim Reifenkauf ruhig nach dem DOT fragen — seriöse Händler verkaufen keine Reifen, die schon Jahre im Lager lagen.`},

/* -- Motor & Flüssigkeiten -- */
{id:"oelstand",n:"Ölstand prüfen & nachfüllen",kat:"motor",typ:"wartung",selbst:true,
 kurz:`Der wichtigste Zwei-Minuten-Check — zu wenig Öl killt den Motor.`,
 lage:`Zu niedriger Ölstand ist einer der teuersten vermeidbaren Motorschäden. Der Peilstab (oder die digitale Anzeige) verrät den Stand in zwei Minuten.`,
 schritte:[
  `Motor warm, dann aus; Auto eben abstellen und 1–2 Minuten warten.`,
  `Peilstab herausziehen, abwischen, ganz hineinstecken, erneut ziehen und ablesen — der Stand muss zwischen MIN und MAX liegen.`,
  `Zu niedrig: die richtige Ölsorte (Bordbuch!) in kleinen Mengen nachfüllen und erneut messen — lieber zu wenig als zu viel.`,
  `Bei digitaler Anzeige die Menüführung im Bordcomputer nutzen.`],
 fehler:`Falsche Ölsorte nachfüllen oder überfüllen — beides schadet. Immer die Spezifikation aus dem Bordbuch verwenden.`,
 werkstatt:`Ständiger Ölverlust, blauer Rauch oder die rote Öldruck-Lampe (Ölkännchen) sind Alarm: sofort anhalten, Motor aus, Werkstatt.`,
 warn:`Die ROTE Öllampe bedeutet Öldruck-Notfall — sofort sicher anhalten. Die gelbe ist ein Hinweis, kein Sofort-Stopp, aber zeitnah prüfen.`,
 tipp:`Vor jeder langen Fahrt und einmal im Monat: Öl, Kühlwasser, Scheibenwasser, Reifen — der Vier-Punkte-Blick unter fünf Minuten.`},
{id:"kuehlwasser",n:"Kühlwasser prüfen",kat:"motor",typ:"wartung",selbst:true,
 kurz:`Zwischen MIN und MAX — und den heißen Deckel niemals öffnen.`,
 lage:`Das Kühlmittel schützt vor Überhitzung und Frost. Der Stand im Ausgleichsbehälter sollte zwischen den Markierungen liegen; das Frostschutz-Mischungsverhältnis ist im Winter wichtig.`,
 schritte:[
  `NUR bei kaltem Motor: Stand im durchsichtigen Ausgleichsbehälter zwischen MIN und MAX prüfen.`,
  `Zu niedrig: passendes Kühlmittel (richtige Farbe/Spezifikation, mit Frostschutz) nachfüllen.`,
  `Nie reines Wasser dauerhaft einfüllen — es fehlt Frost- und Korrosionsschutz.`,
  `Bei häufigem Nachfüllen die Ursache (Undichtigkeit) suchen lassen.`],
 fehler:`Den Kühlerdeckel bei heißem Motor öffnen — kochendes Kühlmittel spritzt heraus. Schwere Verbrühungsgefahr.`,
 werkstatt:`Steigt die Temperaturanzeige in den roten Bereich: Heizung voll aufdrehen (entlastet den Motor), bei nächster Gelegenheit anhalten, Motor aus, Werkstatt. Weißer Rauch heißt oft Zylinderkopfdichtung.`,
 warn:`Kühlerdeckel bei heißem Motor = akute Verbrühungsgefahr. Immer erst abkühlen lassen.`,
 tipp:`Steigt die Temperatur beim Stehen im Stau: Heizung voll auf — sie zieht Wärme aus dem Motor und ist der beste Nothelfer.`},
{id:"scheibenwasser",n:"Scheibenwaschwasser & Wischer",kat:"motor",typ:"wartung",selbst:true,
 kurz:`Freie Sicht ist Sicherheit — und im Winter entscheidet der Frostschutz.`,
 lage:`Leeres Wischwasser oder schmierende Wischer sind ein unterschätztes Sicherheitsrisiko. Beides ist in Minuten selbst erledigt.`,
 schritte:[
  `Wasserbehälter (Symbol: Fontäne) auffüllen; im Winter Konzentrat mit Frostschutz, nicht nur Wasser (friert und sprengt die Pumpe).`,
  `Sommer: Reiniger gegen Insekten zugeben.`,
  `Wischerblätter prüfen: schmieren oder rattern sie, tauschen — das geht meist werkzeuglos per Clip.`,
  `Wischergummis mit einem feuchten Tuch abwischen; im Winter Wischer nicht angefroren am Glas einschalten.`],
 fehler:`Im Winter nur Wasser einfüllen — es gefriert, die Düsen und die Pumpe können Schaden nehmen.`,
 tipp:`Neue Wischer im Herbst sind das günstigste Sicherheits-Upgrade des Jahres — Streulicht und Schlieren bei Dunkelheit verschwinden sofort.`},
{id:"bremsen",n:"Bremsen: Warnzeichen erkennen",kat:"motor",typ:"wartung",
 kurz:`Bremsen sind nichts zum Selbermachen — aber die Warnzeichen muss jeder kennen.`,
 lage:`An der Bremse hört das Heimwerken auf: Sie ist sicherheitskritisch und gehört in die Werkstatt. Deine Aufgabe ist, die Warnzeichen früh zu erkennen.`,
 schritte:[
  `Auf Geräusche achten: Quietschen kann der Verschleiß-Warnhinweis sein, Schleifen/Metallschleifen ist ein Alarmsignal.`,
  `Auf Gefühl achten: weiches oder „durchsackendes“ Pedal, längerer Bremsweg, Ziehen zur Seite, Vibrieren beim Bremsen.`,
  `Auf Anzeigen achten: Bremsbelag-Warnleuchte oder Bremsflüssigkeits-Warnung ernst nehmen.`,
  `Bei jedem dieser Zeichen zeitnah in die Werkstatt.`],
 fehler:`Quietschen und Schleifen „wegfahren“ wollen — verschlissene Beläge zerstören die teuren Bremsscheiben.`,
 werkstatt:`Jedes anhaltende Bremsgeräusch, verändertes Pedalgefühl oder eine Bremswarnleuchte gehören sofort geprüft — hier wird nicht abgewartet.`,
 warn:`Sackt das Bremspedal durch oder leuchtet die Bremswarnung rot: Geschwindigkeit runter, Motorbremse und Handbremse dosiert nutzen, umgehend anhalten.`,
 tipp:`Bremsen und Sicherheit kennen keine Sparfüchse: Die Werkstatt ist hier immer günstiger als das Krankenhaus.`},

/* -- Licht, Elektrik & Warnleuchten -- */
{id:"warnleuchten",n:"Warnleuchten verstehen",kat:"licht",typ:"panne",
 kurz:`Die Ampel-Logik: Rot heißt anhalten, Gelb heißt zeitnah prüfen.`,
 lage:`Kontrollleuchten folgen einer Ampel-Logik. Wer sie kennt, unterscheidet den Notfall vom Hinweis — und den teuren Folgeschaden vom harmlosen Hinweis.`,
 schritte:[
  `ROT = sofort reagieren: anhalten, Motor prüfen/aus. Klassiker: Öldruck (Kännchen), Motortemperatur, Batterie/Ladung, Bremse.`,
  `GELB/ORANGE = zeitnah prüfen, Weiterfahrt meist möglich: Motorkontrollleuchte, Reifendruck, ABS, Glühwendel (Diesel).`,
  `Blinkt die Motorkontrollleuchte (statt Dauerlicht): Leistung reduzieren und zügig in die Werkstatt — mögliche Verbrennungsaussetzer.`,
  `Im Zweifel im Bordbuch nachschlagen — jedes Symbol ist dort erklärt.`],
 fehler:`Eine rote Leuchte „später“ prüfen wollen — bei Öldruck oder Temperatur können Minuten über einen Motorschaden entscheiden.`,
 werkstatt:`Jede rote Leuchte und jede blinkende Motorkontrollleuchte bedeuten: nicht weiterfahren bzw. sofort in die Werkstatt.`,
 tipp:`Fotografiere die leuchtende Anzeige — in der Werkstatt ist die Leuchte oft aus, und das Bild spart die Rätselei.`},
{id:"gluehbirne",n:"Defekte Lampe wechseln",kat:"licht",typ:"wartung",selbst:true,
 kurz:`Eine kaputte Leuchte ist ein Bußgeld auf Rädern — und oft in Minuten getauscht.`,
 lage:`Ein ausgefallenes Abblend-, Brems- oder Blinklicht ist ein Sicherheitsmangel und wird bei Kontrollen beanstandet. Bei vielen Autos ist der Wechsel einfach — bei modernen mit LED oder engem Motorraum aber Werkstattsache.`,
 schritte:[
  `Regelmäßig kontrollieren: Licht einschalten und rundherum prüfen (oder vor einer Schaufensterscheibe).`,
  `Ersatzlampe im richtigen Typ besorgen (Bordbuch/Aufdruck auf der alten Lampe).`,
  `Glaskolben neuer Halogenlampen nicht mit bloßen Fingern anfassen (Fett verkürzt die Lebensdauer) — Tuch benutzen.`,
  `Nach dem Wechsel Funktion prüfen.`],
 fehler:`Den Glaskolben mit bloßen Fingern anfassen — die Lampe brennt dann früh durch. Tuch oder Handschuh verwenden.`,
 werkstatt:`Bei fest verbauten LED-Einheiten, Xenon (Hochspannung!) oder wenn der Zugang das halbe Auto zerlegen würde: Werkstatt.`,
 tipp:`Ein günstiges Ersatzlampen-Set im Handschuhfach spart im Ausland teure Werkstattpreise und mancherorts ein Bußgeld.`},
{id:"autobatterie",n:"Autobatterie: Lebensdauer & Pflege",kat:"licht",typ:"kosten",
 kurz:`Kurzstrecke und Kälte sind die Batterie-Killer — Vorbeugen ist billiger als Liegenbleiben.`,
 lage:`Eine Starterbatterie hält meist 4–6 Jahre. Viele Kurzstrecken laden sie nie voll, Kälte setzt ihr zu — Ausfälle häufen sich im ersten Frost.`,
 schritte:[
  `Vorbeugen: gelegentlich längere Strecken fahren; vor dem Abstellen große Verbraucher (Sitzheizung, Gebläse) ausschalten.`,
  `Zeichen für Schwäche: Anlasser dreht müde, Licht flackert beim Starten, Start-Stopp arbeitet nicht mehr.`,
  `Kontakte sauber und fest halten; bei Standzeiten ein Erhaltungsladegerät nutzen.`,
  `Ersatz nach etwa 5 Jahren einplanen — lieber im Herbst als beim ersten Frost.`],
 fehler:`Warten, bis sie ganz leer ist — moderne Autos „vergessen“ dann teils Einstellungen, und der Wechsel wird umständlicher.`,
 werkstatt:`Bei modernen Fahrzeugen muss die neue Batterie oft angelernt (codiert) werden — hier lohnt die Werkstatt trotz höherer Kosten.`,
 tipp:`Wer viel Kurzstrecke fährt, gönnt der Batterie einmal im Monat eine längere Fahrt — oder lädt sie über Nacht mit einem Erhaltungsgerät.`},

/* -- Pflege & Innenraum -- */
{id:"waschen",n:"Auto richtig waschen",kat:"pflege",typ:"wartung",selbst:true,
 kurz:`Salz runter, Lack schonen — und nur dort waschen, wo es erlaubt ist.`,
 lage:`Regelmäßiges Waschen schützt den Lack, besonders im Winter vor Streusalz. Wichtig: Auf privatem Grund und an der Straße ist die Autowäsche aus Umweltgründen meist verboten — nur Waschanlage oder ausgewiesene Waschplätze.`,
 schritte:[
  `Waschanlage oder SB-Waschbox nutzen (Umweltauflagen); im Winter regelmäßig, um Salz zu entfernen.`,
  `Vorwäsche/Insektenentferner einwirken lassen, damit der Schmutz nicht kratzt.`,
  `Nach der Wäsche Türfalze und Gummidichtungen bei Frost pflegen (Silikon-/Pflegestift), damit nichts festfriert.`,
  `Unterboden im Winter gelegentlich mitwaschen (Salz).`],
 fehler:`Das Auto in der Einfahrt mit dem Gartenschlauch waschen — vielerorts verboten und mit Bußgeld belegt, weil Öl und Schmutz ins Grundwasser gelangen.`,
 tipp:`Türgummis vor dem Winter mit einem Pflegestift einreiben — dann friert die Tür bei Frost nicht fest und reißt nicht ein.`},
{id:"scheibenfrei",n:"Scheiben im Winter freimachen",kat:"pflege",typ:"panne",selbst:true,
 kurz:`Freie Sicht ist Pflicht — das „Guckloch“ kostet Bußgeld und ist gefährlich.`,
 lage:`Vereiste oder beschlagene Scheiben sind im Winter Alltag. Nur komplett freie Scheiben sind erlaubt; ein freigekratztes Guckloch ist ein Bußgeld und lebensgefährlich.`,
 schritte:[
  `Alle Scheiben, Spiegel und die Beleuchtung vollständig freikratzen/enteisen — auch das Dach abfegen (herabfallendes Eis gefährdet andere).`,
  `Enteiser-Spray oder lauwarmes (nie heißes!) Wasser hilft — heißes Wasser sprengt die Scheibe.`,
  `Gegen Beschlagen von innen: Lüftung auf Frontscheibe, Klimaanlage an (entfeuchtet), kein feuchtes Zeug im Auto lassen.`,
  `Motor nicht zum „Warmlaufen“ im Stand laufen lassen — das ist verboten und bringt nichts.`],
 fehler:`Mit laufendem Motor im Stand enteisen — verboten (Bußgeld) und unnötig. Und: nur ein Guckloch freikratzen.`,
 warn:`Nie heißes Wasser auf die kalte Scheibe — der Temperatursprung kann das Glas springen lassen.`,
 tipp:`Eine übergelegte Frontscheibenabdeckung oder Karton am Abend spart am Morgen das ganze Kratzen.`},
{id:"innenraum",n:"Innenraum pflegen & entfeuchten",kat:"pflege",typ:"wartung",selbst:true,
 kurz:`Trockener Innenraum = klare Scheiben, kein Schimmel, kein Mief.`,
 lage:`Feuchtigkeit im Auto führt zu beschlagenen Scheiben, muffigem Geruch und Schimmel. Etwas Routine hält den Innenraum frisch und die Sicht klar.`,
 schritte:[
  `Fußmatten regelmäßig ausschütteln/reinigen; im Winter nasse Matten zum Trocknen herausnehmen.`,
  `Staubsaugen und Oberflächen mit passendem Reiniger abwischen (Kunststoff/Leder unterschiedlich).`,
  `Gegen Feuchtigkeit: Auto gut durchlüften, Entfeuchterkissen nutzen, den Pollenfilter jährlich tauschen lassen (gegen Mief und für die Klimaleistung).`,
  `Scheiben von innen mit Glasreiniger putzen — der Belag von innen verursacht das nächtliche Blenden.`],
 fehler:`Nasse Fußmatten und feuchte Jacken tagelang im Auto lassen — das ist die Hauptquelle für beschlagene Scheiben und Schimmel.`,
 tipp:`Innenscheiben-Putzen ist das unterschätzte Sicherheits-Upgrade: Der dünne Film von innen ist es, der bei Nacht und Gegenlicht blendet.`},

/* -- Kosten & Kauf -- */
{id:"kostenrechnung",n:"Was ein Auto wirklich kostet",kat:"kosten",typ:"kosten",
 kurz:`Der Kaufpreis ist die Spitze des Eisbergs — die Wahrheit steht in den monatlichen Kosten.`,
 lage:`Ein Auto ist nach der Miete oft der zweitgrößte Haushaltsposten. Wer nur auf den Kaufpreis schaut, verrechnet sich — die laufenden Kosten machen den Unterschied.`,
 schritte:[
  `Alle Posten zusammenrechnen: Wertverlust (meist der größte!), Sprit/Strom, Versicherung, Steuer, Wartung/Reparatur, Reifen, TÜV, Parken.`,
  `Wertverlust beachten: Neuwagen verlieren in den ersten Jahren am stärksten — junge Gebrauchte umgehen diesen Sprung.`,
  `Monatliche Gesamtkosten ehrlich ausrechnen (Jahreskosten ÷ 12) und mit dem Budget abgleichen.`,
  `Alternativen gegenrechnen: Bei wenig Fahrleistung können ÖPNV, Carsharing oder ein Mietwagen fürs Wochenende günstiger sein.`],
 fehler:`Nur Kaufpreis und Spritkosten sehen — der Wertverlust ist oft der größte Posten und taucht auf keiner Rechnung auf.`,
 tipp:`Rechne deine Kosten pro Kilometer aus (Jahreskosten ÷ Jahreskilometer). Diese eine Zahl macht jede Fahrt und jeden Autokauf ehrlich vergleichbar.`},
{id:"gebrauchtkauf",n:"Gebrauchtwagen prüfen",kat:"kosten",typ:"kosten",
 kurz:`Papiere, Historie, Rost, Probefahrt — und im Zweifel ein Profi-Check.`,
 lage:`Beim Gebrauchtkauf trennt Sorgfalt das Schnäppchen vom Fass ohne Boden. Ein System schützt vor teuren Überraschungen.`,
 schritte:[
  `Papiere prüfen: Zulassungsbescheinigung I und II, Serviceheft, TÜV-Berichte, Anzahl der Vorbesitzer, Kilometerstand plausibel?`,
  `Zustand checken: Rost (Radläufe, Schweller, Unterboden), gleichmäßige Spaltmaße (Unfall?), Reifenalter, Ölstand, Flüssigkeiten.`,
  `Probefahrt auch auf der Autobahn: Motorlauf, Schaltung, Bremsen, Geradeauslauf, Warnleuchten, Geräusche.`,
  `Bei Unsicherheit einen Gebrauchtwagen-Check (Prüforganisation) machen lassen — das Geld ist gut investiert.`],
 fehler:`Auf Verkäuferdruck („andere Interessenten warten“) schnell unterschreiben — genau darauf zielt die Masche.`,
 warn:`Vorsicht bei „Privatverkauf ohne Gewährleistung“ mit Traumpreis, gedrängtem Verkauf und Barzahlung — klassische Betrugsmerkmale (siehe Kompendium „Sicher im Netz“).`,
 tipp:`Kalter Motor bei der Besichtigung ist Pflicht: Ein schon warmgelaufener Motor kann Startprobleme verstecken. Unangekündigt kommen.`},
{id:"werkstattrechnung",n:"Werkstattrechnung verstehen",kat:"kosten",typ:"kosten",
 kurz:`Kostenvoranschlag, freie Werkstatt, Altteile — deine Rechte sparen bares Geld.`,
 lage:`Bei Reparaturen bist du dem Preis nicht ausgeliefert. Ein paar Grundregeln senken die Rechnung und schützen vor bösen Überraschungen.`,
 schritte:[
  `Vor der Reparatur einen schriftlichen Kostenvoranschlag verlangen; bei größeren Summen einen zweiten einholen.`,
  `Wissen: Nach Ablauf der Neuwagen-Garantie darf eine freie Werkstatt warten, ohne dass Ansprüche verfallen — oft deutlich günstiger.`,
  `Auf der Rechnung Arbeitszeit (Stundensatz × Arbeitswerte) und Teile getrennt prüfen; nach Alternativen zu teuren Originalteilen fragen.`,
  `Bei Reklamation: Gewährleistung auf die Reparatur nutzen und die alten Teile zeigen lassen.`],
 fehler:`Einen Blankoauftrag „reparieren Sie mal alles“ erteilen — ohne Kostenrahmen kann die Rechnung explodieren.`,
 tipp:`Ein Satz spart oft dreistellig: „Bitte rufen Sie mich an, bevor über X Euro hinaus etwas gemacht wird.“ Schriftlich auf den Auftrag.`},
{id:"tuev",n:"TÜV / Hauptuntersuchung vorbereiten",kat:"kosten",typ:"kosten",selbst:true,
 kurz:`Ein Vorab-Check zu Hause verhindert die teure Nachprüfung.`,
 lage:`Die Hauptuntersuchung (HU, umgangssprachlich „TÜV“) ist alle zwei Jahre Pflicht (Neuwagen erst nach drei Jahren). Wer vorher die einfachen Punkte prüft, spart sich die Nachuntersuchung.`,
 schritte:[
  `Termin nicht verpassen: Fälligkeit an der Plakette hinten am Kennzeichen ablesen; Überziehen kann teurer werden.`,
  `Selbst-Vorcheck: alle Lampen, Reifenprofil, Wischer, Scheibenwaschanlage, Hupe, Warndreieck/Weste/Verbandkasten, Ölstand, keine Warnleuchten.`,
  `Sichtbare Mängel (durchgebrannte Lampe, abgefahrene Reifen) vorher beheben.`,
  `Zur HU die Zulassungsbescheinigung I mitnehmen.`],
 fehler:`Mit einer bekannten defekten Lampe zur HU fahren — „erheblicher Mangel“, Nachuntersuchung, doppelte Wege.`,
 tipp:`Die kostenlose Lampen- und Sicht-Runde am Abend vor dem Termin spart im Schnitt eine komplette Nachprüfung.`},
{id:"spritsparen",n:"Sprit sparen im Alltag",kat:"kosten",typ:"kosten",selbst:true,
 kurz:`Vorausschauend fahren schlägt jeden Spritspar-Mythos — und schont die Bremsen gleich mit.`,
 lage:`Der Verbrauch hängt stark vom Fahrstil ab. Ein paar Gewohnheiten senken die Spritrechnung spürbar, ganz ohne neues Auto.`,
 schritte:[
  `Früh hochschalten, niedertourig fahren; vorausschauend rollen lassen statt bremsen (Schubabschaltung spart im Schub sogar ganz).`,
  `Reifendruck korrekt halten (siehe Reifen-Check) — zu wenig Druck kostet dauerhaft Sprit.`,
  `Ballast und unnötige Dachträger raus — Gewicht und Luftwiderstand kosten.`,
  `Kurzstrecken bündeln oder ersetzen; Motor bei längerem Stehen (über ~20 Sek.) aus (Start-Stopp).`],
 fehler:`Im Stand „warmlaufen“ lassen — verbraucht, verschleißt und ist verboten. Moderne Motoren fährt man sanft warm.`,
 tipp:`Der größte Hebel ist der rechte Fuß: Wer 10 km/h langsamer und gleichmäßiger fährt, spart oft mehr als jedes Spar-Gadget.`},

/* -- Ergänzung: Reifen/Motor/Licht/Pflege/Kosten/Panne -- */
{id:"winterreifen",n:"Winterreifen: Pflicht & Zeitraum",kat:"reifen",typ:"wartung",
 kurz:`In Deutschland gilt situative Winterreifenpflicht — es zählt das Wetter, nicht das Datum.`,
 lage:`Bei Glatteis, Schneematsch, Schnee- oder Reifglätte dürfen nur geeignete Winterreifen (Alpine-Symbol „Bergpiktogramm mit Schneeflocke“) gefahren werden. Ein festes Kalenderdatum gibt es nicht — die Faustregel „von O bis O“ ist nur eine Orientierung.`,
 schritte:[
  `Am Reifen auf das Alpine-Symbol achten (Berg mit Schneeflocke) — nur dieses ist wintertauglich; das alte „M+S“ allein genügt bei Neureifen nicht mehr.`,
  `Bei winterlichen Verhältnissen ohne passende Reifen droht Bußgeld — und bei einem Unfall Ärger mit der Versicherung.`,
  `Ganzjahresreifen mit Alpine-Symbol sind ein Kompromiss für Wenigfahrer in milden Regionen.`,
  `Reifendruck im Winter prüfen — Kälte senkt den Druck.`],
 fehler:`Aufs Datum statt aufs Wetter schauen: Ein früher Wintereinbruch im Oktober verlangt schon Winterreifen.`,
 tipp:`Das Alpine-Symbol ist das einzige, das zählt — beim Reifenkauf gezielt darauf achten, nicht nur auf „Winterreifen“ im Werbetext.`},
{id:"einlagern",n:"Räder einlagern",kat:"reifen",typ:"wartung",selbst:true,
 kurz:`Richtig gelagert halten Reifen Jahre länger — falsch gelagert altern sie im Keller.`,
 lage:`Die halbjährlich abmontierten Räder wollen richtig gelagert sein: kühl, dunkel, trocken und vor allem gekennzeichnet, damit die Rotation stimmt.`,
 schritte:[
  `Vor dem Einlagern reinigen, auf Schäden prüfen und die Position markieren (VL/VR/HL/HR mit Kreide oder Aufkleber).`,
  `Kompletträder (Reifen auf Felge) liegend stapeln oder hängen; Reifen ohne Felge stehend lagern und gelegentlich drehen.`,
  `Kühl, trocken, dunkel und fern von Öl, Lösungsmitteln und Ozonquellen (Elektromotoren) lagern.`,
  `Reifendruck vor dem Einlagern leicht erhöhen; beim nächsten Wechsel korrekt einstellen.`],
 fehler:`Reifen in der prallen Sonne oder neben Chemie lagern — beides macht das Gummi vorzeitig spröde.`,
 tipp:`Kein Platz oder keine Lust? Viele Werkstätten bieten Reifeneinlagerung inklusive Wechsel — oft günstiger als gedacht und rückenschonend.`},
{id:"riemen",n:"Zahnriemen & Keilriemen im Blick",kat:"motor",typ:"wartung",
 kurz:`Der Zahnriemen ist unsichtbar — reißt er, ist oft der ganze Motor hin.`,
 lage:`Der Zahnriemen steuert die Motorsteuerung und muss nach festem Intervall (Kilometer ODER Jahre, je nachdem was zuerst kommt) gewechselt werden. Reißt er, drohen kapitale Motorschäden. Manche Motoren haben stattdessen eine wartungsarme Steuerkette.`,
 schritte:[
  `Im Serviceheft/Bordbuch das Wechselintervall des Zahnriemens nachschlagen (Kilometer und Jahre).`,
  `Intervall NICHT überziehen — auch bei wenig Fahrleistung altert der Riemen mit der Zeit.`,
  `Beim Gebrauchtkauf gezielt nach dem letzten Zahnriemenwechsel fragen (Beleg zeigen lassen).`,
  `Quietschen beim Kaltstart deutet oft auf den (anderen) Keilrippenriemen hin — prüfen lassen.`],
 fehler:`Das Zahnriemen-Intervall aussitzen, weil „das Auto ja läuft“ — der Riss kommt ohne Vorwarnung und zerstört den Motor.`,
 werkstatt:`Zahnriemenwechsel ist reine Werkstattarbeit; sinnvollerweise Wasserpumpe und Spannrolle gleich mitwechseln.`,
 tipp:`Vor jedem Gebrauchtkauf die eine Frage: „Wann wurde der Zahnriemen gemacht?“ — ohne Beleg den fälligen Wechsel in den Preis einrechnen.`},
{id:"klima",n:"Klimaanlage warten",kat:"motor",typ:"wartung",
 kurz:`Auch im Winter kurz laufen lassen — und alle paar Jahre den Service machen.`,
 lage:`Die Klimaanlage entfeuchtet die Luft (klare Scheiben!) und braucht etwas Pflege: Kältemittel entweicht mit der Zeit, und im Verdampfer sammeln sich Keime, die müffeln.`,
 schritte:[
  `Klimaanlage ganzjährig regelmäßig nutzen — auch im Winter (entfeuchtet und hält die Dichtungen geschmeidig).`,
  `Gegen Mief: einige Minuten vor dem Abstellen die Klimaanlage aus, Gebläse an — der Verdampfer trocknet.`,
  `Pollenfilter (Innenraumfilter) jährlich tauschen lassen — er beeinflusst Geruch und Kühlleistung.`,
  `Klimaservice etwa alle 2 Jahre: Kältemittel prüfen/auffüllen, System auf Dichtheit checken.`],
 fehler:`Die Klimaanlage im Winter monatelang ausschalten — Dichtungen trocknen aus, das teure Kältemittel entweicht schneller.`,
 werkstatt:`Kühlt die Klimaanlage nicht mehr richtig, ist meist Kältemittel entwichen — das gehört (auch aus Umweltgründen) in die Fachwerkstatt.`,
 tipp:`Klimaanlage plus Umluft aus und Lüftung auf die Frontscheibe ist der schnellste Weg zur beschlagfreien Scheibe im Winter.`},
{id:"sicherung",n:"Sicherung im Auto wechseln",kat:"licht",typ:"wartung",selbst:true,
 kurz:`Wenn ein einzelner Verbraucher tot ist, ist oft nur eine Cent-Sicherung durch.`,
 lage:`Fällt plötzlich nur die Zigarettenanzünder-Buchse, das Radio oder ein Fensterheber aus, ist häufig eine Stecksicherung durchgebrannt — ein günstiger Selbstfix.`,
 schritte:[
  `Sicherungskasten finden (Bordbuch: oft im Fußraum, hinter einer Klappe im Armaturenbrett oder im Motorraum).`,
  `Belegungsplan im Deckel oder Bordbuch nutzen, um die richtige Sicherung zu finden.`,
  `Verdächtige Sicherung mit der Plastikzange herausziehen; durchgebrannt = der Draht innen ist unterbrochen.`,
  `Durch eine NEUE mit exakt gleicher Ampere-Zahl (Farbe!) ersetzen — Ersatzsicherungen liegen oft im Kasten.`],
 fehler:`Eine Sicherung mit höherem Ampere-Wert einsetzen (oder gar überbrücken) — Brandgefahr; die Sicherung schützt die Leitung.`,
 werkstatt:`Brennt die neue Sicherung sofort wieder durch, liegt ein Kurzschluss vor — das gehört in die Werkstatt, nicht zur nächsten Sicherung.`,
 tipp:`Ein Zwei-Euro-Sortiment Ersatzsicherungen im Handschuhfach macht dich beim häufigsten Elektrik-Zwischenfall sofort handlungsfähig.`},
{id:"steinschlag",n:"Steinschlag & kleine Lackschäden",kat:"pflege",typ:"wartung",selbst:true,
 kurz:`Schnell handeln stoppt Rost und den wachsenden Riss in der Scheibe.`,
 lage:`Ein Steinschlag in der Frontscheibe kann sich zum Riss ausweiten; ein Lackkratzer bis aufs Blech beginnt zu rosten. Frühes Handeln ist billiger als die Folge.`,
 schritte:[
  `Steinschlag in der Scheibe zügig reparieren lassen — im frühen Stadium oft günstig und teils von der Teilkasko übernommen; ein Riss im Sichtfeld bedeutet Scheibentausch.`,
  `Kleine Lackkratzer: reinigen, entfetten, mit Lackstift im Farbton (Farbcode am Typenschild) dünn auffüllen.`,
  `Kratzer bis aufs Blech nicht offen lassen — Rost frisst sich sonst weiter.`,
  `Tiefe oder großflächige Schäden in die Lackierwerkstatt geben.`],
 fehler:`Den Steinschlag „beobachten“ — Temperaturwechsel und Erschütterung lassen ihn zum Riss werden, dann hilft nur der teure Scheibentausch.`,
 tipp:`Den Farbcode deines Autos (Typenschild/Serviceheft) einmal notieren — mit ihm bekommst du den exakt passenden Lackstift.`},
{id:"versicherung",n:"Kfz-Versicherung & SF-Klasse",kat:"kosten",typ:"kosten",
 kurz:`Haftpflicht ist Pflicht — bei Kasko und Beitrag lohnt der jährliche Vergleich.`,
 lage:`Die Kfz-Haftpflicht ist gesetzlich vorgeschrieben; Teil- und Vollkasko sind freiwillig. Der Beitrag hängt stark von der schadenfreien Zeit (SF-Klasse) ab — und lässt sich durch Wechsel oft senken.`,
 schritte:[
  `Bedarf klären: Neuwagen/junge Gebrauchte meist Vollkasko; ältere Autos oft nur Teilkasko oder Haftpflicht.`,
  `SF-Klasse verstehen: Jedes unfallfreie Jahr verbessert die Einstufung und senkt den Beitrag; ein Schaden stuft zurück.`,
  `Kleinschäden selbst zahlen, wenn die Rückstufung teurer wäre als der Schaden (die Versicherung nennt dir den Vergleichsbetrag).`,
  `Einmal im Jahr vergleichen und bis zum Stichtag (meist 30. November) kündigen/wechseln.`],
 fehler:`Jeden Kleinschaden melden — die Höherstufung kann über Jahre mehr kosten als die Reparatur selbst.`,
 tipp:`Vor der Schadensmeldung fragen: „Was kostet mich die Rückstufung insgesamt?“ Liegt sie über dem Schaden, lieber selbst zahlen (siehe Kompendium „Papierkram“, Stichtag 30.11.).`},
{id:"falschtanken",n:"Falschen Kraftstoff getankt",kat:"panne",typ:"panne",
 kurz:`Diesel in den Benziner oder umgekehrt: NICHT starten — das ist die halbe Rettung.`,
 lage:`Der Griff zur falschen Zapfsäule passiert schnell. Entscheidend ist, was danach kommt: Solange der Motor nicht gestartet wurde, bleibt der Schaden meist überschaubar.`,
 schritte:[
  `Auf keinen Fall den Motor starten und die Zündung ausgelassen lassen — schon das Einschalten der Zündung kann die Pumpe fördern lassen.`,
  `Auto (schiebend) aus dem Weg an einen sicheren Ort bringen.`,
  `Tankstellenpersonal informieren und einen Pannendienst/Abschlepper zum Abpumpen rufen.`,
  `Falschmenge abpumpen lassen; kleine Beimengungen sind je nach Kombination unterschiedlich kritisch — im Zweifel Fachrat einholen.`],
 fehler:`„Wird schon gehen“ und losfahren — der falsche Kraftstoff im Einspritzsystem verursacht dann die teuren Schäden.`,
 warn:`Besonders kritisch: Benzin im Diesel. Nicht starten, nicht die Zündung anschalten, sondern abpumpen lassen.`,
 tipp:`Merksatz an der Zapfsäule, falls es passiert: „Nicht starten, abpumpen.“ Diese drei Worte retten oft den Motor.`}
];
