/* HeiBen — Behördengänge: welches Amt, welche Frist, welche Unterlagen.
   Datenbasis für behoerden.html. Schema je Eintrag:
   {id,n,kat,typ:"frist"|"termin"|"online"|"jederzeit",frist(opt),wo,mit,kosten,
    dauer,ablauf,achtung(opt),digital(opt),tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten.

   ZUR GENAUIGKEIT: Fristen sind Bundesrecht und hier konkret benannt.
   Gebühren und Bearbeitungszeiten setzen Länder und Kommunen — sie stehen
   darum als typische Werte („in der Regel", „je nach Stadt"). Wer es genau
   braucht, schaut beim eigenen Amt nach; das sagt jeder Steckbrief auch.
   Stand der Angaben: 2026. */

window.BH_KAT={
  umzug:"Umzug & Meldung", ausweis:"Ausweise & Urkunden", familie:"Familie & Standesamt",
  arbeit:"Arbeit & Selbständigkeit", fahrzeug:"Fahrzeug & Führerschein",
  geld:"Geld vom Staat", ende:"Vorsorge & Todesfall"
};
window.BH_TYP={
  frist:"Frist läuft", termin:"Termin nötig", online:"Geht digital", jederzeit:"Ohne Frist"
};

window.BEHOERDEN=[

/* ---------- Umzug & Meldung ---------- */
{id:"ummelden", n:"Wohnsitz ummelden", kat:"umzug", typ:"frist",
 frist:`Zwei Wochen nach dem Einzug (§ 17 Bundesmeldegesetz).`,
 wo:`Bürgeramt, Einwohnermeldeamt oder Bürgerbüro der NEUEN Stadt. Die alte Stadt erfährt es automatisch — eine getrennte Abmeldung gibt es innerhalb Deutschlands nicht.`,
 mit:`Personalausweis oder Reisepass aller anzumeldenden Personen, ausgefüllter Meldeschein, Wohnungsgeberbestätigung des Vermieters.`,
 kosten:`Meist gebührenfrei. Einzelne Kommunen verlangen eine kleine Gebühr.`,
 dauer:`Im Termin erledigt, die neue Adresse steht sofort im Ausweis-Aufkleber.`,
 ablauf:`Termin buchen (in Großstädten Wochen im Voraus!), Wohnungsgeberbestätigung vom Vermieter holen, mit allen Ausweisen hingehen, Adressaufkleber bekommen.`,
 achtung:`Die Zwei-Wochen-Frist ist bußgeldbewehrt. Wer nicht rechtzeitig einen Termin bekommt, sollte die Terminbestätigung aufheben — sie belegt den Versuch.`,
 digital:`Einige Länder bieten die elektronische Wohnsitzanmeldung mit Online-Ausweis an. Wo es sie gibt, spart sie den Termin komplett.`,
 tipp:`Termin buchen, BEVOR der Umzugswagen kommt. Die Wartezeiten sind der eigentliche Engpass, nicht das Amt.`},

{id:"wohnungsgeberbestaetigung", n:"Wohnungsgeberbestätigung", kat:"umzug", typ:"frist",
 frist:`Der Vermieter muss sie binnen zwei Wochen nach Einzug ausstellen.`,
 wo:`Kein Amt — der Vermieter oder die Hausverwaltung stellt sie aus.`,
 mit:`Nichts. Der Vermieter braucht nur Namen und Einzugsdatum.`,
 kosten:`Kostenlos. Wer dafür Geld verlangt, tut das zu Unrecht.`,
 dauer:`Ein Formular, eine Unterschrift.`,
 ablauf:`Vordruck herunterladen (jede Stadt hat einen), Vermieter ausfüllen und unterschreiben lassen, zum Meldetermin mitnehmen.`,
 achtung:`Ohne sie geht die Ummeldung nicht. Wer allein in eine eigene Wohnung zieht und selbst Eigentümer ist, bestätigt sich selbst.`,
 tipp:`Beim Wohnungsübergabetermin gleich mit unterschreiben lassen — später ist der Vermieter schwerer zu greifen.`},

{id:"abmelden-ausland", n:"Abmeldung ins Ausland", kat:"umzug", typ:"frist",
 frist:`Frühestens eine Woche vor dem Auszug, spätestens zwei Wochen danach.`,
 wo:`Bürgeramt der bisherigen Stadt.`,
 mit:`Personalausweis oder Reisepass, Abmeldeformular.`,
 kosten:`In der Regel gebührenfrei.`,
 dauer:`Sofort. Man bekommt eine Abmeldebestätigung.`,
 ablauf:`Formular ausfüllen, abgeben oder per Post schicken (in vielen Städten möglich), Bestätigung aufbewahren.`,
 achtung:`Innerhalb Deutschlands gibt es KEINE Abmeldung — nur bei Wegzug ins Ausland oder Aufgabe einer Nebenwohnung.`,
 tipp:`Die Abmeldebestätigung gut aufheben: Rundfunkbeitrag, Krankenkasse und Finanzamt fragen später danach.`},

{id:"zweitwohnsitz", n:"Nebenwohnung anmelden", kat:"umzug", typ:"frist",
 frist:`Zwei Wochen nach Bezug, wie bei jeder Anmeldung.`,
 wo:`Bürgeramt der Stadt, in der die Nebenwohnung liegt.`,
 mit:`Ausweis, Meldeschein, Wohnungsgeberbestätigung.`,
 kosten:`Die Anmeldung meist frei — die Zweitwohnungsteuer nicht. Sie liegt je nach Stadt bei mehreren Prozent der Jahreskaltmiete.`,
 dauer:`Im Termin erledigt.`,
 ablauf:`Anmelden, dabei festlegen, welche Wohnung Haupt- und welche Nebenwohnung ist.`,
 achtung:`Hauptwohnung ist die vorwiegend genutzte. Wer das falsch angibt, riskiert Nachzahlungen — die Städte gleichen ab.`,
 tipp:`Studierende und Azubis prüfen vorher, ob ihre Stadt eine Befreiung von der Zweitwohnungsteuer kennt.`},

{id:"nachsendeauftrag", n:"Nachsendeauftrag", kat:"umzug", typ:"online",
 wo:`Kein Amt — der Postdienstleister. Online, in der Filiale oder per Formular.`,
 mit:`Alte und neue Adresse, Ausweis bei Beauftragung in der Filiale.`,
 kosten:`Kostenpflichtig, gestaffelt nach Laufzeit (6, 12 oder 24 Monate).`,
 dauer:`Einrichtung dauert einige Werktage — rechtzeitig vor dem Umzug beauftragen.`,
 ablauf:`Online beauftragen, Startdatum setzen, in der Laufzeit alle Absender nach und nach auf die neue Adresse umstellen.`,
 achtung:`Kein Behördengang, aber der wirksamste Schutz davor, eine Frist zu verpassen, weil Post an die alte Adresse ging.`,
 tipp:`Die nachgesendeten Briefe sind eine kostenlose Checkliste: Jeder Absender, der noch auftaucht, muss umgemeldet werden.`},

/* ---------- Ausweise & Urkunden ---------- */
{id:"personalausweis", n:"Personalausweis beantragen", kat:"ausweis", typ:"termin",
 frist:`Ausweispflicht ab 16. Der Ausweis gilt zehn Jahre, bei Antrag vor dem 24. Geburtstag sechs Jahre.`,
 wo:`Bürgeramt am Hauptwohnsitz.`,
 mit:`Biometrisches Passfoto (oder Foto vor Ort, wo angeboten), alter Ausweis oder Geburtsurkunde, bei Namensabweichung die Heirats- oder Namensänderungsurkunde.`,
 kosten:`In der Regel 37 €; unter 24 Jahren ermäßigt. Gebühren sind bundesweit geregelt und ändern sich gelegentlich.`,
 dauer:`Zwei bis vier Wochen bis zur Abholung. Für Eilfälle gibt es den vorläufigen Ausweis — sofort, aber kürzer gültig und ohne Online-Funktion.`,
 ablauf:`Termin buchen, Foto mitbringen, Fingerabdrücke abgeben (seit 2021 Pflicht), PIN-Brief abwarten, Ausweis abholen.`,
 achtung:`Ab 2024 werden Passfotos in vielen Ämtern nur noch digital übermittelt. Wer beim Fotografen war, braucht den passenden digitalen Nachweis — vorher fragen, was das eigene Amt akzeptiert.`,
 digital:`Die Online-Ausweisfunktion (eID) steckt in jedem neuen Ausweis. Einmal aktiviert, erspart sie später viele Behördengänge.`,
 tipp:`Ablaufdatum beim Ausstellen in den Kalender eintragen — mit Erinnerung drei Monate vorher. Ein abgelaufener Ausweis ist die häufigste vermeidbare Terminnot.`},

{id:"reisepass", n:"Reisepass beantragen", kat:"ausweis", typ:"termin",
 frist:`Keine Pflicht — aber ohne Pass geht es in viele Länder außerhalb der EU nicht.`,
 wo:`Bürgeramt am Hauptwohnsitz.`,
 mit:`Biometrisches Passfoto, Personalausweis, bei Kindern Geburtsurkunde und Einverständnis beider Sorgeberechtigten.`,
 kosten:`Deutlich teurer als der Personalausweis; unter 24 Jahren ermäßigt. Express kostet extra.`,
 dauer:`Drei bis sechs Wochen. Der Express-Pass ist in wenigen Werktagen da.`,
 ablauf:`Termin buchen, Antrag stellen, Fingerabdrücke abgeben, Pass abholen (persönlich, mit dem alten Pass).`,
 achtung:`Seit Anfang 2024 werden keine Kinderreisepässe mehr ausgestellt. Kinder brauchen einen eigenen Reisepass — das dauert genauso lange wie bei Erwachsenen.`,
 tipp:`Viele Länder verlangen, dass der Pass bei der Einreise noch sechs Monate gültig ist. Vor der Buchung das Ablaufdatum prüfen, nicht nach.`},

{id:"fuehrungszeugnis", n:"Führungszeugnis", kat:"ausweis", typ:"online",
 wo:`Bürgeramt — oder direkt beim Bundesamt für Justiz online.`,
 mit:`Personalausweis. Für das erweiterte Führungszeugnis zusätzlich die schriftliche Aufforderung der Stelle, die es verlangt.`,
 kosten:`13 € (bundesweit einheitlich). Befreiung ist bei Ehrenamt möglich.`,
 dauer:`Etwa zwei Wochen bis zur Zustellung. Es kommt per Post, nicht sofort.`,
 ablauf:`Online mit Online-Ausweisfunktion beantragen oder im Bürgeramt beantragen, Gebühr zahlen, warten. Es wird an die Meldeadresse oder an die angegebene Behörde geschickt.`,
 achtung:`Das ERWEITERTE Führungszeugnis (für Arbeit mit Kindern und Jugendlichen) bekommt man nur mit der Aufforderung des Arbeitgebers — ohne sie stellt das Amt das einfache aus, und man zahlt zweimal.`,
 digital:`Mit aktivierter Online-Ausweisfunktion geht der ganze Antrag vom Sofa aus.`,
 tipp:`Zwei Wochen Vorlauf einplanen. Wer es „bis Montag" braucht, hat schon verloren.`},

{id:"meldebescheinigung", n:"Meldebescheinigung", kat:"ausweis", typ:"online",
 wo:`Bürgeramt, in vielen Städten auch online oder am Bürgerterminal.`,
 mit:`Personalausweis.`,
 kosten:`Wenige Euro, je nach Kommune.`,
 dauer:`Sofort.`,
 ablauf:`Beantragen, Gebühr zahlen, ausgedruckt mitnehmen.`,
 achtung:`Die einfache Meldebescheinigung reicht fast immer. Die erweiterte enthält mehr Daten und wird nur verlangt, wenn es ausdrücklich dasteht.`,
 tipp:`Beim Ummelde-Termin gleich eine mitbestellen — dann spart man sich den zweiten Gang, wenn Bank oder Arbeitgeber danach fragen.`},

{id:"beglaubigung", n:"Amtliche Beglaubigung", kat:"ausweis", typ:"jederzeit",
 wo:`Bürgeramt, in vielen Fällen auch Kirchengemeinden, Schulen oder Notare — je nachdem, wer sie verlangt.`,
 mit:`Original und Kopie des Dokuments, eigener Ausweis.`,
 kosten:`Wenige Euro je Seite.`,
 dauer:`Sofort im Termin.`,
 ablauf:`Original und Kopie vorlegen, Stempel und Unterschrift bekommen.`,
 achtung:`Eine Beglaubigung bestätigt nur, dass die Kopie dem Original entspricht — nicht, dass der Inhalt stimmt. Für Unterschriften unter Verträgen braucht es oft den Notar.`,
 tipp:`Immer ein Exemplar mehr beglaubigen lassen als verlangt. Die zweite Kopie kostet Cent, der zweite Weg kostet einen Vormittag.`},

{id:"ausweis-verloren", n:"Ausweis verloren oder gestohlen", kat:"ausweis", typ:"frist",
 frist:`Sofort. Jeder Tag ohne Sperre ist ein Tag, an dem jemand anderes damit unterwegs sein kann.`,
 wo:`Sperrhotline für die Online-Ausweisfunktion, Polizei für die Anzeige, Bürgeramt für den neuen Ausweis.`,
 mit:`Für den neuen Ausweis: Passfoto, Anzeigebestätigung oder Verlusterklärung, falls vorhanden ein anderes Ausweisdokument.`,
 kosten:`Wie bei der Neuausstellung; manche Kommunen erheben zusätzlich eine Verlustgebühr.`,
 dauer:`Sperre in Minuten, neuer Ausweis in Wochen. Der vorläufige Ausweis überbrückt.`,
 ablauf:`Erst die eID sperren lassen, dann Anzeige erstatten, dann neuen Ausweis beantragen.`,
 achtung:`Bei Diebstahl unbedingt Anzeige erstatten. Sie ist der Nachweis, dass man den Ausweis nicht selbst weitergegeben hat.`,
 tipp:`Ausweisnummer und Sperrkennwort getrennt vom Ausweis notieren — im Passwort-Manager oder im Notfallordner.`},

/* ---------- Familie & Standesamt ---------- */
{id:"geburt-anzeigen", n:"Geburt anzeigen", kat:"familie", typ:"frist",
 frist:`Binnen einer Woche nach der Geburt (§ 18 Personenstandsgesetz).`,
 wo:`Standesamt des Geburtsorts — nicht des Wohnorts. Kliniken melden die Geburt meist selbst.`,
 mit:`Geburtsbescheinigung der Klinik, Personalausweise der Eltern, Geburtsurkunden der Eltern, bei Verheirateten die Eheurkunde, sonst Vaterschaftsanerkennung und Sorgeerklärung.`,
 kosten:`Die Beurkundung selbst ist frei; jede Urkunde kostet wenige Euro.`,
 dauer:`Ein bis drei Wochen bis zu den Urkunden.`,
 ablauf:`Unterlagen sammeln, Formular der Klinik ausfüllen, Standesamt beurkundet, Urkunden abholen oder zuschicken lassen.`,
 achtung:`Die Wochenfrist läuft ab dem Geburtstag — mitten in der anstrengendsten Woche des Lebens. Deshalb die Unterlagen VOR dem Termin zusammenlegen, am besten schon im letzten Schwangerschaftsmonat.`,
 tipp:`Gleich mehrere Geburtsurkunden bestellen: Krankenkasse, Elterngeldstelle und Kindergeldkasse wollen jeweils eine eigene.`},

{id:"vaterschaft", n:"Vaterschaft anerkennen", kat:"familie", typ:"termin",
 wo:`Standesamt, Jugendamt, Notar oder Amtsgericht — alle können es beurkunden.`,
 mit:`Ausweise beider Elternteile, Geburtsurkunden, bei bereits geborenem Kind dessen Geburtsurkunde.`,
 kosten:`Beim Jugendamt und Standesamt in der Regel kostenlos.`,
 dauer:`Ein Termin.`,
 ablauf:`Gemeinsam hingehen, Erklärung abgeben, Zustimmung der Mutter protokollieren lassen, Urkunde erhalten.`,
 achtung:`Ohne Anerkennung ist der Vater rechtlich nicht der Vater — das betrifft Sorgerecht, Unterhalt und Erbrecht.`,
 tipp:`Schon vor der Geburt möglich und dann deutlich ruhiger zu erledigen. Viele Ämter bieten dafür einen gemeinsamen Termin mit der Sorgeerklärung an.`},

{id:"sorgeerklaerung", n:"Gemeinsame Sorge erklären", kat:"familie", typ:"termin",
 wo:`Jugendamt oder Notar.`,
 mit:`Ausweise beider Elternteile, Geburtsurkunde des Kindes, Vaterschaftsanerkennung.`,
 kosten:`Beim Jugendamt kostenlos, beim Notar gebührenpflichtig.`,
 dauer:`Ein Termin.`,
 ablauf:`Beide Elternteile erscheinen, erklären die gemeinsame Sorge, bekommen eine Bescheinigung.`,
 achtung:`Sind die Eltern nicht verheiratet, hat ohne diese Erklärung allein die Mutter das Sorgerecht. Das überrascht viele erst im Ernstfall.`,
 tipp:`Bescheinigung zu den wichtigen Papieren legen — Kita, Klinik und Schule fragen danach.`},

{id:"eheschliessung", n:"Eheschließung anmelden", kat:"familie", typ:"termin",
 frist:`Die Anmeldung gilt sechs Monate. Wer später heiratet, meldet erneut an.`,
 wo:`Standesamt am Wohnort eines der beiden. Geheiratet werden kann danach bundesweit.`,
 mit:`Ausweise, beglaubigte Abschriften aus dem Geburtenregister (nicht die alte Geburtsurkunde), Meldebescheinigungen, bei Vorehen die Eheurkunde mit Scheidungsvermerk.`,
 kosten:`Anmeldung und Trauung zusammen meist im mittleren zweistelligen Bereich; Trauung außerhalb der Amtsräume oder am Samstag kostet Aufschlag.`,
 dauer:`Anmeldung ein Termin, Prüfung ein bis vier Wochen.`,
 ablauf:`Unterlagen besorgen (das dauert am längsten), gemeinsam anmelden, Prüfung abwarten, Trautermin festlegen.`,
 achtung:`Bei Auslandsbezug — ausländische Staatsangehörigkeit, Vorehe im Ausland — verlängert sich alles erheblich. Dann mit mehreren Monaten rechnen.`,
 tipp:`Beglaubigte Abschrift aus dem Geburtenregister zuerst bestellen. Sie kommt vom Standesamt des Geburtsorts und ist oft der langsamste Baustein.`},

{id:"namensaenderung-ehe", n:"Name nach der Eheschließung", kat:"familie", typ:"jederzeit",
 wo:`Standesamt (Erklärung), danach Bürgeramt für die neuen Ausweise.`,
 mit:`Eheurkunde, Ausweise.`,
 kosten:`Die Erklärung kostet wenig, die neuen Ausweise die volle Gebühr.`,
 dauer:`Erklärung sofort, neue Dokumente wie bei jeder Neuausstellung.`,
 ablauf:`Namensführung erklären (geht auch später), neue Ausweise beantragen, danach alle Verträge umstellen.`,
 achtung:`Der Ausweis wird durch den Namenswechsel ungültig — ohne neuen Ausweis fehlt der Nachweis im Alltag.`,
 tipp:`Eine Liste aller Stellen anlegen, die den Namen führen: Bank, Arbeitgeber, Versicherung, Krankenkasse, Vermieter, Abos. Der Nachsendeauftrag der Namensänderung ist die eigene Sorgfalt.`},

{id:"kita-platz", n:"Kitaplatz beantragen", kat:"familie", typ:"frist",
 frist:`Rechtsanspruch ab dem vollendeten ersten Lebensjahr. Viele Städte verlangen die Anmeldung sechs bis zwölf Monate vorher.`,
 wo:`Je nach Stadt zentrales Online-Portal oder die Einrichtungen direkt.`,
 mit:`Geburtsurkunde, Meldebescheinigung, teils Arbeitsbescheinigungen der Eltern.`,
 kosten:`Die Anmeldung frei; die Beiträge richten sich nach Einkommen und Land.`,
 dauer:`Zusage oft erst wenige Monate vor Beginn.`,
 ablauf:`Portal der Stadt suchen, Wunschtermin und mehrere Einrichtungen angeben, Fristen der Stadt einhalten, Zusagen bestätigen.`,
 achtung:`Der Rechtsanspruch besteht — der Wunschplatz nicht. Wer keinen Platz bekommt, sollte das schriftlich geltend machen; das ist die Grundlage für alles Weitere.`,
 tipp:`Parallel mehrere Einrichtungen anmelden und Zusagen sofort beantworten. Ein nicht bestätigter Platz geht an den Nächsten.`},

/* ---------- Arbeit & Selbständigkeit ---------- */
{id:"steuer-id", n:"Steuer-Identifikationsnummer", kat:"arbeit", typ:"jederzeit",
 wo:`Bundeszentralamt für Steuern. Sie wird nach der Geburt oder nach der ersten Anmeldung in Deutschland automatisch vergeben.`,
 mit:`Nichts — sie ist schon da. Beim erneuten Zusenden: Name, Geburtsdatum, Meldeadresse.`,
 kosten:`Kostenlos.`,
 dauer:`Erneutes Zusenden dauert einige Wochen und geht nur an die Meldeadresse.`,
 ablauf:`In alten Steuerbescheiden, auf der Lohnabrechnung oder im Brief nach der Geburt nachsehen. Erst wenn nichts hilft, neu anfordern.`,
 achtung:`Sie ist lebenslang gleich und ändert sich weder bei Umzug noch bei Heirat. Verwechslungsgefahr mit der Steuernummer des Finanzamts — die ändert sich sehr wohl.`,
 tipp:`Einmal in den Notfallordner legen. Arbeitgeber, Bank und Kindergeldkasse fragen regelmäßig danach.`},

{id:"sozialversicherungsnummer", n:"Sozialversicherungsnummer", kat:"arbeit", typ:"jederzeit",
 wo:`Deutsche Rentenversicherung; im Alltag hilft die eigene Krankenkasse weiter.`,
 mit:`Ausweis, Krankenkasse.`,
 kosten:`Kostenlos.`,
 dauer:`Neuausstellung der Bescheinigung wenige Wochen.`,
 ablauf:`Bei der Krankenkasse anfragen — sie kennt die Nummer und stellt eine Bescheinigung aus.`,
 achtung:`Seit einigen Jahren gibt es keinen Ausweis aus Papier mehr, sondern eine Bescheinigung über die Versicherungsnummer.`,
 tipp:`Die Nummer steht auf jeder Renteninformation. Wer die jährlich abheftet, muss nie nachfragen.`},

{id:"arbeitsuchend-melden", n:"Arbeitsuchend melden", kat:"arbeit", typ:"frist",
 frist:`Spätestens drei Monate vor dem Ende des Arbeitsverhältnisses. Erfährt man später davon, binnen drei Tagen (§ 38 SGB III).`,
 wo:`Agentur für Arbeit — online, telefonisch oder vor Ort.`,
 mit:`Kündigung oder befristeter Vertrag, Personalausweis.`,
 kosten:`Kostenlos.`,
 dauer:`Die Meldung selbst ist in Minuten erledigt.`,
 ablauf:`Sofort nach Erhalt der Kündigung melden — auch wenn man schon eine neue Stelle in Aussicht hat.`,
 achtung:`Wer die Frist versäumt, riskiert eine Sperrzeit beim Arbeitslosengeld. Das ist der teuerste vermeidbare Fehler in diesem Kompendium.`,
 digital:`Die Meldung geht online; der persönliche Termin folgt später.`,
 tipp:`Arbeitsuchend melden ist NICHT dasselbe wie arbeitslos melden. Das eine passiert vor dem letzten Arbeitstag, das andere ab dem ersten Tag ohne Arbeit.`},

{id:"arbeitslos-melden", n:"Arbeitslos melden", kat:"arbeit", typ:"frist",
 frist:`Am ersten Tag der Arbeitslosigkeit. Rückwirkend gibt es kein Geld.`,
 wo:`Agentur für Arbeit.`,
 mit:`Ausweis, Arbeitsbescheinigung des Arbeitgebers, Kündigung, Sozialversicherungsnummer, Bankverbindung.`,
 kosten:`Kostenlos.`,
 dauer:`Erstes Geld meist im Folgemonat.`,
 ablauf:`Persönlich oder online melden, Antrag auf Arbeitslosengeld stellen, Unterlagen nachreichen.`,
 achtung:`Die Arbeitsbescheinigung kommt vom alten Arbeitgeber und ist oft der Grund für Verzögerungen. Früh danach fragen.`,
 tipp:`Der Anspruch beginnt mit der Meldung, nicht mit dem Antrag. Erst melden, Unterlagen dürfen nachkommen.`},

{id:"gewerbe-anmelden", n:"Gewerbe anmelden", kat:"arbeit", typ:"frist",
 frist:`Mit Aufnahme der Tätigkeit — nicht erst mit dem ersten Umsatz.`,
 wo:`Gewerbeamt oder Ordnungsamt der Stadt, in vielen Kommunen auch online.`,
 mit:`Personalausweis, bei erlaubnispflichtigen Gewerben die jeweilige Erlaubnis, bei ausländischer Staatsangehörigkeit ggf. der Aufenthaltstitel.`,
 kosten:`Je nach Stadt ein niedriger zweistelliger Betrag.`,
 dauer:`Die Anmeldung sofort. Danach melden sich Finanzamt, IHK oder Handwerkskammer von selbst.`,
 ablauf:`Formular ausfüllen, Tätigkeit genau beschreiben, Gewerbeschein erhalten.`,
 achtung:`Freie Berufe — etwa Ärzte, Anwälte, viele künstlerische und beratende Tätigkeiten — melden KEIN Gewerbe an, sondern nur beim Finanzamt. Die Abgrenzung entscheidet über Gewerbesteuer und Kammerbeiträge.`,
 tipp:`Die Tätigkeitsbeschreibung eher weit fassen. Eine Änderung kostet später wieder Gebühr und Zeit.`},

{id:"steuerliche-erfassung", n:"Fragebogen zur steuerlichen Erfassung", kat:"arbeit", typ:"frist",
 frist:`Binnen eines Monats nach Aufnahme der Tätigkeit.`,
 wo:`Finanzamt — elektronisch über das Steuerportal der Verwaltung.`,
 mit:`Steuer-Identifikationsnummer, erwartete Umsätze und Gewinne, Bankverbindung.`,
 kosten:`Kostenlos.`,
 dauer:`Steuernummer kommt in der Regel in zwei bis sechs Wochen.`,
 ablauf:`Elektronisch ausfüllen, Schätzungen angeben, absenden, Steuernummer abwarten.`,
 achtung:`Hier entscheidet man über die Kleinunternehmerregelung. Die Wahl bindet und lässt sich nicht beliebig zurücknehmen — vorher durchrechnen, ob die Kunden vorsteuerabzugsberechtigt sind.`,
 digital:`Der Fragebogen ist seit einigen Jahren elektronisch abzugeben. Papierformulare nimmt das Finanzamt in der Regel nicht mehr an.`,
 tipp:`Ohne Steuernummer darf keine Rechnung mit Umsatzsteuer geschrieben werden. Wer zum Monatsersten starten will, füllt den Fragebogen im Vormonat aus.`},

/* ---------- Fahrzeug & Führerschein ---------- */
{id:"kfz-zulassen", n:"Fahrzeug zulassen", kat:"fahrzeug", typ:"termin",
 wo:`Zulassungsstelle des Wohnorts, in vielen Kreisen auch online.`,
 mit:`Ausweis, Zulassungsbescheinigung Teil I und II, gültige Hauptuntersuchung, eVB-Nummer der Versicherung, SEPA-Mandat für die Kfz-Steuer, bei Gebrauchtwagen der Kaufvertrag.`,
 kosten:`Zulassung im niedrigen zweistelligen Bereich, Kennzeichen kommen dazu.`,
 dauer:`Im Termin erledigt.`,
 ablauf:`eVB-Nummer bei der Versicherung holen, Termin buchen, Unterlagen vollständig mitbringen, Kennzeichen prägen lassen, Plaketten bekommen.`,
 achtung:`Die eVB-Nummer ist der häufigste Stolperstein: ohne sie keine Zulassung, und sie gilt nur begrenzt.`,
 digital:`Die internetbasierte Fahrzeugzulassung funktioniert mit Online-Ausweisfunktion und den Sicherheitscodes auf Fahrzeugschein und Kennzeichen.`,
 tipp:`Vor dem Termin die Zulassungsbescheinigung Teil II („Fahrzeugbrief") suchen — sie liegt oft noch bei der Bank, wenn das Auto finanziert war.`},

{id:"kfz-abmelden", n:"Fahrzeug abmelden", kat:"fahrzeug", typ:"jederzeit",
 wo:`Jede Zulassungsstelle in Deutschland, nicht nur die eigene.`,
 mit:`Zulassungsbescheinigung Teil I, Kennzeichen mit Plaketten.`,
 kosten:`Geringe Gebühr.`,
 dauer:`Sofort.`,
 ablauf:`Kennzeichen abgeben, Abmeldebestätigung mitnehmen, Versicherung und Steuer enden automatisch.`,
 achtung:`Beim Verkauf: unbedingt die Veräußerungsanzeige machen oder auf der Ummeldung bestehen. Sonst haftet man weiter für Steuer, Versicherung und Bußgelder des Käufers.`,
 tipp:`Abmeldebestätigung aufheben, bis die letzte Steuerabrechnung und die Versicherungsrückzahlung da sind.`},

{id:"fuehrerschein-umtausch", n:"Führerschein umtauschen", kat:"fahrzeug", typ:"frist",
 frist:`Gestaffelt nach Geburtsjahr und Ausstellungsjahr — bis spätestens 2033 müssen alle alten Führerscheine getauscht sein.`,
 wo:`Fahrerlaubnisbehörde oder Bürgeramt, je nach Stadt.`,
 mit:`Alter Führerschein, biometrisches Passfoto, Personalausweis; bei Führerscheinen, die nicht am Wohnort ausgestellt wurden, eine Karteikartenabschrift.`,
 kosten:`Rund 25 bis 30 €, plus Karteikartenabschrift falls nötig.`,
 dauer:`Drei bis sechs Wochen.`,
 ablauf:`Eigene Frist anhand der Tabelle prüfen, Unterlagen sammeln, Antrag stellen, neuen Kartenführerschein abholen.`,
 achtung:`Es handelt sich um einen reinen Umtausch: keine neue Prüfung, keine ärztliche Untersuchung. Wer nach Ablauf seiner Frist fährt, riskiert ein Verwarnungsgeld.`,
 tipp:`Die Karteikartenabschrift bei der alten Ausstellungsbehörde anfordern, bevor man den Termin bucht — sie ist der langsamste Teil.`},

{id:"fuehrerschein-ersatz", n:"Führerschein verloren", kat:"fahrzeug", typ:"termin",
 wo:`Fahrerlaubnisbehörde am Wohnort.`,
 mit:`Ausweis, Passfoto, eidesstattliche Versicherung über den Verlust, bei Diebstahl die Anzeige, Karteikartenabschrift falls anderswo ausgestellt.`,
 kosten:`Ähnlich dem Umtausch, plus Gebühr für die Verlusterklärung.`,
 dauer:`Drei bis sechs Wochen; einen vorläufigen Nachweis gibt es auf Nachfrage.`,
 ablauf:`Verlust erklären, Antrag stellen, warten. Fahren ist in dieser Zeit erlaubt, aber ohne Dokument riskant.`,
 achtung:`Die Fahrerlaubnis geht nicht verloren — nur das Dokument. Wer angehalten wird, muss die Identität anderweitig nachweisen.`,
 tipp:`Eine Handyfotografie des Führerscheins im eigenen Cloud-Ordner erspart bei der Verlusterklärung viel Erinnerungsarbeit.`},

/* ---------- Geld vom Staat ---------- */
{id:"kindergeld", n:"Kindergeld beantragen", kat:"geld", typ:"frist",
 frist:`Rückwirkend werden höchstens sechs Monate gezahlt. Wer später beantragt, verliert den Rest.`,
 wo:`Familienkasse der Agentur für Arbeit.`,
 mit:`Geburtsurkunde des Kindes, Steuer-Identifikationsnummern von Kind und Eltern, Bankverbindung.`,
 kosten:`Kostenlos.`,
 dauer:`Vier bis acht Wochen bis zur ersten Zahlung, danach monatlich.`,
 ablauf:`Antrag online oder auf Papier stellen, Geburtsurkunde beifügen, Bescheid abwarten.`,
 achtung:`Bei volljährigen Kindern in Ausbildung muss jährlich nachgewiesen werden, dass die Voraussetzungen noch vorliegen. Ohne Nachweis endet die Zahlung.`,
 digital:`Der Antrag geht online; die Geburtsurkunde lässt sich hochladen.`,
 tipp:`Gleich nach der Geburtsurkunde beantragen — im selben Aufwasch wie das Elterngeld, die Unterlagen überschneiden sich fast vollständig.`},

{id:"elterngeld", n:"Elterngeld beantragen", kat:"geld", typ:"frist",
 frist:`Rückwirkend höchstens drei Monate (§ 7 BEEG). Das ist die kürzeste wirklich teure Frist nach einer Geburt.`,
 wo:`Elterngeldstelle des Landes oder der Kommune.`,
 mit:`Geburtsurkunde mit Verwendungszweck Elterngeld, Einkommensnachweise der letzten zwölf Monate, Bescheinigung des Arbeitgebers über die Elternzeit, Krankenkassennachweis.`,
 kosten:`Kostenlos.`,
 dauer:`Sechs bis zwölf Wochen. Bis zum Bescheid fließt kein Geld.`,
 ablauf:`Elternzeit beim Arbeitgeber anmelden, Unterlagen sammeln, Antrag stellen, Bescheid prüfen.`,
 achtung:`Die Aufteilung der Monate zwischen beiden Elternteilen lässt sich im Nachhinein nur begrenzt ändern. Vorher durchrechnen — Basiselterngeld, ElterngeldPlus und Partnermonate ergeben sehr verschiedene Summen.`,
 tipp:`Die Einkommensnachweise sind der Engpass. Wer sie schon in der Schwangerschaft sammelt, beantragt in einer halben Stunde statt an einem Wochenende.`},

{id:"wohngeld", n:"Wohngeld beantragen", kat:"geld", typ:"frist",
 frist:`Gezahlt wird ab dem Monat der Antragstellung, nicht rückwirkend.`,
 wo:`Wohngeldstelle der Stadt oder des Kreises.`,
 mit:`Mietvertrag, Einkommensnachweise aller Haushaltsmitglieder, Mietbescheinigung des Vermieters, Ausweise.`,
 kosten:`Kostenlos.`,
 dauer:`Je nach Stadt mehrere Wochen bis Monate.`,
 ablauf:`Antrag holen, Mietbescheinigung vom Vermieter ausfüllen lassen, Einkommen belegen, abgeben.`,
 achtung:`Wer Bürgergeld oder BAföG mit Wohnkostenanteil bezieht, ist in der Regel vom Wohngeld ausgeschlossen — beides gleichzeitig geht nicht.`,
 tipp:`Lieber unvollständig einreichen und nachreichen, als auf das letzte Papier zu warten: Das Antragsdatum zählt, nicht das Datum der Vollständigkeit.`},

{id:"bafoeg", n:"BAföG beantragen", kat:"geld", typ:"frist",
 frist:`Leistungen gibt es ab dem Monat der Antragstellung — nie davor.`,
 wo:`Amt für Ausbildungsförderung der Hochschule oder des Kreises.`,
 mit:`Immatrikulationsbescheinigung, Einkommensnachweise der Eltern aus dem vorletzten Jahr, eigene Nachweise, Bankverbindung.`,
 kosten:`Kostenlos.`,
 dauer:`Sechs bis zwölf Wochen; vorläufige Zahlungen sind möglich.`,
 ablauf:`Online beantragen, Formblätter zuordnen, Nachweise hochladen, Bescheid prüfen.`,
 achtung:`Es zählt das Einkommen der Eltern im vorletzten Kalenderjahr. Ist das Einkommen inzwischen deutlich gesunken, gibt es den Aktualisierungsantrag — den muss man aber ausdrücklich stellen.`,
 digital:`Der Antrag läuft in allen Ländern digital; Formblätter lassen sich zwischenspeichern.`,
 tipp:`Einen formlosen Antrag zum Monatsanfang stellen („Hiermit beantrage ich Ausbildungsförderung"), Unterlagen nachreichen. Das sichert den Monat.`},

/* ---------- Vorsorge & Todesfall ---------- */
{id:"sterbefall", n:"Sterbefall anzeigen", kat:"ende", typ:"frist",
 frist:`In der Regel spätestens am dritten Werktag nach dem Tod.`,
 wo:`Standesamt des Sterbeorts. Das Bestattungsunternehmen übernimmt das meist mit.`,
 mit:`Totenschein des Arztes, Personalausweis der verstorbenen Person, Geburts- und ggf. Eheurkunde, Ausweis der anzeigenden Person.`,
 kosten:`Die Beurkundung gering, jede Sterbeurkunde kostet extra.`,
 dauer:`Sterbeurkunde in wenigen Tagen.`,
 ablauf:`Arzt ruft und stellt den Totenschein aus, Bestatter beauftragen, Standesamt beurkundet, Sterbeurkunden abholen.`,
 achtung:`Ohne Sterbeurkunde geht danach nichts: Rentenversicherung, Banken, Versicherungen und Vermieter verlangen alle ein eigenes Exemplar.`,
 tipp:`Mindestens zehn Sterbeurkunden bestellen. Nachbestellen kostet wieder Gebühr und Zeit, und zwar in genau der Woche, in der niemand Zeit hat.`},

{id:"erbschein", n:"Erbschein beantragen", kat:"ende", typ:"jederzeit",
 wo:`Nachlassgericht beim Amtsgericht des letzten Wohnorts, oder über einen Notar.`,
 mit:`Sterbeurkunde, Testament falls vorhanden, Personenstandsurkunden, Angaben zum Nachlasswert.`,
 kosten:`Nach dem Nachlasswert gestaffelt — bei größeren Erbschaften schnell dreistellig und mehr.`,
 dauer:`Mehrere Wochen bis Monate.`,
 ablauf:`Erklärung an Eides statt abgeben, Unterlagen einreichen, Erbschein abwarten.`,
 achtung:`Oft gar nicht nötig: Ein notarielles Testament mit Eröffnungsprotokoll reicht vielen Banken. Erst fragen, dann beantragen — das spart häufig die gesamte Gebühr.`,
 tipp:`Vor dem Antrag bei allen Banken schriftlich nachfragen, was sie konkret verlangen. Die Antworten unterscheiden sich stärker als erwartet.`},

{id:"vorsorgevollmacht", n:"Vorsorgevollmacht hinterlegen", kat:"ende", typ:"jederzeit",
 wo:`Kein Amtsgang nötig, um sie zu errichten. Registrieren lässt sie sich im Zentralen Vorsorgeregister der Bundesnotarkammer; beglaubigen beim Notar oder bei der Betreuungsbehörde.`,
 mit:`Ausweis, die unterschriebene Vollmacht.`,
 kosten:`Registrierung eine kleine Gebühr, notarielle Beurkundung nach Vermögenswert.`,
 dauer:`Registrierung in Tagen.`,
 ablauf:`Vollmacht aufsetzen, unterschreiben, bei Bedarf beglaubigen lassen, im Register eintragen, Bevollmächtigte informieren.`,
 achtung:`Für Grundstücksgeschäfte und manche Bankvorgänge verlangen Gegenüber eine notariell beglaubigte Vollmacht. Eine handschriftliche reicht dann nicht.`,
 tipp:`Die beste Vollmacht nützt nichts, wenn niemand von ihr weiß. Zwei Vertrauenspersonen sagen, dass es sie gibt und wo sie liegt — und das Register erledigt den Rest.`}

];
