/* HeiBen — Sicher im Netz: Betrug erkennen, Daten schützen.
   Datenbasis für digital.html. Schema je Eintrag:
   {id,n,kat,typ:"masche"|"schutz",senior(opt true = mit Eltern/Großeltern besprechen),
    kurz:`Ein-Satz-Kern`,lage:`Worum es geht / wie die Masche läuft`,
    erkennen:`Warnzeichen`,schutz:[`3–5 Schritte`],notfall(opt):`Wenn es passiert ist`,tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten. */

window.DS_KAT={betrug:"Betrugsmaschen",konto:"Konto & Bezahlen",zugang:"Passwörter & Zugänge",geraete:"Geräte & Zuhause",daten:"Daten & Backup",familie:"Familie schützen"};
window.DS_TYP={masche:"Betrugsmasche",schutz:"Grundschutz"};

window.DIGITAL=[
/* -- Betrugsmaschen -- */
{id:"phishing",n:"Phishing-Mails erkennen",kat:"betrug",typ:"masche",senior:true,
 kurz:`Gefälschte Mails wollen dich auf falsche Login-Seiten locken.`,
 lage:`Eine Mail sieht aus wie von Bank, Paketdienst oder Streaming-Anbieter und drängt: „Konto gesperrt, jetzt bestätigen!“ Der Link führt auf eine nachgebaute Seite, die deine Zugangsdaten abgreift.`,
 erkennen:`Druck und Drohung („innerhalb von 24 Stunden“), unpersönliche Anrede, Absenderadresse mit seltsamer Domain, Link-Ziel passt nicht zum Absender (lange auf den Link tippen bzw. mit der Maus darüber schweben, ohne zu klicken).`,
 schutz:[
  `Grundregel: Niemals über Links aus Mails einloggen — Adresse immer selbst eintippen oder die App nutzen.`,
  `Absender prüfen: Die echte Domain steht direkt vor dem letzten Punkt (bank.de, nicht bank.de.irgendwas.com).`,
  `Bei Zweifel den Anbieter über die offizielle Website oder Hotline fragen — nie über Kontaktdaten aus der Mail.`,
  `Verdächtige Mails melden (Phishing-Meldeadresse des Anbieters, Verbraucherzentrale) und löschen.`],
 notfall:`Daten eingegeben? Sofort das Passwort ändern (und überall, wo es gleich lautet), Zwei-Faktor aktivieren, bei Bankdaten die Bank anrufen und Umsätze prüfen.`,
 tipp:`Echte Anbieter drohen nicht mit der Stoppuhr — Zeitdruck ist das sicherste Phishing-Signal überhaupt.`},
{id:"smishing",n:"Fake-SMS: „Ihr Paket wartet“",kat:"betrug",typ:"masche",senior:true,
 kurz:`Betrugs-SMS mit Link — meist getarnt als Paketdienst oder Bank.`,
 lage:`„Ihre Sendung konnte nicht zugestellt werden“ plus Link: Dahinter stecken Schadsoftware oder Abo-Fallen. Auch angebliche Banken-SMS („neues Sicherheitsverfahren“) gehören dazu.`,
 erkennen:`Du erwartest gar kein Paket, die Nummer ist ein normales Handy, der Link ist kryptisch verkürzt, es wird eine „Zollgebühr“ von wenigen Euro verlangt.`,
 schutz:[
  `Links in SMS von Unbekannten grundsätzlich nicht antippen.`,
  `Sendungsstatus nur in der offiziellen App oder mit der Sendungsnummer auf der echten Website prüfen.`,
  `Nummer blockieren und die SMS löschen; auf Android keine Apps aus SMS-Links installieren.`],
 notfall:`Link angetippt oder gar eine App installiert? Flugmodus an, App löschen, Virenscan, Passwörter vom sauberen Gerät ändern — und die Mobilfunkrechnung auf Drittanbieter-Abos prüfen (Drittanbietersperre einrichten).`,
 tipp:`Die Drittanbietersperre beim Mobilfunkanbieter ist kostenlos und stoppt Abo-Fallen, bevor sie Geld kosten.`},
{id:"whatsapptrick",n:"„Hallo Mama“ — der Messenger-Trick",kat:"betrug",typ:"masche",senior:true,
 kurz:`„Neue Nummer, Handy kaputt, brauche dringend Geld“ — das Kind ist ein Betrüger.`,
 lage:`Per WhatsApp meldet sich das angebliche Kind von einer fremden Nummer: Handy kaputt, deshalb neue Nummer — und gleich eine dringende Rechnung, die „nur heute“ überwiesen werden muss.`,
 erkennen:`Fremde Nummer plus Geldbitte, Anrufe werden abgeblockt („Mikrofon kaputt“), emotionaler Druck und Eile, Überweisung soll auf ein fremdes Konto gehen.`,
 schutz:[
  `Eiserne Regel: Bei Geldbitten IMMER auf der alten, bekannten Nummer anrufen — geht das Kind dort ran, ist alles klar.`,
  `Eine Kontrollfrage stellen, die nur die echte Person beantworten kann — oder ein Familien-Codewort vereinbaren.`,
  `Niemals unter Zeitdruck überweisen; kein seriöses Anliegen scheitert an einer Stunde Bedenkzeit.`],
 notfall:`Schon überwiesen? Sofort die eigene Bank anrufen (Rückruf der Überweisung versuchen — je schneller, desto besser) und Anzeige bei der Polizei erstatten.`,
 tipp:`Das Familien-Codewort kostet nichts, ist in einer Minute vereinbart — und macht diese Masche komplett wirkungslos.`},
{id:"schockanruf",n:"Schockanruf & Enkeltrick",kat:"betrug",typ:"masche",senior:true,
 kurz:`„Ihr Kind hatte einen Unfall“ — falsche Polizisten wollen Geld oder Schmuck abholen.`,
 lage:`Ein Anrufer — angeblich Polizei, Staatsanwalt oder weinendes Enkelkind — meldet einen schweren Unfall oder eine Verhaftung. Nur eine sofortige „Kaution“ könne helfen; ein Bote holt Geld und Wertsachen ab.`,
 erkennen:`Extremer emotionaler Druck, Geheimhaltung wird verlangt („mit niemandem sprechen!“), Geldübergabe an Fremde, angezeigte Nummer wirkt echt (auch 110 lässt sich fälschen).`,
 schutz:[
  `Auflegen — und die betroffene Person selbst unter ihrer bekannten Nummer anrufen.`,
  `Wissen verankern: Polizei und Staatsanwaltschaft fordern NIEMALS Geld am Telefon und holen NIEMALS Wertsachen ab. Es gibt keine „Kaution“ nach deutschem Recht.`,
  `Bei echtem Zweifel selbst die 110 wählen (neu wählen, nicht zurückrufen!) und nachfragen.`,
  `Niemals Fremden Geld, Schmuck oder Karten übergeben — egal, wie dringend es klingt.`],
 notfall:`Übergabe erfolgt oder vereinbart? Sofort 110 anrufen — die Polizei nimmt diese Fälle sehr ernst und kann Boten teils noch abfangen.`,
 tipp:`Ein Satz schützt die ganze Familie: „Die Polizei will nie dein Geld.“ Diesen Satz laut mit den Eltern und Großeltern durchsprechen.`},
{id:"fakeshop",n:"Fake-Shops entlarven",kat:"betrug",typ:"masche",
 kurz:`Traumpreis, Vorkasse, keine Ware — der Shop existiert nur zum Kassieren.`,
 lage:`Professionell aussehende Online-Shops locken mit dem begehrten Produkt zum Bestpreis. Bezahlt wird per Vorkasse — geliefert wird nie, und der Shop verschwindet.`,
 erkennen:`Preis deutlich unter allen anderen, am Ende bleibt nur Vorkasse/Überweisung übrig, Impressum fehlt oder ist wirr, Fantasie-Gütesiegel ohne Verlinkung, sehr junge Domain.`,
 schutz:[
  `Unbekannte Shops vor der Bestellung prüfen: Fakeshop-Finder der Verbraucherzentrale und eine kurze Suche nach „Shopname + Erfahrungen“.`,
  `Impressum kontrollieren: vollständige Anschrift, Vertretungsberechtigter, Handelsregister.`,
  `Nie per Vorkasse an Unbekannte zahlen — Rechnung, Lastschrift oder Zahlarten mit Käuferschutz wählen.`,
  `Gesundes Misstrauen: Der einzige Shop, der das ausverkaufte Produkt „auf Lager“ hat, ist verdächtig.`],
 notfall:`Bezahlt und nichts erhalten? Sofort die Bank kontaktieren (Überweisungsrückruf versuchen, Lastschrift zurückgeben), Beweise sichern (Screenshots, Mails) und Anzeige erstatten — das geht auch online.`,
 tipp:`Die Zahlart ist der Lackmustest: Wenn im letzten Schritt plötzlich nur noch Vorkasse geht — Kauf abbrechen.`},
{id:"kleinanzeigen",n:"Betrug beim Kleinanzeigen-Verkauf",kat:"betrug",typ:"masche",
 kurz:`Nicht nur Käufer werden betrogen — Verkäufer sind das Hauptziel.`,
 lage:`Ein „Käufer“ schickt einen Link zur angeblichen „Sicher bezahlen“-Funktion oder will per Kurier zahlen lassen. Der Link führt auf eine Phishing-Seite, die Kartendaten abfragt — statt Geld zu erhalten, wird abgebucht.`,
 erkennen:`Kommunikation soll sofort auf WhatsApp wechseln, Links zu „Zahlungsseiten“ im Chat, der Käufer will ohne Besichtigung sofort kaufen, gebrochenes Deutsch mit Textbausteinen.`,
 schutz:[
  `Nur die offiziellen Funktionen der Plattform nutzen — niemals Links anklicken, die dir zugeschickt werden.`,
  `Als Verkäufer musst du NIE Kartendaten eingeben, um Geld zu ERHALTEN — wer das verlangt, ist Betrüger.`,
  `Bei Übergabe vor Ort: Bargeld prüfen; bei Versand nur nach Zahlungseingang auf dem Konto (nicht nach Zahlungs-„Beleg“) verschicken.`,
  `PayPal-Falle kennen: „Freunde & Familie“ hat keinen Käuferschutz — für Fremde tabu.`],
 notfall:`Kartendaten eingegeben? Karte sofort über 116 116 sperren und die Bank informieren; Chatverläufe als Beweis sichern und Anzeige erstatten.`,
 tipp:`Merksatz für jeden Verkauf: Wer Geld BEKOMMT, gibt niemals Kartendaten ein. Ohne Ausnahme.`},
{id:"supportbetrug",n:"Falscher Microsoft-Support",kat:"betrug",typ:"masche",senior:true,
 kurz:`Anruf oder Warnfenster: „Ihr PC ist infiziert“ — und dann kommt die Fernwartung.`,
 lage:`Ein Anrufer gibt sich als Microsoft- oder Techniksupport aus, oder ein rotes Browser-Warnfenster mit Sirenenton behauptet einen Virenbefall samt „Hotline“. Ziel: Fernwartungszugriff auf den Rechner und Zahlungen für nutzlose „Reparaturen“.`,
 erkennen:`Microsoft ruft niemals unaufgefordert an. Warnfenster mit Telefonnummer und Dauerton sind immer Fake. Es wird Fernwartungssoftware (AnyDesk, TeamViewer) und Zahlung per Gutscheinkarte verlangt.`,
 schutz:[
  `Auflegen bzw. den Browser schließen (notfalls über den Task-Manager) — echte Warnungen haben keine Hotline.`,
  `Niemals Fremden Fernzugriff auf den Rechner geben.`,
  `Nie mit Gutscheinkarten (Google Play, Apple, Amazon) „Gebühren“ zahlen — das verlangt kein seriöses Unternehmen.`],
 notfall:`Fernzugriff gewährt? Sofort Internet trennen, Fernwartungssoftware deinstallieren, alle wichtigen Passwörter von einem anderen Gerät ändern, Bank informieren, Rechner gründlich prüfen (im Zweifel neu aufsetzen lassen).`,
 tipp:`Ein Satz entwaffnet die Masche: „Microsoft ruft nie an.“ Wer das weiß, legt nach drei Sekunden auf.`},
{id:"quishing",n:"QR-Code-Betrug (Quishing)",kat:"betrug",typ:"masche",senior:true,
 kurz:`Aufgeklebte QR-Codes an Parkautomat, Ladesäule oder in Briefen führen auf Betrugsseiten.`,
 lage:`Kriminelle überkleben echte QR-Codes an Parkautomaten und E-Ladesäulen oder verschicken Briefe „der Bank“ mit QR-Code. Wer scannt, landet auf einer täuschend echten Zahl- oder Loginseite.`,
 erkennen:`Der Code ist ein Aufkleber (Kante fühlbar!), die geöffnete Adresse passt nicht zum Anbieter, es werden sofort Kartendaten verlangt, Briefe mit QR-Code kommen unerwartet.`,
 schutz:[
  `Vor dem Scannen fühlen und schauen: Klebt da etwas über dem Original?`,
  `Nach dem Scannen IMMER erst die angezeigte Web-Adresse prüfen, bevor irgendetwas eingegeben wird.`,
  `Fürs Parken und Laden lieber die offizielle App des Anbieters nutzen als wechselnde Codes.`,
  `QR-Codes aus Briefen und Mails der „Bank“ ignorieren — Banking nur über App oder selbst eingetippte Adresse.`],
 notfall:`Daten eingegeben? Karte über 116 116 sperren, Bank anrufen, Umsätze prüfen, Anzeige erstatten.`,
 tipp:`Ein QR-Code ist nur ein Link in Verkleidung — behandle ihn genau so misstrauisch wie einen Link in einer fremden Mail.`},
{id:"lovescam",n:"Romance Scam: Liebe als Masche",kat:"betrug",typ:"masche",
 kurz:`Wochenlang Nähe aufbauen, dann die Notlage — und die Bitte um Geld.`,
 lage:`Über Dating-Portale oder soziale Netzwerke entsteht eine intensive Online-Beziehung — mit gestohlenen Fotos und erfundener Biografie (Arzt im Ausland, Soldat, Ingenieur auf Bohrinsel). Nach Wochen kommt die Notlage: Zoll, Krankenhaus, gesperrtes Konto. Treffen scheitern immer in letzter Minute.`,
 erkennen:`Sehr schnelle große Gefühle, Videoanrufe klappen nie richtig, die Lebensgeschichte ist dramatisch und fern, und früher oder später geht es um Geld, Gutscheine oder Paketannahmen.`,
 schutz:[
  `Grundsatz ohne Ausnahme: Niemals Geld an Menschen senden, die man nie persönlich getroffen hat.`,
  `Profilfotos per Bilder-Rückwärtssuche prüfen — gestohlene Bilder fliegen so sofort auf.`,
  `Keine intimen Fotos an Online-Bekanntschaften — sie werden zum Erpressungshebel.`,
  `Auch keine „Gefälligkeiten“: Pakete annehmen oder Geld weiterleiten macht dich zum Teil einer Geldwäsche.`],
 notfall:`Geld gesendet? Bank sofort informieren, allen weiteren Kontakt abbrechen (Betrüger versuchen Nachschläge!), Beweise sichern, Anzeige erstatten — und mit jemandem darüber sprechen: Scham ist der beste Schutz der Täter.`,
 tipp:`Die Bilder-Rückwärtssuche dauert eine Minute und beendet die meisten dieser „Beziehungen“ auf der Stelle.`},

/* -- Konto & Bezahlen -- */
{id:"kartesperren",n:"Karte weg? Die 116 116",kat:"konto",typ:"schutz",senior:true,
 kurz:`Eine Nummer für fast alle Karten: der zentrale Sperr-Notruf 116 116.`,
 lage:`Ob Geldbörse gestohlen, Karte im Automaten verschwunden oder Daten in falsche Hände geraten — jede Minute zählt. Der Sperr-Notruf 116 116 sperrt Girocard, Kreditkarten vieler Anbieter und mehr, rund um die Uhr.`,
 erkennen:`Sperren bei: Verlust oder Diebstahl, unbekannten Abbuchungen, versehentlicher Dateneingabe auf einer Betrugsseite, Karte vom Automaten einbehalten an einem manipuliert wirkenden Gerät.`,
 schutz:[
  `Jetzt sofort: 116 116 als Kontakt „Kartensperrung“ ins Handy speichern (aus dem Ausland: +49 116 116).`,
  `Im Verlustfall erst sperren, dann suchen — Entsperren ist bei vielen Banken einfach, Schaden rückgängig machen nicht.`,
  `Bei Diebstahl zusätzlich Anzeige erstatten und für die Girocard die KUNO-Sperrung (Lastschriftverfahren) bei der Polizei erwähnen.`,
  `Umsätze der Folgetage kontrollieren und Unbekanntes sofort der Bank melden.`],
 tipp:`Diese sechs Ziffern gehören in jedes Familien-Handy: 116 116 — auswendig oder als erster Kontakt unter „K“.`},
{id:"sicherbezahlen",n:"Sicher online bezahlen",kat:"konto",typ:"schutz",
 kurz:`Die Zahlart entscheidet, wer im Streitfall das Risiko trägt — du oder der Anbieter.`,
 lage:`Rechnung, Lastschrift, Kreditkarte, Käuferschutz-Dienste, Vorkasse: Jede Zahlart verteilt das Risiko anders. Wer das System kennt, kauft entspannt — auch bei unbekannten Shops.`,
 erkennen:`Handlungsbedarf, wenn du standardmäßig per Vorkasse zahlst, Kartendaten in vielen Shops gespeichert hast oder „Freunde & Familie“ für Käufe nutzt.`,
 schutz:[
  `Rangfolge merken: Rechnung und Lastschrift (rückholbar) vor Kreditkarte und Käuferschutz-Diensten — Vorkasse nur bei Händlern, denen du wirklich vertraust.`,
  `PayPal & Co.: Für Waren immer die Option MIT Käuferschutz — „Freunde & Familie“ ist für Fremde tabu.`,
  `Kartendaten nicht in jedem Shop speichern; als Gast bestellen, wo es geht.`,
  `Für Online-Zahlungen die Freigabe per Banking-App (starke Kundenauthentifizierung) aktiv nutzen — sie ist dein Türsteher.`],
 tipp:`Frag dich vor dem Kauf nur eines: „Bekomme ich mein Geld zurück, wenn nichts kommt?“ — die Antwort bestimmt die Zahlart.`},
{id:"bankphishing",n:"Phishing im Namen der Bank",kat:"konto",typ:"masche",senior:true,
 kurz:`Die Bank fragt nie nach PIN oder TAN — wer es tut, ist Betrüger.`,
 lage:`Anrufer „von der Bank“ warnen vor angeblichen Betrugsbuchungen und bitten, „zur Sicherheit“ eine TAN freizugeben oder Daten zu bestätigen. Genau diese Freigabe autorisiert in Wahrheit die Betrüger-Überweisung. Auch per Mail und SMS läuft die Masche.`,
 erkennen:`Anruf mit Zeitdruck und Fachjargon, es wird eine TAN/Photo-TAN-Freigabe „zum Stornieren“ verlangt, die angezeigte Nummer sieht echt aus (Rufnummern sind fälschbar).`,
 schutz:[
  `In Stein gemeißelt: Bank-Mitarbeiter fragen NIE nach PIN, Passwort oder TAN — am Telefon, per Mail, niemals.`,
  `Jede TAN-Freigabe in der App genau LESEN: Dort steht Betrag und Empfänger — freigeben heißt überweisen.`,
  `Bei Anrufen: auflegen und die Bank selbst über die Nummer auf der Karte zurückrufen.`,
  `Banking nur über die App oder selbst eingetippte Adresse — nie über Links.`],
 notfall:`TAN freigegeben oder Daten genannt? Sofort die Bank anrufen (24-h-Sperr-Hotline), Zugang sperren lassen, Überweisungsrückruf versuchen, Anzeige erstatten.`,
 tipp:`Die TAN ist kein „Sicherheitscode“, sondern deine Unterschrift — lies vor jeder Freigabe, was du da unterschreibst.`},
{id:"lastschrift",n:"Lastschrift zurückholen",kat:"konto",typ:"schutz",
 kurz:`Acht Wochen Rückholrecht — die unterschätzte Superkraft des Girokontos.`,
 lage:`Jede SEPA-Lastschrift kannst du acht Wochen lang ohne Angabe von Gründen zurückgeben — per Klick im Online-Banking. Bei Abbuchungen ganz ohne dein Mandat gilt sogar eine Frist von 13 Monaten.`,
 erkennen:`Unbekannte Firmennamen auf dem Auszug, doppelte Abbuchungen, gekündigte Abos, die weiter abbuchen, falsche Beträge.`,
 schutz:[
  `Umsätze regelmäßig durchsehen — einmal pro Woche zwei Minuten reichen.`,
  `Fragwürdige Lastschrift im Online-Banking direkt zurückgeben („Lastschrift zurückgeben“ beim Umsatz).`,
  `Wichtig: Berechtigte Forderungen trotzdem klären — die Rückgabe löst den Vertrag nicht, sie verschafft dir nur die Verhandlungsposition.`,
  `Bei komplett unbekannten Abbuchungen zusätzlich die Bank informieren (möglicher Kontodaten-Missbrauch).`],
 tipp:`Wer weiß, dass Lastschriften 8 Wochen rückholbar sind, zahlt entspannter per Lastschrift als per Vorkasse.`},
{id:"identitaet",n:"Identitätsdiebstahl — was jetzt",kat:"konto",typ:"schutz",
 kurz:`Jemand bestellt, mahnt und schließt Verträge in deinem Namen — so stoppst du es.`,
 lage:`Mit erbeuteten Daten (Name, Adresse, Geburtsdatum, Ausweiskopie) bestellen Betrüger auf Rechnung oder schließen Verträge ab. Du merkst es an Mahnungen und Inkassopost für Dinge, die du nie bestellt hast.`,
 erkennen:`Rechnungen und Mahnungen für fremde Bestellungen, Post von Inkassobüros, Login-Warnungen von Diensten, Pakete an deine Adresse, die du nicht bestellt hast.`,
 schutz:[
  `Ruhe bewahren und JEDE Forderung schriftlich bestreiten — nie „zur Sicherheit“ zahlen.`,
  `Anzeige bei der Polizei erstatten (auch online möglich) — das Aktenzeichen ist dein Schlüssel gegenüber Händlern und Inkasso.`,
  `Schufa und andere Auskunfteien informieren und eine kostenlose Selbstauskunft anfordern.`,
  `Betroffene Konten absichern: Passwörter ändern, Zwei-Faktor aktivieren, Datenleck-Check machen.`],
 tipp:`Niemals aus Angst eine fremde Rechnung zahlen — mit Anzeige und schriftlichem Widerspruch bist du rechtlich auf der sicheren Seite.`},

/* -- Passwörter & Zugänge -- */
{id:"passwoerter",n:"Starke Passwörter ohne Zettelchaos",kat:"zugang",typ:"schutz",
 kurz:`Lang schlägt kompliziert — und der Passwort-Manager merkt sich alles.`,
 lage:`Das größte Risiko ist nicht das „schwache“ Passwort, sondern das WIEDERVERWENDETE: Ein einziges Datenleck öffnet dann alle Konten. Die Lösung sind einzigartige, lange Passwörter — verwaltet von einem Passwort-Manager.`,
 erkennen:`Handlungsbedarf, wenn du dasselbe Passwort mehrfach nutzt, Passwörter im Browser-Klartext oder auf Zetteln sammelst oder deine Passwörter kürzer als 12 Zeichen sind.`,
 schutz:[
  `Länge vor Komplexität: Eine Passphrase aus vier zufälligen Wörtern („KorrektesPferdBatterieKlammer“) ist stark und merkbar.`,
  `Jedes Konto bekommt ein eigenes Passwort — ohne Ausnahme bei Mail, Bank und wichtigen Shops.`,
  `Einen Passwort-Manager einrichten: Er erzeugt und merkt sich alles, du merkst dir nur noch EIN starkes Master-Passwort.`,
  `Passwörter nur bei Verdacht wechseln — der regelmäßige Zwangswechsel ist überholt und produziert nur schwache Muster.`],
 tipp:`Das wichtigste Passwort deines Lebens gehört deinem E-Mail-Konto — wer deine Mails hat, kann fast alles andere zurücksetzen.`},
{id:"zweifaktor",n:"Zwei-Faktor: das Sicherheitsnetz",kat:"zugang",typ:"schutz",
 kurz:`Selbst mit geklautem Passwort kommt ohne zweiten Faktor niemand rein.`,
 lage:`Die Zwei-Faktor-Authentisierung (2FA) verlangt beim Login zusätzlich einen Code vom Handy oder eine Bestätigung in der App. Ein gestohlenes Passwort allein wird damit wertlos.`,
 erkennen:`Handlungsbedarf, wenn E-Mail-Konto, Banking, Passwort-Manager oder Social-Media-Konten noch ohne zweiten Faktor laufen.`,
 schutz:[
  `2FA zuerst dort aktivieren, wo es am meisten schützt: E-Mail, Bank, Passwort-Manager, Apple/Google-Konto.`,
  `Authenticator-App (oder Hardware-Schlüssel) bevorzugen — SMS-Codes sind besser als nichts, aber die schwächste Variante.`,
  `Die Backup-Codes beim Einrichten ausdrucken und zu den wichtigen Papieren legen — sie sind dein Ersatzschlüssel bei Handyverlust.`],
 tipp:`Zehn Minuten Einrichtung, jahrelanger Schutz — 2FA ist das beste Sicherheits-Preis-Leistungs-Verhältnis im ganzen Netz.`},
{id:"datenleck",n:"Bin ich in einem Datenleck?",kat:"zugang",typ:"schutz",
 kurz:`Ob deine Mail-Adresse samt Passwort im Umlauf ist, lässt sich seriös prüfen.`,
 lage:`Bei Einbrüchen in Online-Dienste landen Millionen Zugangsdaten im Netz. Seriöse Prüfdienste wie der HPI Identity Leak Checker (Hasso-Plattner-Institut) oder „Have I Been Pwned“ verraten, ob deine Adresse betroffen ist.`,
 erkennen:`Spam-Wellen an eine bestimmte Adresse, Login-Warnungen aus fremden Ländern, Freunde erhalten seltsame Mails „von dir“.`,
 schutz:[
  `Eigene Mail-Adressen bei einem seriösen Leak-Checker prüfen (HPI Identity Leak Checker, Have I Been Pwned) — nie bei dubiosen „Prüfseiten“, die selbst Daten sammeln.`,
  `Bei Treffern: Passwort des betroffenen Dienstes UND überall, wo es gleich lautete, sofort ändern.`,
  `Zwei-Faktor aktivieren — dann bleibt ein geleaktes Passwort ein stumpfes Schwert.`],
 tipp:`Einmal im Jahr fünf Minuten Leak-Check für die ganze Familie — am besten gleich zusammen mit dem Passwort-Aufräumen.`},
{id:"geraetesperre",n:"Handy & Laptop richtig sperren",kat:"zugang",typ:"schutz",
 kurz:`Das entsperrte Gerät ist der Generalschlüssel zu deinem Leben.`,
 lage:`Wer dein entsperrtes Handy hat, hat deine Mails, Fotos, Chats — und kann Passwörter zurücksetzen. Die Bildschirmsperre ist deshalb keine Komfortfrage, sondern die erste Verteidigungslinie.`,
 erkennen:`Handlungsbedarf bei: keiner oder trivialer PIN (1234, Geburtsjahr), Entsperr-Muster (leicht abzuschauen), Laptop ohne Passwort und ohne Verschlüsselung.`,
 schutz:[
  `Mindestens 6-stellige PIN oder Fingerabdruck/Gesicht — Biometrie ist im Alltag sicherer als eine abgeschaute Kurz-PIN.`,
  `Automatische Sperre auf kurze Zeit stellen (30–60 Sekunden).`,
  `Laptop: Anmeldepasswort plus Geräteverschlüsselung aktivieren (bei aktuellen Systemen oft nur ein Schalter).`,
  `Vorsicht mit der SIM-PIN: aktiv lassen — sonst telefoniert der Dieb mit deiner Nummer und empfängt deine SMS-Codes.`],
 tipp:`Teste dich selbst: Was könnte ein Fremder in fünf Minuten mit deinem entsperrten Handy anrichten? Genau davor schützt die Sperre.`},
{id:"wiederherstellung",n:"Konto-Wiederherstellung vorbereiten",kat:"zugang",typ:"schutz",
 kurz:`Der Ernstfall entscheidet sich daran, was du HEUTE hinterlegt hast.`,
 lage:`Handy kaputt, Passwort vergessen, Konto gehackt: Ob du wieder hineinkommst, hängt an Wiederherstellungs-Mail, Zweitnummer und Backup-Codes — alles Dinge, die man VORHER einrichtet.`,
 erkennen:`Handlungsbedarf, wenn bei wichtigen Konten noch die alte Mail-Adresse oder eine gekündigte Nummer hinterlegt ist — oder du die Backup-Codes nie gesichert hast.`,
 schutz:[
  `Bei E-Mail-, Apple/Google- und Bank-Konten die hinterlegten Wiederherstellungsdaten prüfen und aktualisieren.`,
  `Backup-Codes der 2FA ausdrucken und offline zu den wichtigen Papieren legen (Stichwort Notfallordner).`,
  `Eine zweite vertrauenswürdige Mail-Adresse als Rettungsanker pflegen.`],
 tipp:`Mach den Feuerwehr-Test: „Handy weg — komme ich morgen in mein Mail-Konto?“ Wenn die Antwort zögert, heute nachrüsten.`},

/* -- Geräte & Zuhause -- */
{id:"updates",n:"Updates: der unterschätzte Schutz",kat:"geraete",typ:"schutz",
 kurz:`Jedes verschobene Update ist ein offen gelassenes Fenster.`,
 lage:`Die meisten erfolgreichen Angriffe nutzen längst bekannte Sicherheitslücken — auf Geräten, deren Besitzer das Update „später“ machen wollten. Updates schließen genau diese Löcher.`,
 erkennen:`Handlungsbedarf bei: rotem Update-Zähler seit Wochen, Geräten ohne Hersteller-Support (altes Android, uraltes Windows), „Später erinnern“ als Dauerzustand.`,
 schutz:[
  `Automatische Updates überall aktivieren: Betriebssystem, Browser, Apps, Router.`,
  `Geräte, die keine Sicherheitsupdates mehr bekommen, nicht mehr für Banking und Mail nutzen.`,
  `Beim Gerätekauf auf zugesagte Update-Dauer achten — sie ist ein echtes Qualitätsmerkmal.`],
 tipp:`Der Dienstag-Trick: Ein fester Wochentag als „Update-Moment“ (Kaffee holen, Update läuft) macht aus der Störung eine Routine.`},
{id:"router",n:"Den Router absichern",kat:"geraete",typ:"schutz",
 kurz:`Der Router ist die Haustür deines digitalen Zuhauses.`,
 lage:`Über den Router läuft alles — entsprechend lohnt sich eine Viertelstunde Grundsicherung: Passwörter, Verschlüsselung, Gastnetz. Einmal richtig eingestellt, jahrelang Ruhe.`,
 erkennen:`Handlungsbedarf bei: WLAN-Passwort wie ab Werk seit Jahren, unbekannten Geräten in der Geräteliste, Router-Login noch mit Standardkennwort.`,
 schutz:[
  `Zwei Passwörter ändern: das WLAN-Passwort UND das Zugangspasswort zur Router-Oberfläche.`,
  `Verschlüsselung auf WPA2 oder WPA3 stellen; WPS-Taste dauerhaft deaktivieren.`,
  `Ein Gastnetz einrichten — für Besuch und für smarte Geräte, getrennt vom eigenen Netz.`,
  `Automatische Router-Updates aktivieren und einmal im Jahr die Geräteliste durchsehen.`],
 tipp:`Das Gastnetz ist der unterschätzte Held: Besucher-Handys und Billig-Gadgets kommen ins Gästezimmer, nicht ins Wohnzimmer deines Netzwerks.`},
{id:"oeffwlan",n:"Öffentliches WLAN nutzen",kat:"geraete",typ:"schutz",
 kurz:`Café-WLAN ist okay — wenn du weißt, was dort nichts verloren hat.`,
 lage:`Dank verschlüsselter Verbindungen (https) ist offenes WLAN heute weniger gefährlich als sein Ruf. Riskant bleiben gefälschte Hotspots mit vertrauten Namen und sensible Logins auf fremder Infrastruktur.`,
 erkennen:`Warnzeichen: mehrere Netze mit fast gleichem Namen, Anmeldeportale, die Passwörter oder Kartendaten verlangen, Zertifikatswarnungen des Browsers.`,
 schutz:[
  `Faustregel: Surfen und Nachschlagen ja — Banking und wichtige Logins lieber über die Mobilfunkverbindung (Hotspot).`,
  `Auf das Schloss-Symbol/https achten und Zertifikatswarnungen ernst nehmen: dann abbrechen.`,
  `„Automatisch verbinden“ für offene Netze deaktivieren — sonst wählt sich das Handy ungefragt in Fake-Hotspots ein.`,
  `Wer viel unterwegs arbeitet: ein seriöses VPN als Zusatzschicht.`],
 tipp:`Im Zweifel ist dein eigener Handy-Hotspot das sicherste WLAN im ganzen Café.`},
{id:"smartgeraete",n:"Smarte Geräte zu Hause",kat:"geraete",typ:"schutz",
 kurz:`Kamera, Sprachassistent, smarte Steckdose — praktisch, aber mit Grundregeln.`,
 lage:`Jedes vernetzte Gerät ist ein kleiner Computer im Haus. Billige Geräte ohne Updates und mit Standardpasswörtern sind beliebte Einfallstore — besonders heikel bei Kameras.`,
 erkennen:`Warnzeichen: Gerät verlangt nie ein Passwort, der Hersteller ist ein No-Name ohne Update-Historie, die Kamera ist aus dem Internet ohne Anmeldung erreichbar.`,
 schutz:[
  `Bei jedem Gerät zuerst: Standardpasswort ändern und Updates aktivieren.`,
  `Smarte Geräte ins Gastnetz des Routers hängen — getrennt von Laptop und Handy.`,
  `Kameras nie auf Schlaf- und Kinderzimmer richten; Mikrofon-/Kamera-Abschaltung nutzen, wenn vorhanden.`,
  `Lieber wenige Geräte von Herstellern mit Update-Versprechen als viele Schnäppchen ohne Support.`],
 tipp:`Vor dem Kauf eine Frage an den Hersteller-Support-Bereich: „Wie lange gibt es Updates?“ Keine Antwort ist auch eine Antwort.`},
{id:"handyverloren",n:"Handy verloren oder geklaut",kat:"geraete",typ:"schutz",
 kurz:`Die ersten 30 Minuten entscheiden — wenn Ortung und Sperre vorbereitet sind.`,
 lage:`Ein verlorenes Handy ist doppelter Verlust: das Gerät und der Zugang zu Konten, Fotos und Codes. „Mein iPhone suchen“ bzw. „Mein Gerät finden“ (Android) machen daraus einen beherrschbaren Zwischenfall — wenn sie AKTIVIERT sind.`,
 erkennen:`Vorbereitungs-Check: Ist die Ortung aktiviert? Kennst du die Zugangsdaten zum Apple/Google-Konto auch ohne das Handy? Ist die IMEI-Nummer notiert (steht auf der Verpackung)?`,
 schutz:[
  `HEUTE: Ortungsdienst aktivieren und einmal von einem anderen Gerät testen.`,
  `Im Verlustfall sofort: orten, aus der Ferne sperren, Nachricht mit Kontaktnummer anzeigen lassen — bei Diebstahl: Daten fernlöschen.`,
  `SIM-Karte beim Mobilfunkanbieter sperren lassen (sonst empfängt der Dieb deine SMS-Codes).`,
  `Passwörter der wichtigsten Konten ändern; bei Diebstahl Anzeige mit IMEI-Nummer erstatten.`],
 notfall:`Reihenfolge im Ernstfall: 1) Orten & sperren über den Ortungsdienst, 2) SIM sperren beim Anbieter, 3) Mail-/Bank-Passwörter ändern, 4) Anzeige mit IMEI.`,
 tipp:`Schreib dir die IMEI (Tastenfeld: *#06#) heute zu den wichtigen Papieren — nach dem Diebstahl zeigt sie dir niemand mehr an.`},

/* -- Daten & Backup -- */
{id:"backup",n:"Backups: die 3-2-1-Regel",kat:"daten",typ:"schutz",
 kurz:`Drei Kopien, zwei Medien, eine außer Haus — mehr Formel braucht es nicht.`,
 lage:`Fotos, Dokumente, Steuerunterlagen: Ohne Backup genügt ein Sturz, ein Diebstahl oder ein Verschlüsselungstrojaner, und alles ist weg. Die 3-2-1-Regel macht Datenverlust praktisch unmöglich.`,
 erkennen:`Handlungsbedarf, wenn Familienfotos nur auf dem Handy existieren, die einzige Sicherung eine dauerhaft angesteckte Festplatte ist oder das letzte Backup „irgendwann letztes Jahr“ lief.`,
 schutz:[
  `3-2-1 umsetzen: 3 Kopien deiner Daten, auf 2 verschiedenen Medien, davon 1 außer Haus (Cloud oder Platte bei Vertrauensperson).`,
  `Backups automatisieren — Handy-Cloudsicherung plus regelmäßige Kopie auf eine externe Platte.`,
  `Die externe Platte nach dem Backup ABSTECKEN: Nur ein getrenntes Backup übersteht Verschlüsselungstrojaner.`,
  `Einmal im Jahr die Probe: eine Datei testweise wiederherstellen.`],
 tipp:`Ein Backup, das du nie wiederhergestellt hast, ist nur eine Hoffnung — der jährliche Fünf-Minuten-Test macht daraus Gewissheit.`},
{id:"datensparsam",n:"Datensparsamkeit im Alltag",kat:"daten",typ:"schutz",
 kurz:`Was du nicht preisgibst, kann niemand leaken, verkaufen oder missbrauchen.`,
 lage:`Jedes Formularfeld, jedes Gewinnspiel, jede App-Berechtigung sammelt Puzzleteile deiner Identität. Datensparsamkeit ist der leiseste, aber wirksamste Schutz — vor Werbung, Leaks und Identitätsdiebstahl.`,
 erkennen:`Handlungsbedarf, wenn du überall dein echtes Geburtsdatum angibst, jede App alle Berechtigungen bekommt und deine Haupt-Mail-Adresse in jedem Shop steckt.`,
 schutz:[
  `Nur Pflichtfelder ausfüllen — freiwillige Angaben (Telefon, Geburtsdatum) konsequent leer lassen.`,
  `Eine Zweit-Mail-Adresse für Shops und Newsletter nutzen; die Haupt-Adresse bleibt für Wichtiges sauber.`,
  `App-Berechtigungen prüfen: Braucht die Taschenlampe wirklich deinen Standort und die Kontakte?`,
  `Bei Gewinnspielen und „Gratis“-Angeboten daran denken: Bezahlt wird dort mit deinen Daten.`],
 tipp:`Die Zweit-Mail ist der einfachste Datenschutz-Trick überhaupt — und sie zeigt dir sofort, wer deine Adresse weiterverkauft hat.`},
{id:"socialprivat",n:"Privatsphäre in sozialen Medien",kat:"daten",typ:"schutz",
 kurz:`Poste so, dass du es auch einem freundlichen Fremden erzählen würdest.`,
 lage:`Öffentliche Profile verraten Wohnort, Tagesroutine, Urlaubszeiten und Familienstruktur — nützlich für Werbetreibende, Einbrecher und Betrüger, die daraus glaubwürdige Maschen bauen (Stichwort Schockanruf mit echten Namen).`,
 erkennen:`Handlungsbedarf, wenn deine Beiträge „öffentlich“ stehen, Urlaubsfotos live vom Strand kommen oder Fremde deine Freundesliste und dein Geburtsdatum sehen können.`,
 schutz:[
  `Privatsphäre-Check in jedem Netzwerk: Beiträge auf „Freunde“, Freundesliste und Geburtstag verbergen.`,
  `Urlaubsfotos erst NACH der Rückkehr posten — das leere Zuhause muss niemand live mitverfolgen.`,
  `Standort-Funktionen in Kamera und Apps deaktivieren; Kinderfotos besonders zurückhaltend teilen.`,
  `Freundschaftsanfragen von Unbekannten und Doppel-Profilen echter Freunde ignorieren und melden.`],
 tipp:`Betrüger lesen mit: Je weniger dein Profil über Familie und Alltag verrät, desto stumpfer werden ihre Maschen.`},
{id:"spam",n:"Spam & unerwünschte Mails",kat:"daten",typ:"schutz",
 kurz:`Der wichtigste Klick bei Spam ist: gar keiner.`,
 lage:`Spam ist lästig, aber vor allem ein Testballon: Jede Reaktion — sogar der Klick auf „Abbestellen“ — bestätigt den Absendern, dass deine Adresse aktiv gelesen wird, und macht sie wertvoller.`,
 erkennen:`Typisch: reißerische Betreffzeilen, Gewinnversprechen, angebliche Rechnungen im Anhang, Absender, bei denen du nie Kunde warst.`,
 schutz:[
  `In echtem Spam NIE auf „Abbestellen“ klicken und keine Bilder nachladen — beides bestätigt deine Adresse. Einfach als Spam markieren.`,
  `Der Spam-Filter lernt: Konsequentes Markieren macht ihn von Woche zu Woche besser.`,
  `Anhänge von Unbekannten (Rechnung.zip, Mahnung.pdf.exe) niemals öffnen.`,
  `Seriöse Newsletter, die du wirklich mal bestellt hast, darfst du dagegen ganz normal abbestellen.`],
 tipp:`Unterscheide zwei Welten: Beim bestellten Newsletter ist „Abbestellen“ dein Recht — beim echten Spam ist es die Falle.`},

/* -- Familie schützen -- */
{id:"kinder",n:"Kinder sicher im Netz",kat:"familie",typ:"schutz",
 kurz:`Begleiten schlägt verbieten — und Reden schlägt jede Filter-App.`,
 lage:`Kinder wachsen ins Netz hinein wie in den Straßenverkehr: mit Übung, Regeln und einem Erwachsenen an der Seite. Technische Schutzmaßnahmen helfen — ersetzen aber nie das Gespräch.`,
 erkennen:`Gesprächsbedarf, wenn das Kind heimlich nutzt, plötzlich Chats verbirgt, Kontakt mit Unbekannten hat oder Inhalte sieht, die es sichtbar beschäftigen.`,
 schutz:[
  `Altersfreigaben und kindgerechte Profile/Apps nutzen (Familienfunktionen von Google/Apple, YouTube Kids statt YouTube).`,
  `Gemeinsame Regeln vereinbaren: Zeiten, Orte (Geräte nicht im Kinderzimmer über Nacht), was gepostet werden darf.`,
  `Die wichtigste Botschaft verankern: „Du kannst IMMER zu uns kommen, egal was du angeklickt hast“ — ohne Angst vor Strafe erzählen Kinder Probleme früh.`,
  `Interesse zeigen: mitspielen, erklären lassen — wer die Welt des Kindes kennt, erkennt Veränderungen sofort.`],
 tipp:`Der beste Jugendschutzfilter ist ein Kind, das weiß: Wenn etwas komisch ist, erzähle ich es zu Hause — und niemand schimpft.`},
{id:"senioren",n:"Eltern & Großeltern schützen",kat:"familie",typ:"schutz",senior:true,
 kurz:`Drei Sätze und ein Codewort schützen besser als jede Software.`,
 lage:`Telefonbetrüger zielen gezielt auf ältere Menschen — mit Schockanruf, falscher Bankmitarbeiterin und Gewinnversprechen. Der wirksamste Schutz ist Vorbereitung im Familienkreis: Wer die Masche kennt, legt auf.`,
 erkennen:`Warnzeichen bei Angehörigen: plötzliche Geldsorgen oder Abhebungen, Geheimniskrämerei nach Anrufen, neue „Freunde“ oder „Berater“ am Telefon, Gutscheinkarten-Käufe.`,
 schutz:[
  `Die drei Schutzsätze gemeinsam durchsprechen: „Die Polizei will nie dein Geld.“ — „Die Bank fragt nie nach PIN oder TAN.“ — „Bei Geldbitten rufe ich auf der alten Nummer zurück.“`,
  `Ein Familien-Codewort für echte Notfälle vereinbaren.`,
  `Die 116 116 und die eigene Nummer groß neben das Telefon der Eltern legen.`,
  `Eine offene Kultur pflegen: Über Betrugsversuche wird ohne Scham gesprochen — jeder Fall macht die ganze Familie schlauer.`],
 tipp:`Mach aus dem Thema ein Sonntagsgespräch, nicht eine Belehrung: „Stell dir vor, was bei Nachbarn passiert ist …“ öffnet Ohren besser als jeder Vortrag.`},
{id:"inapp",n:"In-App-Käufe & Abofallen im Store",kat:"familie",typ:"schutz",
 kurz:`„Gratis“-Spiele verdienen ihr Geld im Spiel — Schutz ist eine Einstellung.`,
 lage:`Kostenlose Apps locken mit Käufen im Spiel und Probe-Abos, die sich still verlängern. Besonders teuer wird es, wenn Kinder auf dem Familien-Tablet freie Bahn haben und die Karte hinterlegt ist.`,
 erkennen:`Warnzeichen: App-Store-Abbuchungen auf dem Kontoauszug, „3 Tage gratis testen“-Banner, Kind fragt nach dem Passwort „nur ganz kurz“.`,
 schutz:[
  `Jeden Kauf mit Passwort oder Fingerabdruck bestätigen lassen — die Einstellung „für jeden Kauf erforderlich“ aktivieren.`,
  `Familienfreigabe einrichten: Kinderkäufe müssen erst von den Eltern genehmigt werden.`,
  `Laufende Abos regelmäßig im Store-Konto prüfen (dort werden sie auch gekündigt — nicht durch Löschen der App!).`,
  `Probe-Abos direkt nach Abschluss kündigen — der Testzeitraum läuft trotzdem bis zum Ende.`],
 notfall:`Kind hat versehentlich gekauft? Im Store-Konto eine Erstattung anfragen — bei offensichtlichen Kinderkäufen sind Apple und Google oft kulant, wenn es zeitnah gemeldet wird.`,
 tipp:`Eine App zu löschen kündigt KEIN Abo — gekündigt wird immer im Store-Konto unter „Abos“.`},
{id:"nachlass",n:"Digitaler Nachlass",kat:"familie",typ:"schutz",
 kurz:`Konten, Fotos, Abos: Auch das digitale Leben braucht eine Regelung.`,
 lage:`Im Ernstfall stehen Angehörige vor verschlossenen Konten: Mail, Cloud-Fotos, Abos, die weiterlaufen. Wer zu Lebzeiten zehn Minuten investiert, erspart der Familie Monate — das digitale Gegenstück zum Notfallordner.`,
 erkennen:`Handlungsbedarf, wenn niemand außer dir weiß, welche Konten existieren, wo der Passwort-Manager liegt und wie man an die Familienfotos in der Cloud käme.`,
 schutz:[
  `Nachlass-Funktionen der großen Anbieter einrichten: Google „Kontoinaktivität-Manager“, Apple „Nachlasskontakt“, Facebook „Nachlasskontakt“.`,
  `Eine Kontenliste (Dienst + Benutzername, OHNE Passwörter) in den Notfallordner legen — plus den Hinweis, wo der Zugang zum Passwort-Manager geregelt ist.`,
  `Im Passwort-Manager die Notfallzugriffs-Funktion für eine Vertrauensperson aktivieren, falls vorhanden.`,
  `In Vollmacht bzw. Testament einen Satz zum digitalen Nachlass ergänzen (wer darf Konten verwalten und löschen).`],
 tipp:`Der Notfallordner aus dem Papierkram-Kompendium bekommt eine Seite „Digital“ — damit ist die Lücke zwischen Aktenordner und Cloud geschlossen.`}
];
