/* HeiBen — Erste Hilfe im Haushalt: ruhig & richtig handeln.
   Datenbasis für erstehilfe.html. Schema je Eintrag:
   {id,n,kat,typ:"akut"|"vorsorge",kind(opt true = Kind-Besonderheit),
    kurz:`Ein-Satz-Kern`,sofort:[`3–6 Schritte`],nicht:`Bloß nicht (klassische Fehler)`,
    notruf(bei akut Pflicht):`Wann 112 / Arzt / Giftnotruf`,kindbes(opt):`Bei Kindern`,tipp}
   Inhaltlich strikt am etablierten Erste-Hilfe-Kanon (DRK/Leitlinien-Niveau), bewusst ohne
   Medikamenten-Dosierungen. Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil. */

window.EH_KAT={notfall:"Lebensbedrohliche Notfälle",wunden:"Wunden & Blutungen",hitze:"Hitze, Kälte & Strom",gift:"Vergiftung & Allergie",alltag:"Stürze & Alltagsverletzungen",vorsorge:"Vorbeugen & Familie"};
window.EH_TYP={akut:"Akut handeln",vorsorge:"Vorbereitet sein"};

window.ERSTEHILFE=[
/* -- Lebensbedrohliche Notfälle -- */
{id:"notruf112",n:"Der Notruf 112 — richtig alarmieren",kat:"notfall",typ:"akut",kind:true,
 kurz:`Eine Nummer, europaweit, kostenlos — und die Leitstelle führt dich durch alles Weitere.`,
 sofort:[
  `112 wählen — kostenlos von jedem Telefon und Handy, europaweit.`,
  `Zuerst das Wichtigste: WO ist es passiert (Adresse, Stockwerk, Besonderheiten der Zufahrt).`,
  `Dann: WAS ist passiert und WIE VIELE Betroffene.`,
  `Fragen der Leitstelle beantworten und NICHT auflegen, bis die Leitstelle das Gespräch beendet — sie gibt dir Anweisungen.`,
  `Wenn möglich: Tür öffnen, Licht an, jemanden zum Einweisen an die Straße stellen.`],
 nicht:`Aus Angst „zu stören“ nicht anrufen — die 112 ist genau dafür da. Und nicht auflegen, bevor die Leitstelle fertig ist.`,
 notruf:`112 bei jedem möglichen Notfall für Leben und Gesundheit. Der ärztliche Bereitschaftsdienst 116 117 ist für Beschwerden, die bis zur Praxisöffnung warten könnten — im Zweifel immer 112.`,
 kindbes:`Kindern früh die 112 beibringen und üben: eigenen Namen und die Wohnadresse laut aufsagen können.`,
 tipp:`Die eigene Adresse gut sichtbar an den Kühlschrank — für Kinder, Babysitter und für dich selbst, wenn im Stress der Kopf leer ist.`},
{id:"bewusstlos",n:"Bewusstlos — aber Atmung vorhanden",kat:"notfall",typ:"akut",
 kurz:`Wer bewusstlos ist und atmet, gehört in die stabile Seitenlage — sofort.`,
 sofort:[
  `Laut ansprechen und vorsichtig an den Schultern rütteln: „Hallo, hören Sie mich?“`,
  `Keine Reaktion: Atmung prüfen — Kopf leicht in den Nacken neigen, maximal 10 Sekunden sehen, hören, fühlen.`,
  `Atmung vorhanden: in die stabile Seitenlage drehen — der Mund wird zum tiefsten Punkt, damit die Atemwege frei bleiben.`,
  `112 rufen (oder rufen lassen), zudecken und die Atmung fortlaufend kontrollieren.`],
 nicht:`Nichts einflößen, nicht schütteln, nicht allein lassen — und die Atemkontrolle nicht vergessen: Setzt die Atmung aus, sofort mit der Herzdruckmassage beginnen.`,
 notruf:`Bewusstlosigkeit ist immer ein Fall für die 112 — auch wenn die Person zwischendurch wieder wach wirkt.`,
 tipp:`Merksatz für die Seitenlage: überstreckter Kopf, geöffneter Mund, Mund zeigt zum Boden — die genaue Grifffolge frischt der nächste Kurs auf.`},
{id:"reanimation",n:"Keine Atmung: Drücken rettet",kat:"notfall",typ:"akut",kind:true,
 kurz:`Prüfen — rufen — drücken: 100 bis 120 Mal pro Minute, fest und ohne Pause.`,
 sofort:[
  `Keine (normale) Atmung? Sofort 112 — laut um Hilfe rufen und, falls vorhanden, einen Defibrillator (AED) holen lassen.`,
  `Person auf harten Untergrund, Handballen auf die Mitte des Brustkorbs, zweite Hand darüber.`,
  `Fest und schnell drücken: 5–6 cm tief, 100–120 Mal pro Minute — das Tempo von „Stayin’ Alive“.`,
  `Nicht aufhören, bis der Rettungsdienst übernimmt; wenn ein Helfer da ist, alle 1–2 Minuten abwechseln.`,
  `AED einschalten, sobald er da ist — das Gerät sagt dir jeden Schritt an.`],
 nicht:`Der einzige Fehler ist, NICHTS zu tun. Dass dabei Rippen brechen können, ist bekannt und in Ordnung — ohne Drücken hat das Herz keine Chance.`,
 notruf:`112 kommt immer zuerst — die Leitstelle leitet dich am Telefon durch die Herzdruckmassage.`,
 kindbes:`Bei Kindern nach Möglichkeit zuerst 5 Beatmungen, dann drücken (etwa ein Drittel der Brustkorbtiefe; beim Säugling mit zwei Fingern).`,
 tipp:`Trau dich: Laien-Reanimation verdoppelt bis verdreifacht die Überlebenschance — und die Leitstelle spricht dir jeden Schritt vor.`},
{id:"verschlucken",n:"Verschluckt — Erstickungsgefahr",kat:"notfall",typ:"akut",kind:true,
 kurz:`Solange gehustet wird: husten lassen. Danach: 5 Rückenschläge, 5 Oberbauchstöße.`,
 sofort:[
  `Kräftiges Husten ist das Beste — dazu auffordern und nicht dazwischenfunken.`,
  `Husten wird wirkungslos: Oberkörper nach vorn beugen, 5 kräftige Schläge mit dem Handballen zwischen die Schulterblätter.`,
  `Hilft das nicht: 5 Oberbauchstöße (Heimlich-Griff) — Faust oberhalb des Nabels, ruckartig nach hinten-oben ziehen.`,
  `Im Wechsel 5 Schläge / 5 Stöße; dabei 112 alarmieren (lassen).`,
  `Wird die Person bewusstlos: ablegen und mit der Herzdruckmassage beginnen.`],
 nicht:`Nicht auf den Rücken klopfen, solange kräftig gehustet wird; nicht blind mit den Fingern in den Rachen; Kinder nicht kopfüber schütteln.`,
 notruf:`112 spätestens, sobald Rückenschläge nötig werden — und nach jedem angewendeten Heimlich-Griff ärztlich untersuchen lassen (innere Verletzungen möglich).`,
 kindbes:`Säuglinge bäuchlings auf den Unterarm legen (Kopf tief), 5 Rückenschläge — statt Oberbauchstößen 5 Brustkompressionen.`,
 tipp:`Vorbeugen ist die halbe Erste Hilfe: Nüsse, Weintrauben und Bonbons sind für Kleinkinder Hochrisiko — Trauben immer längs halbieren.`},
{id:"starkeblutung",n:"Starke Blutung stoppen",kat:"notfall",typ:"akut",
 kurz:`Druck, Druck, Druck — direkter Druck auf die Wunde stoppt fast jede Blutung.`,
 sofort:[
  `112 rufen (lassen) und Einmalhandschuhe anziehen, wenn greifbar.`,
  `Person hinlegen, betroffenes Körperteil hochhalten.`,
  `Mit steriler Auflage oder sauberem Tuch direkt und kräftig auf die Wunde drücken.`,
  `Druckverband anlegen: Wundauflage, festes Polster darüber, straff umwickeln.`,
  `Blutet es durch: zweites Polster obendrauf und weiter drücken — nicht abwickeln.`],
 nicht:`Eingedrungene Gegenstände (Messer, Glas) NIE herausziehen — sie stopfen die Wunde; stattdessen umpolstern und fixieren. Abbinden ist die absolute Ausnahme für Extremfälle.`,
 notruf:`112 bei spritzender, anhaltender oder großflächiger Blutung, bei Blässe, Kaltschweiß oder Benommenheit (Schockzeichen).`,
 tipp:`Wenn kein Material da ist: einfach mit der Hand fest draufbleiben, bis Hilfe kommt — dein Druck ist der Verband.`},
{id:"krampfanfall",n:"Krampfanfall",kat:"notfall",typ:"akut",
 kurz:`Schützen statt festhalten — und auf die Uhr schauen.`,
 sofort:[
  `Ruhe bewahren; harte und spitze Gegenstände aus der Umgebung räumen.`,
  `Kopf weich polstern (Jacke, Kissen) — die Person selbst NICHT festhalten.`,
  `Auf die Uhr sehen: Wie lange dauert der Anfall?`,
  `Nach dem Anfall: Atmung prüfen, stabile Seitenlage, dableiben und beruhigen — Verwirrtheit danach ist normal.`],
 nicht:`Niemals etwas zwischen die Zähne schieben (der „Löffel“ ist ein gefährlicher Mythos) und keine Bewegungen gewaltsam unterdrücken.`,
 notruf:`112 beim ersten Anfall überhaupt, bei Dauer über 5 Minuten, bei Verletzung, bei Anfallserien oder wenn die Person nicht zu Bewusstsein kommt.`,
 tipp:`Wenn eine zweite Person da ist: ein kurzes Handyvideo hilft Ärzten später enorm bei der Einordnung.`},

/* -- Wunden & Blutungen -- */
{id:"schnittwunde",n:"Schnittwunde versorgen",kat:"wunden",typ:"akut",
 kurz:`Erst Druck und Ruhe — dann entscheidet die Tiefe, ob es Pflaster oder Praxis wird.`,
 sofort:[
  `Hinsetzen (Kreislauf!), Wunde mit sauberer Auflage komprimieren, Hand hochhalten.`,
  `Kleine Schnitte: kurz unter Trinkwasser spülen, Wundddesinfektion, Pflaster oder Wundschnellverband.`,
  `Klaffende oder tiefe Schnitte: nur keimfrei abdecken und zum Arzt — Kleben oder Nähen gelingt am besten innerhalb weniger Stunden.`,
  `Tetanus-Impfschutz gedanklich prüfen — im Zweifel beim Arzt ansprechen.`],
 nicht:`Kein Mehl, kein Puder, keine Hausmittel in frische Wunden; klaffende Wunden nicht selbst „zusammenkleben“.`,
 notruf:`112 bei starker, nicht stillbarer Blutung. Arztpraxis bei klaffenden, tiefen oder verschmutzten Wunden, bei Taubheitsgefühl oder wenn sich Finger nicht mehr normal bewegen lassen (Sehnen!).`,
 tipp:`Der Küchenmesser-Klassiker: erst zwei Minuten fest drücken, DANN erst nachsehen — sonst blutet jede Beurteilung davon.`},
{id:"schuerfwunde",n:"Schürfwunde reinigen",kat:"wunden",typ:"akut",kind:true,
 kurz:`Sauber machen ist hier die eigentliche Behandlung.`,
 sofort:[
  `Wunde mit reichlich Trinkwasser oder Wundspüllösung ausspülen, groben Schmutz herauslösen.`,
  `Wunddesinfektionsmittel auftragen.`,
  `Mit nicht verklebender Auflage oder Pflaster abdecken — moderne feuchte Wundheilung heilt schöner als „Luft und Kruste“.`,
  `Verband täglich und bei Durchnässung wechseln.`],
 nicht:`Nicht auf die Wunde pusten (Keime!), Kruste nicht abknibbeln, tief eingeriebenen Schmutz nicht ignorieren.`,
 notruf:`Zum Arzt bei tief eingeriebenem Schmutz („Asphalt-Tattoo“ droht), bei Bisswunden, bei Rötung, Pochen oder Eiter in den Folgetagen — und wenn der Tetanusschutz unklar ist.`,
 kindbes:`Bei Kindern lieber einmal mehr spülen und mit einem guten Pflaster „belohnen“ — Drama vermeiden hilft beim nächsten Mal.`,
 tipp:`Eine kleine Flasche Wundspüllösung im Wanderrucksack ersetzt unterwegs das fehlende Waschbecken.`},
{id:"nasenbluten",n:"Nasenbluten stillen",kat:"wunden",typ:"akut",kind:true,
 kurz:`Kopf nach VORN — nicht in den Nacken — und zehn Minuten zudrücken.`,
 sofort:[
  `Aufrecht hinsetzen, Kopf leicht nach vorn beugen.`,
  `Nasenflügel mit Daumen und Zeigefinger fest zusammendrücken — volle 10 Minuten, auf die Uhr schauen.`,
  `Kaltes, feuchtes Tuch in den Nacken legen.`,
  `Danach einige Stunden nicht schnäuzen und nicht bohren.`],
 nicht:`Kopf NICHT in den Nacken (Blut läuft in den Magen — Übelkeit) und keine Watte tief in die Nase stopfen.`,
 notruf:`Ärztliche Hilfe, wenn es nach 20 Minuten Druck weiterblutet, nach einem Sturz oder Schlag auf den Kopf, oder bei Blutverdünner-Einnahme.`,
 kindbes:`Kinder beim Drücken ablenken (Video, Geschichte) — die 10 Minuten sind für kleine Patienten lang.`,
 tipp:`Der häufigste Fehler ist Ungeduld: Wer alle zwei Minuten nachschaut, startet die Blutungs-Uhr jedes Mal neu.`},
{id:"splitter",n:"Splitter entfernen",kat:"wunden",typ:"akut",
 kurz:`Flach sitzende Splitter zieht die Pinzette — tiefe gehören dem Arzt.`,
 sofort:[
  `Pinzette desinfizieren, Haut um den Splitter reinigen.`,
  `Splitter im Eintrittswinkel fassen und in gleicher Richtung herausziehen.`,
  `Stelle desinfizieren und mit Pflaster abdecken.`,
  `Winzige, oberflächliche Splitter: Klebeband aufdrücken und abziehen.`],
 nicht:`Nicht mit der Nadel „graben“ und nicht quetschen — das treibt Splitter tiefer und Keime hinein.`,
 notruf:`Zum Arzt bei Glassplittern, Splittern unter dem Nagel, sehr tiefen Splittern — und wenn die Stelle in den Folgetagen rot, dick oder pochend wird.`,
 tipp:`Nach dem Heimwerken mit Glas: Boden mit einer Taschenlampe flach ausleuchten — Splitter blitzen auf, bevor sie im Fuß landen.`},
{id:"zahnaus",n:"Zahn ausgeschlagen",kat:"wunden",typ:"akut",kind:true,
 kurz:`Der Zahn lebt — wenn er feucht bleibt und du schnell bist.`,
 sofort:[
  `Zahn NUR an der Krone anfassen, nie an der Wurzel.`,
  `Nicht säubern, nicht abrubbeln — Schmutz bleibt dran.`,
  `Feucht lagern: ideal Zahnrettungsbox (Apotheke), sonst kalte H-Milch; notfalls in einem Becher mit Speichel.`,
  `Sofort zum Zahnarzt oder in die Zahnklinik — jede Minute zählt für die Wiedereinpflanzung.`],
 nicht:`Nicht trocken transportieren, nicht in Wasser legen, nicht selbst zurückdrücken.`,
 notruf:`Immer sofort zahnärztlich vorstellen; bei Sturz mit Bewusstlosigkeit oder Erbrechen zusätzlich an den Kopf denken → 112/Arzt.`,
 kindbes:`Ausgeschlagene Milchzähne werden nicht wieder eingesetzt — trotzdem zum Zahnarzt: Der bleibende Zahnkeim darunter muss kontrolliert werden.`,
 tipp:`Eine Zahnrettungsbox in Sport- und Schultasche hält Zahnzellen bis zu 24 Stunden am Leben — das beste Sportzubehör für wenige Euro.`},

/* -- Hitze, Kälte & Strom -- */
{id:"verbrennung",n:"Verbrennung & Verbrühung",kat:"hitze",typ:"akut",kind:true,
 kurz:`Handwarmes Wasser, keine Hausmittel — und bei großen Flächen sofort die 112.`,
 sofort:[
  `Hitzequelle beseitigen; bei Verbrühung heiß durchtränkte Kleidung sofort ausziehen (nur wenn sie nicht mit der Haut verklebt ist).`,
  `Kleinflächige Verbrennungen: 10–20 Minuten unter handwarmem (nicht eiskaltem) Leitungswasser kühlen — das nimmt den Schmerz.`,
  `Danach keimfrei und locker abdecken (metallbeschichtetes Brandwundtuch oder sauberes Tuch).`,
  `Blasen geschlossen lassen; Schmuck in der Nähe der Stelle früh abnehmen (Schwellung).`],
 nicht:`Kein Eis, kein Mehl, keine Butter, keine Zahnpasta — Hausmittel verschlimmern. Große Flächen NICHT kühlen (Unterkühlungsgefahr), keine Blasen aufstechen, verklebte Kleidung nicht abreißen.`,
 notruf:`112 bei großflächigen Verbrennungen, bei Gesicht oder Atemwegen, bei Stromverbrennungen und bei Säuglingen/Kleinkindern im Zweifel immer. Arzt bei allen Blasen, die größer als eine Münze sind.`,
 kindbes:`Kinderhaut verbrennt schon bei Temperaturen, die Erwachsene nur als heiß empfinden — und Kinder kühlen beim Kühlen rasch aus: nur kurz, nur kleinflächig, im Zweifel 112.`,
 tipp:`Der gefährlichste Ort der Küche ist die Tischkante mit der Teetasse — heiße Getränke nie in Reichweite kleiner Hände abstellen.`},
{id:"sonnenstich",n:"Sonnenstich & Hitzschlag",kat:"hitze",typ:"akut",kind:true,
 kurz:`Roter, heißer Kopf nach Sonne: raus aus der Hitze — und Warnzeichen kennen.`,
 sofort:[
  `Sofort in Schatten oder kühlen Raum; hinlegen mit leicht erhöhtem Kopf und Oberkörper.`,
  `Kühle, feuchte Tücher auf Kopf und Nacken.`,
  `Wenn klar und ansprechbar: schluckweise Wasser trinken lassen.`,
  `Beobachten — Verschlechterung ist ein Alarmzeichen.`],
 nicht:`Nicht allein lassen, nicht eiskalt abduschen, nicht „weiter durchhalten“ lassen.`,
 notruf:`112 bei Bewusstseinsstörungen, Erbrechen, Nackensteifigkeit oder Hitzschlag-Zeichen: heiße, oft trockene Haut, Verwirrtheit, Taumeln — dann zusätzlich aktiv kühlen, das ist ein Notfall.`,
 kindbes:`Babys und Kleinkinder überhitzen schnell: nie im Auto lassen (auch nicht „nur kurz“), Kopf und Nacken immer bedecken.`,
 tipp:`Der Unterschied in einem Satz: Sonnenstich = heißer Kopf, Hitzschlag = heißer ganzer Körper plus Verwirrtheit — Zweiteres ist immer die 112.`},
{id:"unterkuehlung",n:"Unterkühlung & Erfrierung",kat:"hitze",typ:"akut",
 kurz:`Zittern ist ein gutes Zeichen — gefährlich wird es, wenn es aufhört.`,
 sofort:[
  `Aus Wind und Nässe holen, nasse Kleidung ausziehen, in Decken wickeln (auch den Kopf).`,
  `Wach und zitternd: warme, gezuckerte Getränke geben.`,
  `Langsam aufwärmen — warmer Raum, Körperkontakt, Decken.`,
  `Erfrorene Stellen (weiß, gefühllos): locker keimfrei abdecken, körperwarm aufwärmen lassen.`],
 nicht:`Kein Alkohol, kein heißes Bad, kein Rubbeln oder Massieren erfrorener Stellen (auch nicht mit Schnee — ein gefährlicher Mythos).`,
 notruf:`112, wenn das Zittern aufhört, die Person schläfrig oder verwirrt wird — schwer Unterkühlte so wenig wie möglich bewegen.`,
 tipp:`Bei Kindern nach dem Schlittentag Hände und Füße kontrollieren — Kinder melden Erfrierungen oft nicht, weil das Spielen wichtiger ist.`},
{id:"stromunfall",n:"Stromunfall",kat:"hitze",typ:"akut",
 kurz:`Erst der Strom, dann der Mensch — sonst gibt es zwei Verletzte.`,
 sofort:[
  `ZUERST Stromkreis unterbrechen: Stecker ziehen, Sicherung raus — die Person vorher nicht berühren.`,
  `Geht das nicht: mit nicht leitendem Gegenstand (Holz, Kunststoff) trennen, selbst isoliert stehen.`,
  `Dann Bewusstsein und Atmung prüfen; wenn nötig Seitenlage oder Herzdruckmassage.`,
  `Strommarken (Brandwunden) keimfrei abdecken.`],
 nicht:`Bei Hochspannung (Bahnanlagen, Freileitungen, geöffnete Verteilerkästen) NICHT nähern — mehrere Meter Abstand, nur 112.`,
 notruf:`Nach jedem nennenswerten Stromunfall 112 bzw. ärztliche Abklärung mit EKG — Herzrhythmusstörungen können noch Stunden später auftreten, auch wenn sich alles gut anfühlt.`,
 tipp:`Die Reihenfolge als Merksatz ins Familiengedächtnis: „Strom weg — dann Mensch.“`},

/* -- Vergiftung & Allergie -- */
{id:"vergiftung",n:"Vergiftung — der Giftnotruf",kat:"gift",typ:"akut",kind:true,
 kurz:`Ruhe, Reste sichern, Giftnotruf anrufen — und niemals Erbrechen auslösen.`,
 sofort:[
  `Ruhe bewahren und klären: WAS wurde WANN und in WELCHER Menge genommen? Verpackung, Pflanzenteile oder Reste sichern.`,
  `Giftnotrufzentrale anrufen (regionale Nummer — heute einspeichern!) und die Fragen beantworten.`,
  `Nur tun, was der Giftnotruf anweist — je nach Stoff sind die Maßnahmen völlig unterschiedlich.`,
  `Bei Bewusstseinsstörung oder Atemproblemen sofort 112; Bewusstlose in die stabile Seitenlage.`],
 nicht:`NIEMALS Erbrechen auslösen und keine Milch als „Gegengift“ geben — beides kann alles schlimmer machen. Nichts einflößen ohne Anweisung des Giftnotrufs.`,
 notruf:`Giftnotruf, solange die Person wach und stabil ist; 112 bei Bewusstseins- oder Atemproblemen. Beide Nummern gehören ins Handy.`,
 kindbes:`Der Standardfall ist das Kleinkind mit Putzmittel, Medikamenten oder Beeren — deshalb: Giftnotruf-Nummer JETZT einspeichern, nicht erst im Ernstfall suchen.`,
 tipp:`Suche einmal „Giftnotruf“ plus dein Bundesland, speichere die Nummer als Kontakt — dieser eine Handgriff macht dich im Ernstfall doppelt so schnell.`},
{id:"veraetzung",n:"Verätzung an Haut & Auge",kat:"gift",typ:"akut",
 kurz:`Spülen, spülen, spülen — Wasser ist hier das Medikament.`,
 sofort:[
  `Eigenschutz: Handschuhe an, getränkte Kleidung mit Abstand entfernen.`,
  `Haut: mindestens 10 Minuten unter fließendem Wasser spülen.`,
  `Auge: sofort und 10–15 Minuten spülen — Kopf zur Seite, vom inneren zum äußeren Augenwinkel, Lid dabei offen halten.`,
  `Immer ärztlich (beim Auge: augenärztlich) vorstellen und die Produktverpackung mitnehmen.`],
 nicht:`Nicht „neutralisieren“ (Säure gegen Lauge erzeugt Hitze), nicht reiben, keine Salben vor der ärztlichen Beurteilung.`,
 notruf:`112 bei großflächigen Verätzungen, starken Schmerzen am Auge oder wenn Ätzendes geschluckt wurde (dann zusätzlich Giftnotruf; nichts einflößen ohne Anweisung).`,
 tipp:`Rohrreiniger und Entkalker sind die Haushalts-Klassiker — die Schutzbrille aus dem Baumarkt ist die billigste Augenversicherung.`},
{id:"insektenstich",n:"Wespen- & Bienenstich",kat:"gift",typ:"akut",kind:true,
 kurz:`Meist harmlos — außer im Mund oder bei Allergie.`,
 sofort:[
  `Bienenstachel mit dem Fingernagel oder einer Karte seitlich wegkratzen — nicht mit den Fingern quetschen (Giftblase!).`,
  `Stichstelle kühlen; ein Wärmestift (Stichheiler) direkt nach dem Stich lindert oft zusätzlich.`,
  `Stich in Mund oder Rachen: sofort 112 — währenddessen Eis lutschen und den Hals von außen kühlen.`,
  `In der ersten Stunde auf Allergiezeichen achten: Quaddeln am ganzen Körper, Schwellung im Gesicht, Atemnot.`],
 nicht:`Nicht aufkratzen, nicht aussaugen — und Panik hilft niemandem, auch dem gestochenen Kind nicht.`,
 notruf:`112 bei Stichen in Mund/Rachen, bei Atemnot, Kreislaufproblemen, Schwellungen fern der Stichstelle oder sehr vielen Stichen gleichzeitig.`,
 kindbes:`Draußen Getränke abdecken und mit Strohhalm trinken lassen — der Wespenstich im Mund passiert fast immer über die Limoflasche.`,
 tipp:`Ruhig bleiben und nicht fuchteln — Wespen stechen zur Verteidigung, nicht aus Bosheit.`},
{id:"anaphylaxie",n:"Allergischer Schock (Anaphylaxie)",kat:"gift",typ:"akut",
 kurz:`Ganzkörperreaktion nach Stich, Essen oder Medikament — hier zählt jede Minute.`,
 sofort:[
  `Alarmzeichen erkennen: Quaddeln am ganzen Körper, Schwellung von Gesicht oder Hals, Atemnot, Schwindel, Kreislaufkollaps — sofort 112.`,
  `Hat die Person einen Adrenalin-Autoinjektor: anwenden (außen in den Oberschenkel, notfalls durch die Kleidung) — im Zweifel lieber geben als zögern.`,
  `Lagerung: bei Atemnot sitzend, bei Kreislaufproblemen flach mit erhöhten Beinen.`,
  `Bei Bewusstlosigkeit: Seitenlage; ohne Atmung: Herzdruckmassage.`],
 nicht:`Nicht abwarten, „ob es von allein besser wird“ — Anaphylaxie kann in Minuten lebensbedrohlich werden.`,
 notruf:`Immer 112 — auch wenn der Autoinjektor gewirkt hat: Die Reaktion kann in einer zweiten Welle zurückkommen.`,
 tipp:`Allergiker in der Familie? Alle müssen wissen, WO das Notfallset liegt und WIE der Injektor geht — einmal gemeinsam am Übungs-Pen probieren.`},

/* -- Stürze & Alltagsverletzungen -- */
{id:"pech",n:"Umgeknickt & geprellt: die PECH-Regel",kat:"alltag",typ:"akut",
 kurz:`Pause, Eis, Compression, Hochlagern — die ersten 20 Minuten entscheiden über die nächsten zwei Wochen.`,
 sofort:[
  `P — Pause: sofort aufhören, nicht „auslaufen“ oder weiterspielen.`,
  `E — Eis: 15–20 Minuten kühlen, immer mit Tuch zwischen Haut und Kühlpack.`,
  `C — Compression: elastische Binde anlegen, spürbar, aber nicht abschnürend.`,
  `H — Hochlagern: über Herzhöhe, auch in den Stunden danach.`],
 nicht:`Keine Wärme, keine Massage und kein Alkohol in den ersten 48 Stunden — alles drei verstärkt die Einblutung.`,
 notruf:`Zum Arzt bei Fehlstellung, bei Unfähigkeit aufzutreten, bei sofort massiver Schwellung oder wenn es nach Tagen nicht besser wird — ein Bruch versteckt sich gern hinter einer „Verstauchung“.`,
 tipp:`Die Kühlkompresse gehört in den Kühlschrank, nicht ins Gefrierfach — eiskalt direkt aus dem Froster schadet der Haut.`},
{id:"kopfsturz",n:"Sturz auf den Kopf",kat:"alltag",typ:"akut",kind:true,
 kurz:`Die Beule außen ist selten das Problem — das Verhalten in den nächsten 48 Stunden zählt.`,
 sofort:[
  `Hinsetzen oder hinlegen, Beule mit umwickeltem Kühlpack kühlen.`,
  `Die nächsten 24–48 Stunden beobachten — anfangs auch nachts einmal prüfen, ob die Person gut weckbar ist.`,
  `Warnzeichen kennen: wiederholtes Erbrechen, zunehmende Kopfschmerzen, ungewöhnliche Schläfrigkeit oder Wesensveränderung, Erinnerungslücken, ungleich große Pupillen.`,
  `Bei jedem Warnzeichen: sofort ärztliche Hilfe.`],
 nicht:`Nach einem heftigen Sturz nicht allein lassen; Schlafen ist erlaubt (der „Wachhalte-Zwang“ ist ein Mythos) — aber weckbar muss die Person sein.`,
 notruf:`112 bei Bewusstlosigkeit (auch kurzer), Krampfanfall oder den genannten Warnzeichen. Säuglinge nach jedem Sturz auf den Kopf ärztlich vorstellen.`,
 kindbes:`Wickeltisch und Sofakante sind die Klassiker — Babys fallen lautlos und schneller, als man „kurz mal“ sagen kann: immer eine Hand am Kind.`,
 tipp:`Notiere dir die Sturzzeit — Ärzte fragen immer danach, und im Stress verschwimmen Stunden.`},
{id:"knochenbruch",n:"Verdacht auf Knochenbruch",kat:"alltag",typ:"akut",
 kurz:`Ruhigstellen heißt: so lassen, wie es ist — und bequem stützen.`,
 sofort:[
  `Betroffenes Körperteil nicht bewegen und nicht belasten lassen.`,
  `In der vorgefundenen Stellung mit Kissen, Decken oder Kleidung abstützen.`,
  `Geschlossenen Bruch vorsichtig kühlen (Tuch dazwischen).`,
  `Offener Bruch: Wunde nur keimfrei abdecken — nichts hineindrücken, nichts richten.`],
 nicht:`Niemals einrenken oder „mal testen, ob es geht“ — und improvisierte Schienen fest verzurren ist Profisache, nicht Erste Hilfe.`,
 notruf:`112 bei offenen Brüchen, Verdacht auf Oberschenkel-, Becken- oder Wirbelsäulenverletzung (dann gar nicht bewegen!) und starken Schmerzen — sonst zügig ärztliche Versorgung.`,
 tipp:`Schmuck und Uhren früh von der verletzten Seite nehmen — wenn die Schwellung kommt, geht der Ring nicht mehr ab.`},
{id:"auge",n:"Fremdkörper im Auge",kat:"alltag",typ:"akut",
 kurz:`Nicht reiben — spülen. Und alles, was eingedrungen ist, gehört dem Augenarzt.`,
 sofort:[
  `Nicht reiben lassen — das kratzt die Hornhaut.`,
  `Loses (Staubkorn, Wimper): Auge mit klarem Wasser vom inneren zum äußeren Winkel ausspülen oder das Oberlid kurz über das Unterlid ziehen.`,
  `Sichtbares, lose aufliegendes Teilchen mit dem sauberen Zipfel eines Tuchs zur Nase hin auswischen.`,
  `Festsitzende oder eingedrungene Fremdkörper: Auge nur locker abdecken und sofort zum Augenarzt.`],
 nicht:`Niemals mit Pinzette oder spitzen Gegenständen am Auge hantieren, festsitzende Teile nicht herausziehen.`,
 notruf:`Sofort Augenarzt oder Klinik nach Arbeiten mit Flex, Hammer oder Bohrer (Metallsplitter fliegen unsichtbar schnell) sowie bei Schmerzen mit Sehverschlechterung.`,
 tipp:`Die Schutzbrille beim Flexen, Bohren und Hecke schneiden — der Klassiker unter den vermeidbaren Augen-Notfällen.`},
{id:"zecke",n:"Zeckenstich",kat:"alltag",typ:"akut",kind:true,
 kurz:`Zügig, gerade, hautnah — und danach vier Wochen die Stelle im Blick behalten.`,
 sofort:[
  `Zecke mit feiner Pinzette oder Zeckenkarte HAUTNAH fassen.`,
  `Langsam und gerade herausziehen — nicht ruckeln, den Körper nicht quetschen.`,
  `Stichstelle desinfizieren, Datum notieren (Handyfoto).`,
  `Stelle 4–6 Wochen beobachten.`],
 nicht:`Kein Öl, kein Kleber, kein Nagellack — die Zecke „erbricht“ dann in die Wunde. Bleibt ein Rest des Stechapparats stecken, ist das meist harmlos und wächst heraus.`,
 notruf:`Zum Arzt bei einer sich ausbreitenden ringförmigen Rötung (Wanderröte), bei Fieber oder Grippegefühl in den Wochen danach — und zur Beratung über die FSME-Impfung in Risikogebieten.`,
 kindbes:`Nach jedem Wald- und Wiesentag Kinder absuchen: Haaransatz, hinter den Ohren, Achseln, Kniekehlen, Leisten.`,
 tipp:`Die Zeckenkarte im Portemonnaie wiegt nichts — und macht dich überall zum vorbereiteten Zecken-Entferner.`},
{id:"blase",n:"Blasen an den Füßen",kat:"alltag",typ:"akut",
 kurz:`Die Haut ist der beste Verband — sie bleibt drauf.`,
 sofort:[
  `Kleine, geschlossene Blase: in Ruhe lassen und mit Blasenpflaster polstern.`,
  `Prall und schmerzhaft: mit desinfizierter Nadel am Rand anstechen, Flüssigkeit sanft herausdrücken.`,
  `Die Blasenhaut UNBEDINGT darauf lassen — sie schützt wie ein natürliches Pflaster.`,
  `Desinfizieren, Blasenpflaster darüber, Reibungsquelle beheben (Socken, Schuhe).`],
 nicht:`Blasenhaut nicht abschneiden und offene Blasen nicht „auslüften“ — beides lädt Keime ein.`,
 notruf:`Diabetiker gehen mit Blasen und Wunden am Fuß grundsätzlich zum Arzt; sonst bei Rötung, Pochen oder Eiter.`,
 tipp:`Vor der langen Wanderung bekannte Reibestellen vorsorglich tapen — die beste Blase ist die, die nie entsteht.`},

/* -- Vorbeugen & Familie -- */
{id:"fieber",n:"Fieber & Fieberkrampf bei Kindern",kat:"vorsorge",typ:"akut",kind:true,
 kurz:`Das Verhalten des Kindes zählt mehr als die Zahl auf dem Thermometer.`,
 sofort:[
  `Fieber messen, viel trinken lassen, leicht anziehen und zudecken nach Wohlgefühl.`,
  `Auf das Kind schauen: Trinkt es, lässt es sich trösten, hat es wache Phasen? Das zählt mehr als Zehntelgrade.`,
  `Fiebersenkende Mittel nur altersgerecht nach Packungsbeilage bzw. ärztlicher Empfehlung — für Kinder gilt: niemals ASS (Acetylsalicylsäure).`,
  `FIEBERKRAMPF: Ruhe bewahren, Kind sicher auf den Boden/weiche Unterlage, nichts in den Mund, Zeit stoppen — danach immer ärztlich vorstellen.`],
 nicht:`Keine Wadenwickel bei kalten Beinen oder Schüttelfrost; schlafende Kinder nicht zum Messen wecken; ASS ist für Kinder tabu.`,
 notruf:`112 beim ersten Fieberkrampf, bei Krämpfen über 5 Minuten oder Atemproblemen. Sofort ärztlich: Säuglinge unter 3 Monaten mit Fieber, Kinder mit Nackensteife, Hautausschlag aus punktförmigen Einblutungen, Teilnahmslosigkeit oder Trinkverweigerung.`,
 kindbes:`Der Fieberkrampf sieht dramatisch aus, ist aber bei Kleinkindern meist harmlos — das Wissen darum ist der beste Schutz vor Panik.`,
 tipp:`Merke dir zwei Fragen statt der Kommastelle: „Trinkt mein Kind?“ und „Ist es zwischendurch es selbst?“ — zweimal Ja beruhigt zu Recht.`},
{id:"hausapotheke",n:"Die Hausapotheke",kat:"vorsorge",typ:"vorsorge",
 kurz:`Nicht viel — aber das Richtige, auffindbar und nicht abgelaufen.`,
 sofort:[
  `Grundausstattung: sterile Kompressen, Mullbinden, Pflaster in Größen, Dreiecktuch, Verbandschere, Splitterpinzette, Zeckenkarte, Einmalhandschuhe, Fieberthermometer, Wunddesinfektion, Kühlkompresse (die liegt im Kühlschrank).`,
  `Persönliche Medikamente nach ärztlicher Absprache ergänzen — mit Beipackzetteln.`,
  `Kühl, trocken und kindersicher lagern — das feuchte Bad ist der schlechteste Ort.`,
  `Einmal im Jahr Verfallsdaten prüfen und nachkaufen; Altmedikamente über Restmüll bzw. Rücknahmestellen entsorgen, nie über die Toilette.`],
 nicht:`Keine Sammelkiste voller angebrochener Uralt-Medikamente — was keiner mehr zuordnen kann, fliegt raus.`,
 tipp:`Der „Hausapotheken-TÜV“ zweimal im Jahr beim Uhrenumstellen — im selben Termin wie die Rauchmelder-Batterien.`},
{id:"kindersicher",n:"Haushalt kindersicher machen",kat:"vorsorge",typ:"vorsorge",kind:true,
 kurz:`Die beste Erste Hilfe ist die, die nie gebraucht wird.`,
 sofort:[
  `Putzmittel und Medikamente hoch und abschließbar lagern — und NIE in Getränkeflaschen umfüllen (der Klassiker vor jedem Giftnotruf).`,
  `Küche entschärfen: Topfgriffe nach hinten, Herdschutzgitter, heiße Getränke nie an Tischkante oder über dem Kind.`,
  `Kleinteile-Test: Alles, was durch eine Klopapierrolle passt, ist verschluckbar — weg damit aus Kinderreichweite (Knopfzellen sind Hochrisiko!).`,
  `Steckdosensicherungen, Treppengitter, kippsichere Möbel (Regale an die Wand dübeln), Fenster und Balkon sichern — keine Aufstiegshilfen davor.`],
 nicht:`„Nur ganz kurz“ ist die gefährlichste Formel im Haushalt — am Wickeltisch, in der Badewanne, am offenen Fenster.`,
 notruf:`Wenn doch etwas passiert: Giftnotruf bzw. 112 — beide Nummern hängen idealerweise sichtbar am Kühlschrank.`,
 kindbes:`Verschluckte Knopfzellen sind ein Notfall: sofort in die Klinik, nicht abwarten.`,
 tipp:`Einmal auf Knien durch die Wohnung krabbeln — aus Kinderperspektive siehst du jede Gefahr, die im Stehen unsichtbar ist.`},
{id:"notfalldaten",n:"Notfall-Infos in Handy & Geldbeutel",kat:"vorsorge",typ:"vorsorge",
 kurz:`Rettungskräfte schauen auf deinen Sperrbildschirm — dort sollten Antworten stehen.`,
 sofort:[
  `Notfallpass im Smartphone ausfüllen (iOS „Notfallpass“, Android „Notfallinformationen“): Vorerkrankungen, Allergien, Medikamente, Notfallkontakt — vom Sperrbildschirm abrufbar.`,
  `Notfallkontakte („ICE“) anlegen, die auch bei gesperrtem Handy anrufbar sind.`,
  `Wichtige Nummern einspeichern: 112, 116 117, Giftnotruf, Kartensperrung 116 116.`,
  `Für Angehörige mit Medikamenten: aktuelle Medikationsliste in den Notfallordner (siehe Papierkram-Kompendium).`],
 nicht:`Die eine Person, die alles weiß, ist kein Plan — Informationen gehören dorthin, wo Fremde sie finden.`,
 tipp:`Fünf Minuten am Handy heute können später die entscheidenden Minuten in der Notaufnahme sparen.`},
{id:"ehkurs",n:"Erste-Hilfe-Kurs auffrischen",kat:"vorsorge",typ:"vorsorge",
 kurz:`Der Führerschein-Kurs ist Jahrzehnte her — Handgriffe verfallen wie Verbandpäckchen.`,
 sofort:[
  `Alle 2–3 Jahre einen Auffrischungskurs machen — ein Samstag bei DRK, Johannitern, Maltesern oder ASB genügt.`,
  `Für Eltern und Großeltern: den speziellen Kurs „Erste Hilfe am Kind“ — andere Griffe, andere Notfälle.`,
  `Im Job nachfragen: Betriebshelfer-Kurse übernimmt oft der Arbeitgeber bzw. die Unfallkasse.`,
  `Nach dem Kurs die Familie mitnehmen: Wo liegt die Hausapotheke, wo der Verbandkasten, was sind unsere Notfallnummern?`],
 nicht:`Sich auf „das kriege ich im Ernstfall schon hin“ verlassen — unter Stress kann man nur, was die Hände schon einmal gemacht haben.`,
 tipp:`Ein Samstag alle drei Jahre ist die beste Versicherung, die man nicht kaufen kann — verschenke einen Kurs-Gutschein zum nächsten Familiengeburtstag.`}
];
