/* HeiBen — Finanz-Grundwissen & Eigentum: Geld verstehen, Wohnen entscheiden.
   Datenbasis für finanzen.html. Schema je Eintrag:
   {id,n,kat,typ:"basis"|"planen"|"schutz",kurz:`Ein-Satz-Kern`,lage:`Worum es geht`,
    punkte:[`3–6 Punkte`],fehler:`Häufiger Fehler`,merk(opt):`Faustregel/Merkzahl`,
    warn(opt):`Vorsicht`,tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten.
   Bewusst allgemein & konservativ; Steuerzahlen mit „aktuell/rund“ und Prüf-Hinweis. */

window.FG_KAT={konto:"Konto & Budget",sparen:"Sparen & Notgroschen",steuern:"Steuern",vorsorge:"Vorsorge & Versichern",invest:"Investieren — Grundlagen",wohnen:"Eigentum & Wohnen"};
window.FG_TYP={basis:"Grundlagen",planen:"Planen & Entscheiden",schutz:"Fallen & Schutz"};

window.FINANZEN=[
/* -- Konto & Budget -- */
{id:"girokonto",n:"Das Girokonto",kat:"konto",typ:"basis",
 kurz:`Das Drehkreuz deines Geldlebens — und jeder hat ein Recht darauf.`,
 lage:`Über das Girokonto laufen Gehalt, Miete und Alltag. In Deutschland hat jeder Anspruch auf ein „Basiskonto“ — auch ohne festes Einkommen oder Wohnung.`,
 punkte:[
  `Kostenfrei vs. Gebühren: Viele Banken verlangen Monatsgebühren — vergleichen lohnt, oft gibt es kostenlose Konten (teils an Bedingungen geknüpft).`,
  `Auf versteckte Kosten achten: Gebühren für Karte, Bargeldabheben an fremden Automaten, Buchungsposten.`,
  `Kontowechsel ist einfach: Banken müssen beim Wechsel per Gesetz helfen (Kontowechselservice).`,
  `Umsätze regelmäßig prüfen (siehe Kompendium „Sicher im Netz“: Lastschriften sind 8 Wochen rückholbar).`],
 fehler:`Jahrelang Kontogebühren zahlen, ohne je zu vergleichen — der Wechsel ist heute unkompliziert.`,
 tipp:`Einmal im Jahr die Kontokosten und die Konditionen prüfen — kostenlose Konten gibt es weiter, man muss sie nur suchen.`},
{id:"dispo",n:"Dispokredit & Überziehung",kat:"konto",typ:"schutz",
 kurz:`Der teuerste legale Kredit im Alltag — bequem, aber ein Schuldenmagnet.`,
 lage:`Der Dispo erlaubt, das Konto ins Minus zu ziehen. Die Bequemlichkeit hat einen hohen Preis: zweistellige Zinssätze sind üblich, für die Überziehung darüber hinaus noch mehr.`,
 punkte:[
  `Dispozins ist meist deutlich höher als jeder Ratenkredit — er ist Notnagel, kein Dauerzustand.`,
  `Wer dauerhaft im Dispo steckt, sollte ihn in einen günstigeren Ratenkredit umschulden.`,
  `Den Dispo-Rahmen bewusst niedrig halten — er verleitet zum „unsichtbaren“ Schuldenmachen.`,
  `Ziel: eine Rücklage (Notgroschen), die den Dispo überflüssig macht.`],
 fehler:`Den Dispo als „verlängertes Konto“ nutzen — die hohen Zinsen fressen jeden Monat stillschweigend mit.`,
 warn:`Dauerhaft im Dispo ist ein Warnsignal. Schuldnerberatungsstellen (kostenlos, bei Caritas, Diakonie, Verbraucherzentrale) helfen früh und ohne Scham.`,
 tipp:`Dispo abbauen zuerst: Kein Sparplan bringt so viel „Rendite“ wie das Loswerden eines zweistelligen Dispozinses.`},
{id:"haushaltsbuch",n:"Budget & die 50-30-20-Regel",kat:"konto",typ:"planen",
 kurz:`Wer nicht weiß, wohin das Geld fließt, kann es nicht steuern.`,
 lage:`Ein Haushaltsbuch (App, Tabelle oder Heft) macht die eigenen Ausgaben sichtbar. Als grobe Aufteilung hat sich die 50-30-20-Regel bewährt.`,
 punkte:[
  `50 % für Notwendiges (Miete, Nebenkosten, Lebensmittel, Versicherungen, Mobilität).`,
  `30 % für Wünsche (Freizeit, Restaurant, Hobbys, Abos).`,
  `20 % für Zukunft (Notgroschen, Sparen, Schulden tilgen).`,
  `Ein bis zwei Monate ehrlich alles notieren — die Überraschungen stecken in den kleinen Dauerposten.`],
 fehler:`Nur die großen Rechnungen sehen — Abos, Snacks und Spontankäufe summieren sich unbemerkt zum größten Loch.`,
 merk:`50 % Bedarf · 30 % Wünsche · 20 % Zukunft — als Startaufteilung, an das eigene Leben angepasst.`,
 tipp:`Automatisiere die 20 %: ein Dauerauftrag am Monatsanfang aufs Sparkonto — „pay yourself first“, bevor das Geld ausgegeben ist.`},
{id:"schufa",n:"SCHUFA & Bonität",kat:"konto",typ:"basis",
 kurz:`Deine Kreditwürdigkeit in einer Zahl — die du kostenlos einsehen darfst.`,
 lage:`Auskunfteien wie die SCHUFA sammeln Daten zu deinem Zahlungsverhalten und errechnen einen Score. Er entscheidet über Mietvertrag, Ratenkauf und Kreditzins.`,
 punkte:[
  `Einmal im Jahr kostenlos: die Datenkopie nach Art. 15 DSGVO anfordern und auf Fehler prüfen.`,
  `Falsche oder veraltete Einträge schriftlich korrigieren lassen — Fehler sind häufiger als gedacht.`,
  `Den Score verbessern: Rechnungen pünktlich zahlen, nicht zu viele Konten/Karten gleichzeitig, keine unnötigen Kreditanfragen.`,
  `Wichtig bei Kreditvergleichen: als „Konditionsanfrage“ stellen, nicht als „Kreditanfrage“ — sonst verschlechtert jede Anfrage den Score.`],
 fehler:`Erst bei der abgelehnten Wohnung merken, dass ein falscher Eintrag den Score drückt — jährlich selbst prüfen.`,
 tipp:`Vor Wohnungssuche oder Kreditwunsch die eigene Datenkopie holen — Fehler zu korrigieren dauert Wochen, die man einplanen muss.`},
{id:"pkonto",n:"Pfändungsschutz: das P-Konto",kat:"konto",typ:"schutz",
 kurz:`Bei Schulden schützt das P-Konto das Existenzminimum vor Pfändung.`,
 lage:`Jedes Girokonto lässt sich in ein Pfändungsschutzkonto (P-Konto) umwandeln. Dann bleibt ein monatlicher Grundfreibetrag automatisch geschützt und verfügbar.`,
 punkte:[
  `Nur ein P-Konto pro Person erlaubt; die Umwandlung ist ein Recht und kostenlos.`,
  `Der Grundfreibetrag ist gesetzlich festgelegt und wird jährlich angepasst; für Kinder/Unterhalt gibt es Erhöhungen (Bescheinigung nötig).`,
  `Bei Schulden früh eine (kostenlose) Schuldnerberatung aufsuchen — sie kennt alle Schutzrechte.`,
  `Ruhe bewahren: Pfändung heißt nicht mittellos — das Existenzminimum ist geschützt.`],
 fehler:`Erst nach der ersten Pfändung reagieren — das P-Konto sollte VORHER eingerichtet sein, sonst ist Geld kurzzeitig blockiert.`,
 warn:`Bei drohender Überschuldung: kostenlose Schuldnerberatung (Caritas, Diakonie, Verbraucherzentrale) — je früher, desto mehr Handlungsspielraum.`,
 tipp:`Das P-Konto ist ein Schutzschild, kein Makel — es zu kennen, bevor man es braucht, nimmt dem Thema den Schrecken.`},

/* -- Sparen & Notgroschen -- */
{id:"notgroschen",n:"Der Notgroschen",kat:"sparen",typ:"planen",
 kurz:`Das erste Sparziel vor allen anderen — Geld für den kaputten Kühlschrank.`,
 lage:`Der Notgroschen ist eine Reserve für Unvorhergesehenes: Reparatur, Autopanne, kaputte Waschmaschine. Er verhindert, dass jeder Zwischenfall zum teuren Dispo-Kredit wird.`,
 punkte:[
  `Richtwert: 3 bis 6 Nettomonatsausgaben, je nach Lebenssituation (Familie/selbstständig eher mehr).`,
  `Er gehört aufs Tagesgeldkonto — jederzeit verfügbar, getrennt vom Girokonto, nicht angelegt in Aktien.`,
  `Erst der Notgroschen, dann investieren: Wer in der Krise Aktien verkaufen muss, verkauft oft im schlechtesten Moment.`,
  `Nach jeder Nutzung wieder auffüllen.`],
 fehler:`Investieren, bevor die Reserve steht — dann zwingt der erste Notfall zum Verkauf zur Unzeit.`,
 merk:`3–6 Nettomonatsausgaben auf dem Tagesgeldkonto — jederzeit greifbar.`,
 tipp:`Rechne EINMAL deine Monatsausgaben aus und multipliziere mit drei — diese Zahl ist dein erstes, wichtigstes Sparziel.`},
{id:"zinseszins",n:"Zinseszins & die 72er-Regel",kat:"sparen",typ:"basis",
 kurz:`Zinsen auf Zinsen — der stärkste (oder teuerste) Effekt der Finanzwelt.`,
 lage:`Wer Erträge wieder anlegt, verdient auch auf die Erträge. Über lange Zeiträume wächst Geld dadurch nicht linear, sondern exponentiell — beim Schuldenmachen wirkt derselbe Effekt gegen dich.`,
 punkte:[
  `Zeit ist der wichtigste Faktor: Früh anfangen schlägt viel einzahlen.`,
  `Die 72er-Regel: 72 geteilt durch den Zinssatz ergibt grob die Jahre bis zur Verdopplung (z. B. 6 % → ca. 12 Jahre).`,
  `Derselbe Effekt macht Dispo- und Kreditzinsen so gefährlich — Schulden wachsen genauso exponentiell.`,
  `Erträge nicht entnehmen, sondern wieder anlegen (thesaurieren), verstärkt den Effekt.`],
 fehler:`„Ich fange an, wenn ich mehr verdiene“ — die verlorenen frühen Jahre holt später keine höhere Sparrate mehr ein.`,
 merk:`72 ÷ Zinssatz ≈ Jahre bis zur Verdopplung.`,
 tipp:`Spiel mit der 72er-Regel: Sie macht in Sekunden begreiflich, warum zehn Jahre früher anfangen mehr bringt als doppelt so viel sparen.`},
{id:"inflation",n:"Inflation & Kaufkraft",kat:"sparen",typ:"basis",
 kurz:`Geld auf dem Konto wird jedes Jahr leise weniger wert.`,
 lage:`Inflation bedeutet: Die Preise steigen, für denselben Euro bekommt man weniger. Bargeld und niedrig verzinste Guthaben verlieren real an Wert, auch wenn die Zahl gleich bleibt.`,
 punkte:[
  `Beispiel: Bei 2 % Inflation sind 100 € nach einem Jahr real nur noch rund 98 € wert.`,
  `„Sicher“ ist nicht gleich „werterhaltend“: Geld unterm Kopfkissen ist nominal sicher, verliert aber real.`,
  `Gegen Inflation hilft, dass das Geld mindestens die Teuerung ausgleicht — reine Nullzins-Konten tun das nicht.`,
  `Der Notgroschen darf trotzdem liquide bleiben — hier zählt Verfügbarkeit mehr als Rendite.`],
 fehler:`Große Beträge dauerhaft unverzinst „parken“ und den schleichenden Kaufkraftverlust nicht bemerken.`,
 tipp:`Trenne die Töpfe: Notgroschen sicher und verfügbar, langfristiges Geld so anlegen, dass es die Inflation zumindest ausgleicht.`},
{id:"tagesgeld",n:"Tagesgeld, Festgeld & Einlagensicherung",kat:"sparen",typ:"basis",
 kurz:`Sicher parken — und wissen, bis zu welcher Summe der Staat schützt.`,
 lage:`Tagesgeld ist täglich verfügbar, Festgeld für eine feste Laufzeit meist etwas höher verzinst. Beides ist über die gesetzliche Einlagensicherung geschützt.`,
 punkte:[
  `Einlagensicherung: In der EU sind Guthaben bis 100.000 € pro Bank und Kunde geschützt.`,
  `Große Summen auf mehrere Banken verteilen, um innerhalb der Sicherung zu bleiben.`,
  `Tagesgeld für den Notgroschen und kurzfristiges Geld; Festgeld nur für Beträge, die man sicher länger nicht braucht.`,
  `Lockangebote prüfen: hohe „Neukundenzinsen“ gelten oft nur wenige Monate.`],
 fehler:`Mehr als 100.000 € bei einer einzigen Bank halten — über der Sicherungsgrenze trägt man das Bankenrisiko selbst.`,
 merk:`Gesetzliche Einlagensicherung: 100.000 € pro Bank und Kunde.`,
 tipp:`Bei größeren Summen auf mehrere Banken verteilen — so bleibt jeder Euro innerhalb der gesetzlichen Sicherung.`},
{id:"sparplan",n:"Automatisch sparen (Sparplan)",kat:"sparen",typ:"planen",
 kurz:`Der Dauerauftrag ist die beste Disziplin — er spart, bevor du es merkst.`,
 lage:`Ein Sparplan bucht automatisch einen festen Betrag ab — aufs Tagesgeld oder in einen Wertpapier-Sparplan. Das Geld ist weg, bevor es ausgegeben werden kann.`,
 punkte:[
  `„Pay yourself first“: Sparrate am Monatsanfang abbuchen, nicht hoffen, dass am Ende etwas übrig bleibt.`,
  `Klein anfangen ist besser als warten — die Rate lässt sich jederzeit erhöhen.`,
  `Kurzfristige Ziele (Urlaub, Reserve) aufs Tagesgeld; langfristige (Jahrzehnte) breit gestreut investieren.`,
  `Bei Gehaltserhöhungen die Sparrate mit anheben, bevor sich der Lebensstandard daran gewöhnt.`],
 fehler:`Sparen als „Restgröße“ am Monatsende behandeln — dann bleibt fast nie etwas übrig.`,
 tipp:`Richte den Sparauftrag auf den Tag nach dem Gehaltseingang ein — was gar nicht erst auf dem Girokonto liegt, gibt niemand aus.`},

/* -- Steuern -- */
{id:"steuererklaerung",n:"Steuererklärung: Pflicht oder Chance",kat:"steuern",typ:"planen",
 kurz:`Für viele freiwillig — und dann fast immer mit Erstattung.`,
 lage:`Nicht jeder muss eine Steuererklärung abgeben, aber für Arbeitnehmer lohnt sie sich meist: Im Schnitt gibt es eine vierstellige Erstattung. Freiwillige können bis zu vier Jahre rückwirkend abgeben.`,
 punkte:[
  `Pflicht besteht z. B. bei mehreren Jobs, Lohnersatzleistungen (Kurzarbeit, Elterngeld) oder Steuerklassenkombination III/V.`,
  `Freiwillig lohnt sich fast immer, wenn Werbungskosten, Handwerker, Spenden oder Fahrtkosten anfallen.`,
  `Rückwirkend: Die freiwillige Erklärung ist bis zu 4 Jahre möglich (also lassen sich vergangene Jahre noch nachholen).`,
  `Werkzeuge: das kostenlose ELSTER-Portal oder eine Steuersoftware; bei komplexen Fällen Lohnsteuerhilfeverein oder Steuerberater.`],
 fehler:`Aus Respekt vor dem Formular gar nicht abgeben — und damit im Schnitt eine vierstellige Erstattung liegen lassen.`,
 tipp:`Zahlungsbelege übers Jahr in einem Ordner „Steuer“ sammeln (siehe Kompendium „Papierkram“) — dann ist die Erklärung im Frühjahr in einer Stunde erledigt.`},
{id:"steuerklassen",n:"Steuerklassen verstehen",kat:"steuern",typ:"basis",
 kurz:`Die Steuerklasse ändert nur, WANN du zahlst — nicht, WIE VIEL am Jahresende.`,
 lage:`Die Lohnsteuerklasse bestimmt den monatlichen Abzug. Über das Jahr gleicht die Steuererklärung alles aus — die Klasse verschiebt nur die Liquidität.`,
 punkte:[
  `Ledige haben Klasse I, Alleinerziehende IV mit Entlastungsbetrag (Klasse II).`,
  `Ehepaare wählen: IV/IV (gleich verteilt) oder III/V (ein hohes, ein niedriges Einkommen) — III/V bringt monatlich mehr netto beim Hauptverdiener, führt aber oft zur Nachzahlung.`,
  `Das Faktorverfahren (IV/IV mit Faktor) verteilt fairer und vermeidet böse Überraschungen.`,
  `Die Klasse beeinflusst Lohnersatzleistungen (Eltern-, Kranken-, Arbeitslosengeld) — vor Elternzeit rechtzeitig prüfen.`],
 fehler:`III/V wählen und sich übers hohe Netto freuen — und dann die Steuernachzahlung vergessen.`,
 tipp:`Vor Elterngeld oder längerer Krankheit die Steuerklasse prüfen: Sie kann die Höhe der Lohnersatzleistung spürbar verändern.`},
{id:"werbungskosten",n:"Werbungskosten & Pauschbetrag",kat:"steuern",typ:"planen",
 kurz:`Was du für den Job ausgibst, senkt die Steuer — bis zum Pauschbetrag ganz ohne Belege.`,
 lage:`Werbungskosten sind berufsbedingte Ausgaben. Bis zum Arbeitnehmer-Pauschbetrag zieht das Finanzamt sie automatisch ab; wer mehr hat, sammelt Belege und spart zusätzlich.`,
 punkte:[
  `Der Pauschbetrag (aktuell rund 1.230 € pro Jahr — genauen Wert prüfen) wird automatisch gewährt.`,
  `Typische Werbungskosten: Fahrten zur Arbeit (Pendlerpauschale), Arbeitsmittel, Fortbildung, Bewerbungskosten, Homeoffice-Pauschale, doppelte Haushaltsführung.`,
  `Erst wenn die Summe über dem Pauschbetrag liegt, lohnt das Sammeln — dann aber jeder Beleg.`,
  `Getrennt davon: Sonderausgaben (z. B. Vorsorge, Spenden) und haushaltsnahe Dienstleistungen/Handwerker.`],
 fehler:`Denken „lohnt sich eh nicht“ — schon der normale Arbeitsweg füllt den Pauschbetrag oft und übertrifft ihn.`,
 tipp:`Rechne einmal die Pendlerpauschale übers Jahr aus — viele überschreiten allein damit den Pauschbetrag und sparen mit jedem weiteren Beleg.`},
{id:"sparerpauschbetrag",n:"Freistellungsauftrag & Sparerpauschbetrag",kat:"steuern",typ:"planen",
 kurz:`Kapitalerträge bleiben bis zu einem Freibetrag steuerfrei — wenn du den Auftrag erteilst.`,
 lage:`Zinsen und Dividenden sind bis zum Sparerpauschbetrag steuerfrei. Damit die Bank keine Steuer einbehält, musst du ihr einen Freistellungsauftrag erteilen.`,
 punkte:[
  `Der Sparerpauschbetrag liegt aktuell bei 1.000 € pro Person (2.000 € für zusammen veranlagte Paare) — Wert prüfen, er kann sich ändern.`,
  `Freistellungsauftrag bei jeder Bank einrichten und die Summe auf mehrere Banken aufteilen, wenn nötig.`,
  `Ohne Auftrag zieht die Bank automatisch Steuer ab — zurückholen geht dann nur über die Steuererklärung.`,
  `Aufträge im Blick behalten und anpassen, wenn sich Konten oder Depots ändern.`],
 fehler:`Keinen Freistellungsauftrag erteilen und Jahr für Jahr unnötig Steuer auf kleine Zinsen zahlen.`,
 merk:`Steuerfrei aktuell bis 1.000 € (Single) bzw. 2.000 € (Paar) — Freistellungsauftrag nicht vergessen.`,
 tipp:`Beim Eröffnen jedes Zins- oder Wertpapierkontos sofort den Freistellungsauftrag mit einrichten — der häufigste vergessene Handgriff beim Sparen.`},
{id:"kapitalertragsteuer",n:"Kapitalertragsteuer (Abgeltungsteuer)",kat:"steuern",typ:"basis",
 kurz:`Auf Gewinne aus Zinsen, Dividenden und Verkäufen fällt eine pauschale Steuer an.`,
 lage:`Erträge aus Kapitalanlagen werden mit der Abgeltungsteuer belegt. Bei inländischen Banken wird sie meist automatisch einbehalten und abgeführt.`,
 punkte:[
  `Satz: 25 % Abgeltungsteuer plus Solidaritätszuschlag darauf und ggf. Kirchensteuer.`,
  `Erst über dem Sparerpauschbetrag fällt sie an — deshalb den Freistellungsauftrag nutzen.`,
  `Bei ausländischen Depots oder fehlendem Steuerabzug müssen Erträge selbst in der Steuererklärung angegeben werden.`,
  `Verluste lassen sich mit Gewinnen verrechnen (Verlustverrechnungstöpfe der Bank).`],
 fehler:`Erträge im ausländischen Depot „vergessen“ — sie sind trotzdem steuerpflichtig und anzugeben.`,
 tipp:`Wer nur bei einer deutschen Bank anlegt, muss meist nichts tun — die Steuer läuft automatisch; wichtig bleibt nur der Freistellungsauftrag.`},
{id:"kindergeld",n:"Kindergeld & Kinderfreibetrag",kat:"steuern",typ:"planen",
 kurz:`Beides gibt es nicht zusammen — das Finanzamt rechnet automatisch das Günstigere.`,
 lage:`Für Kinder gibt es entweder monatliches Kindergeld oder den steuerlichen Kinderfreibetrag. Das Finanzamt prüft in der Steuererklärung, was für dich günstiger ist (Günstigerprüfung).`,
 punkte:[
  `Kindergeld muss bei der Familienkasse beantragt werden — es kommt nicht automatisch.`,
  `Es wird in der Regel bis 18 gezahlt, bei Ausbildung/Studium bis maximal 25.`,
  `Der Kinderfreibetrag lohnt sich eher bei höheren Einkommen; die Prüfung macht das Finanzamt von selbst.`,
  `Weitere Entlastungen prüfen: Kinderbetreuungskosten, Entlastungsbetrag für Alleinerziehende, Ausbildungsfreibetrag.`],
 fehler:`Kindergeld nicht (rechtzeitig) beantragen — rückwirkend wird es nur begrenzt nachgezahlt.`,
 tipp:`Direkt nach der Geburt Kindergeld beantragen (geht zusammen mit der Geburtsurkunde) — und bei volljährigen Kindern in Ausbildung den Weiterbezug im Blick behalten.`},

/* -- Vorsorge & Versichern -- */
{id:"rente",n:"Gesetzliche Rente & Versorgungslücke",kat:"vorsorge",typ:"basis",
 kurz:`Die gesetzliche Rente ist ein Fundament — meist aber kein volles Dach.`,
 lage:`Die gesetzliche Rente funktioniert im Umlageverfahren: Heutige Beitragszahler finanzieren heutige Renten. Sie ersetzt später nur einen Teil des letzten Einkommens — die Differenz ist die Versorgungslücke.`,
 punkte:[
  `Die jährliche Renteninformation LESEN — sie zeigt die grobe zu erwartende Rente.`,
  `Faustregel: Die gesetzliche Rente ersetzt oft nur rund die Hälfte des letzten Nettoeinkommens; die Lücke muss privat/betrieblich geschlossen werden.`,
  `Rentenlücken (Ausbildung, Kindererziehung, Auslandsjahre) selbst nachweisen — Kontenklärung ab Mitte 40 (siehe Kompendium „Papierkram“).`,
  `Je früher man die Lücke kennt, desto kleiner die nötige Sparrate (Zinseszins).`],
 fehler:`Die Renteninformation ungelesen ablegen — und die Versorgungslücke erst mit 60 entdecken, wenn Gegensteuern teuer wird.`,
 tipp:`Nimm dir die nächste Renteninformation und ziehe die genannte Rente von deinem heutigen Nettobedarf ab — diese Zahl ist der ehrliche Startpunkt jeder Vorsorge.`},
{id:"altersvorsorge",n:"Die drei Schichten der Altersvorsorge",kat:"vorsorge",typ:"planen",
 kurz:`Gesetzlich, betrieblich, privat — ein Dach auf drei Säulen.`,
 lage:`Altersvorsorge steht in Deutschland auf drei Schichten. Wer nur auf eine setzt, steht wackliger als nötig.`,
 punkte:[
  `Erste Schicht: gesetzliche Rente und Basis-/Rürup-Rente (Pflicht bzw. für Selbstständige).`,
  `Zweite Schicht: betriebliche Altersvorsorge und geförderte Produkte — oft mit Arbeitgeber- oder Staatszuschuss.`,
  `Dritte Schicht: freies privates Sparen (z. B. breit gestreute Wertpapiere, Immobilie).`,
  `Reihenfolge sinnvoll nutzen: erst Zuschüsse mitnehmen (Arbeitgeber, Staat), dann frei sparen.`],
 fehler:`Nur auf die gesetzliche Rente vertrauen — sie ist als alleinige Absicherung für die meisten zu wenig.`,
 tipp:`Zuschüsse zuerst: Wo Arbeitgeber oder Staat mitzahlen, ist die „Rendite“ konkurrenzlos — dieses Geld sollte niemand liegen lassen.`},
{id:"bav",n:"Betriebliche Altersvorsorge",kat:"vorsorge",typ:"planen",
 kurz:`Vom Brutto sparen — oft mit Zuschuss vom Chef obendrauf.`,
 lage:`Bei der Entgeltumwandlung fließt ein Teil des Bruttogehalts in eine Betriebsrente. Das spart heute Steuern und Sozialabgaben; Arbeitgeber müssen sich in der Regel mit einem Zuschuss beteiligen.`,
 punkte:[
  `Vorteil heute: Beiträge mindern Brutto, also Steuer und Sozialabgaben.`,
  `Arbeitgeberzuschuss (in der Regel mindestens 15 %) ist geschenktes Geld — unbedingt mitnehmen.`,
  `Nachteil beachten: In der Auszahlungsphase fallen Steuern und meist Krankenkassenbeiträge an; wer weniger einzahlt, hat auch weniger gesetzliche Rente.`,
  `Vor Abschluss die Konditionen und Kosten des angebotenen Vertrags prüfen — nicht jeder ist gut.`],
 fehler:`Blind jeden bAV-Vertrag abschließen — oder umgekehrt den Arbeitgeberzuschuss ungenutzt lassen.`,
 tipp:`Frag im Betrieb konkret nach dem Zuschuss und den Vertragskosten — lohnt sich vor allem, wenn der Arbeitgeber deutlich mehr als das Minimum dazugibt.`},
{id:"versicherungscheck",n:"Welche Versicherungen wirklich wichtig sind",kat:"vorsorge",typ:"planen",
 kurz:`Versichere, was dich ruinieren kann — nicht, was nur ärgert.`,
 lage:`Die Grundregel der Versicherung: Absichern muss man existenzbedrohende Risiken. Kleine, verkraftbare Schäden zahlt man besser selbst, statt Beiträge zu verschenken.`,
 punkte:[
  `Für fast alle wichtig: Krankenversicherung (Pflicht), private Haftpflicht (deckt Schäden, die du anderen zufügst), Berufsunfähigkeit (deine Arbeitskraft).`,
  `Je nach Lage sinnvoll: Hausrat, Kfz-Haftpflicht (Pflicht), Risikolebensversicherung (bei Familie/Immobilie), Rechtsschutz.`,
  `Faustregel: großes Risiko + geringe Wahrscheinlichkeit = versichern; kleiner Schaden = selbst tragen.`,
  `Verträge alle paar Jahre prüfen und vergleichen — Bedarf und Preise ändern sich.`],
 fehler:`Viele kleine „Wohlfühl“-Policen abschließen, aber die existenziellen (Haftpflicht, BU) vernachlässigen.`,
 merk:`Versichern, was existenzbedrohend ist. Kleinschäden selbst tragen.`,
 tipp:`Die private Haftpflicht ist für wenige Euro im Monat die wichtigste freiwillige Versicherung überhaupt — ein fahrlässig verursachter Personenschaden kann sonst lebenslang kosten.`},
{id:"bu",n:"Berufsunfähigkeit: deine Arbeitskraft",kat:"vorsorge",typ:"schutz",
 kurz:`Dein größtes Vermögen ist die Fähigkeit, Geld zu verdienen — und die ist gefährdet.`,
 lage:`Wer aus gesundheitlichen Gründen nicht mehr arbeiten kann, verliert sein Einkommen. Die staatliche Absicherung (Erwerbsminderungsrente) ist oft niedrig — die Berufsunfähigkeitsversicherung (BU) schließt diese Lücke.`,
 punkte:[
  `Das Risiko ist real: Ein nennenswerter Anteil der Menschen wird im Laufe des Berufslebens berufsunfähig — häufig durch psychische Erkrankungen oder Rückenleiden, nicht durch Unfälle.`,
  `Früh abschließen: Je jünger und gesünder, desto günstiger und leichter der Vertrag (Gesundheitsfragen!).`,
  `Auf die Details achten: Verzicht auf „abstrakte Verweisung“, ausreichende Rentenhöhe, Laufzeit bis zum Rentenbeginn.`,
  `Auch für Berufseinsteiger, Azubis und Studierende sinnvoll.`],
 fehler:`Die BU „später“ abschließen wollen — mit den Jahren kommen Vorerkrankungen, die den Vertrag verteuern oder unmöglich machen.`,
 tipp:`Wenn nur eine einzige zusätzliche Versicherung möglich ist, ist es für die meisten Berufstätigen die Berufsunfähigkeitsversicherung — je früher, desto besser.`},
{id:"versicherungsfallen",n:"Unnötige Versicherungen",kat:"vorsorge",typ:"schutz",
 kurz:`Manche Policen kosten mehr Nerven im Kleingedruckten, als sie je auszahlen.`,
 lage:`Viele Versicherungen decken kleine Schäden, die man locker selbst tragen kann — oder sind so voller Ausschlüsse, dass sie selten zahlen. Sie kosten Beiträge, die woanders besser aufgehoben sind.`,
 punkte:[
  `Meist verzichtbar: Handy-, Brillen-, Glasbruch-, Reisegepäck-, Sterbegeld- und viele „Garantieverlängerungen“.`,
  `Kritisch prüfen: Policen, die an der Haustür, am Telefon oder als „Gratis-Zugabe“ verkauft werden.`,
  `Das gesparte Geld lieber in den Notgroschen — er ersetzt viele Kleinversicherungen.`,
  `Bestehende Verträge durchsehen und Überflüssiges kündigen (Fristen beachten — siehe Kompendium „Papierkram“).`],
 fehler:`Beim Elektronikkauf reflexhaft die teure „Garantieverlängerung“ mitnehmen — die gesetzliche Gewährleistung greift ohnehin zwei Jahre.`,
 tipp:`Frag bei jeder angebotenen Police: „Würde mich dieser Schaden finanziell ruinieren?“ Nur wenn die Antwort Ja ist, lohnt die Versicherung.`},

/* -- Investieren — Grundlagen -- */
{id:"risikorendite",n:"Risiko & Rendite",kat:"invest",typ:"basis",
 kurz:`Es gibt keine hohe Rendite ohne Risiko — wer etwas anderes verspricht, lügt.`,
 lage:`Rendite ist der Ertrag einer Anlage, Risiko die Schwankung und Verlustmöglichkeit. Beide hängen untrennbar zusammen: Mehr Renditechance bedeutet immer mehr Risiko.`,
 punkte:[
  `Sichere Anlagen (Tagesgeld) bringen wenig, schwankende (Aktien) langfristig mehr — mit zwischenzeitlichen Verlusten.`,
  `„Sicher UND hohe Rendite“ existiert nicht — dieses Versprechen ist das häufigste Merkmal von Betrug.`,
  `Das eigene Risiko an den Zeithorizont anpassen: kurzfristig sicher, langfristig darf es schwanken.`,
  `Nur Geld anlegen, dessen zwischenzeitlichen Wertverlust man aushalten kann, ohne verkaufen zu müssen.`],
 fehler:`Auf „garantiert hohe Renditen“ hereinfallen — genau so beginnt fast jeder Anlagebetrug.`,
 warn:`Versprechen wie „sichere 10 % im Monat“, Krypto-„Verdopplung“ oder gedrängte Sofort-Abschlüsse sind klassische Betrugsmuster (siehe Kompendium „Sicher im Netz“).`,
 tipp:`Merke den einen Satz, der dich vor den meisten Finanzfallen schützt: „Ist es zu schön, um wahr zu sein, ist es nicht wahr.“`},
{id:"streuung",n:"Streuung (Diversifikation)",kat:"invest",typ:"basis",
 kurz:`Nicht alle Eier in einen Korb — der älteste und beste Anlagegrundsatz.`,
 lage:`Streuung bedeutet, das Geld auf viele verschiedene Werte, Branchen und Länder zu verteilen. Fällt eines, fangen die anderen es auf. Das senkt das Risiko, ohne die langfristige Renditechance zu opfern.`,
 punkte:[
  `Das größte vermeidbare Risiko ist das Klumpenrisiko: alles auf eine Aktie, eine Branche, ein Land.`,
  `Auch die eigene Firma/Aktie des Arbeitgebers ist ein Klumpen — dort hängt schon das Gehalt.`,
  `Breite Streuung erreicht man einfach über weltweit anlegende Fonds statt Einzelwerte.`,
  `Streuung ersetzt nicht den Notgroschen — sie ist kein Schutz gegen kurzfristigen Geldbedarf.`],
 fehler:`Auf „heiße Tipps“ und Einzelaktien setzen — ein einzelner Wert kann dauerhaft einbrechen, ein breiter Markt erholt sich historisch.`,
 tipp:`Wenn ein Investment „todsicher und riesig“ klingt, ist es das Gegenteil von Streuung — und meist das Gegenteil von sicher.`},
{id:"etf",n:"Aktien, Fonds & ETF verstehen",kat:"invest",typ:"basis",
 kurz:`Ein breit gestreuter Fonds macht dich in einem Schritt zum Miteigentümer tausender Firmen.`,
 lage:`Eine Aktie ist ein Anteil an einer Firma. Ein Fonds bündelt viele Werte; ein ETF ist ein besonders kostengünstiger Fonds, der einen Index (z. B. den Weltaktienmarkt) einfach nachbildet.`,
 punkte:[
  `ETFs sind meist deutlich günstiger als aktiv gemanagte Fonds — die laufende Kostenquote (TER) frisst sonst die Rendite.`,
  `Ein weltweit streuender Aktien-ETF verteilt das Geld automatisch auf viele Länder und Branchen.`,
  `„Thesaurierend“ legt Erträge automatisch wieder an (Zinseszins), „ausschüttend“ zahlt sie aus.`,
  `Kosten sind der einzige verlässlich beeinflussbare Faktor — auf niedrige TER und keine Ausgabeaufschläge achten.`],
 fehler:`Teure Produkte mit hohen Gebühren und Ausgabeaufschlägen kaufen, die die Rendite auffressen — Kosten sind der stille Rendite-Killer.`,
 warn:`Dies ist allgemeine Bildung, keine Anlageempfehlung. Vor eigenen Entscheidungen unabhängig informieren (z. B. Verbraucherzentrale) und nur verstehen, was man kauft.`,
 tipp:`Die wichtigste Kennzahl beim Fonds ist die laufende Kostenquote (TER) — je niedriger, desto mehr Rendite bleibt langfristig bei dir.`},
{id:"anlagehorizont",n:"Zeit, Kosten & Sparplan-Prinzip",kat:"invest",typ:"planen",
 kurz:`Langfristig, günstig, regelmäßig — die drei Hebel, die jeder selbst in der Hand hat.`,
 lage:`Beim langfristigen Anlegen entscheiden nicht kluge Zeitpunkte, sondern Durchhalten, niedrige Kosten und ein langer Atem. Kurzfristige Schwankungen verlieren über die Jahre an Bedeutung.`,
 punkte:[
  `Zeit schlägt Timing: Wer investiert bleibt, schlägt langfristig fast jeden, der ein und aus steigt.`,
  `Sparplan (Cost-Average): regelmäßig gleiche Beträge investieren — mal teurer, mal günstiger, im Schnitt entspannt.`,
  `Nur Geld anlegen, das man 10+ Jahre nicht braucht; kurzfristiges Geld bleibt sicher (Tagesgeld).`,
  `Ruhe bewahren: In Krisen nicht panisch verkaufen — genau dann werden Kursverluste real.`],
 fehler:`Bei fallenden Kursen panisch verkaufen und bei Höchstständen euphorisch kaufen — das genaue Gegenteil des Erfolgreichen.`,
 tipp:`Ein automatischer Sparplan nimmt die Emotion aus dem Spiel — er kauft stur weiter, auch wenn der Bauch schreit.`},

/* -- Eigentum & Wohnen -- */
{id:"mietekaufen",n:"Mieten oder Kaufen?",kat:"wohnen",typ:"planen",
 kurz:`Keine Glaubensfrage, sondern eine Rechenaufgabe — mit Lebensplanung im Nenner.`,
 lage:`Ob Kaufen oder Mieten günstiger ist, hängt von Kaufpreis, Zins, Mietniveau, Haltedauer und Lebensplanung ab. „Miete ist rausgeworfenes Geld“ ist ein Mythos — auch Zinsen und Kaufnebenkosten sind weg.`,
 punkte:[
  `Kaufen lohnt eher bei langer Haltedauer (Faustregel oft 10+ Jahre), stabilem Job und passender Lebensplanung.`,
  `Gegen den reinen Vergleich rechnen: Wer mietet und die Differenz spart/anlegt, steht nicht automatisch schlechter da.`,
  `Flexibilität hat Wert: Eigentum bindet an den Ort und ist teuer/langsam zu verkaufen.`,
  `Ehrlich kalkulieren mit ALLEN Kosten (siehe folgende Einträge: Kaufnebenkosten, Zins/Tilgung, Instandhaltung).`],
 fehler:`Nur Kaufpreis gegen Kaltmiete stellen — Kaufnebenkosten, Zinsen, Instandhaltung und Wertverlust fehlen dann in der Rechnung.`,
 tipp:`Nutze den Miet-Kauf-Rechner im Kit (Werkzeug „Mieten oder kaufen“) und spiele Zins, Haltedauer und Instandhaltung durch — die ehrliche Zahl entsteht erst mit allen Posten.`},
{id:"kaufnebenkosten",n:"Kaufnebenkosten beim Immobilienkauf",kat:"wohnen",typ:"schutz",
 kurz:`Zum Kaufpreis kommen rund 10 bis 15 % obendrauf — meist ohne Kredit.`,
 lage:`Der Kaufpreis ist nicht alles: Grunderwerbsteuer, Notar, Grundbuch und oft Makler summieren sich zu einem erheblichen Betrag, der in der Regel aus Eigenkapital bezahlt werden muss.`,
 punkte:[
  `Grunderwerbsteuer: je nach Bundesland rund 3,5 bis 6,5 % des Kaufpreises.`,
  `Notar und Grundbuch: zusammen rund 1,5 bis 2 %.`,
  `Maklerprovision: falls anfällt, je nach Region und Aufteilung mehrere Prozent (seit 2020 oft geteilt).`,
  `Summe: grob 10 bis 15 % zusätzlich — Banken finanzieren diese Nebenkosten meist nicht mit.`],
 fehler:`Die Nebenkosten in der Finanzierung „vergessen“ — dann fehlt beim Notartermin das Eigenkapital.`,
 merk:`Kaufnebenkosten grob 10–15 % des Kaufpreises — meist aus Eigenkapital.`,
 tipp:`Rechne die Nebenkosten getrennt und zusätzlich zum Kaufpreis — sie sind der Betrag, den fast alle beim ersten Mal unterschätzen.`},
{id:"eigenkapital",n:"Eigenkapital & Finanzierung",kat:"wohnen",typ:"planen",
 kurz:`Je mehr Eigenkapital, desto günstiger der Kredit — und desto ruhiger schläft es sich.`,
 lage:`Beim Immobilienkauf finanziert die Bank einen Teil, den Rest bringt man selbst mit. Als Faustregel sollten mindestens die Kaufnebenkosten plus etwa 20 % des Kaufpreises aus Eigenkapital kommen.`,
 punkte:[
  `Mehr Eigenkapital = niedrigerer Zins und geringere Restschuld — die Bank belohnt Sicherheit.`,
  `Faustregel: Kaufnebenkosten (10–15 %) plus möglichst 20 % des Kaufpreises selbst mitbringen.`,
  `Die monatliche Rate sollte dauerhaft tragbar sein — auch bei Zinsanstieg nach Ablauf der Zinsbindung.`,
  `Puffer einplanen: Instandhaltung, Rücklagen und ein Notgroschen bleiben trotz Kredit nötig.`],
 fehler:`Bis zur letzten Reserve „alles reinstecken“ — ohne Puffer wird die erste größere Reparatur zur Krise.`,
 merk:`Möglichst Kaufnebenkosten + rund 20 % des Kaufpreises als Eigenkapital.`,
 tipp:`Plane die Rate so, dass sie auch mit einem höheren Anschlusszins noch passt — die Zinsbindung endet, die Immobilie bleibt.`},
{id:"tilgung",n:"Zins, Tilgung & Sollzinsbindung",kat:"wohnen",typ:"basis",
 kurz:`Zins ist der Preis des Kredits, Tilgung ist die Rückzahlung — und die Bindung sichert den Zins.`,
 lage:`Die monatliche Kreditrate besteht aus Zins und Tilgung. Anfangs ist der Zinsanteil hoch; mit sinkender Restschuld steigt der Tilgungsanteil. Die Sollzinsbindung legt fest, wie lange der Zins garantiert ist.`,
 punkte:[
  `Anfängliche Tilgung: Ein höherer Tilgungssatz (z. B. 2–3 % statt 1 %) verkürzt die Laufzeit erheblich.`,
  `Sollzinsbindung: Je länger (z. B. 15–20 Jahre), desto planbarer — nach Ablauf bleibt eine Restschuld, die neu finanziert wird (Anschlussfinanzierung).`,
  `Sondertilgungen vereinbaren: Sie erlauben, den Kredit schneller zu drücken.`,
  `Das Zinsänderungsrisiko der Anschlussfinanzierung früh mitdenken.`],
 fehler:`Sich von einer niedrigen 1-%-Tilgung locken lassen — die Rate ist klein, aber die Rückzahlung dauert ewig und kostet viel Zins.`,
 tipp:`Wähl die höchste Tilgung, die du dir dauerhaft leisten kannst — jeder Prozentpunkt mehr spart am Ende oft fünfstellig an Zinsen.`},
{id:"grundbuch",n:"Grundbuch & Grundschuld",kat:"wohnen",typ:"basis",
 kurz:`Das amtliche Verzeichnis, wem was gehört — und wer mitreden darf.`,
 lage:`Im Grundbuch steht, wem ein Grundstück gehört und welche Rechte und Lasten darauf liegen. Wer eine Immobilie mit Kredit kauft, lässt zugunsten der Bank eine Grundschuld eintragen.`,
 punkte:[
  `Aufbau: Abteilung I (Eigentümer), II (Lasten/Rechte wie Wegerechte, Wohnrechte), III (Grundschulden/Hypotheken).`,
  `Vor dem Kauf einen aktuellen Grundbuchauszug prüfen — Altlasten und Rechte Dritter stehen hier.`,
  `Die Grundschuld sichert den Bankkredit; nach vollständiger Rückzahlung eine Löschungsbewilligung anfordern (siehe Kompendium „Papierkram“).`,
  `Änderungen laufen über den Notar — nichts im Grundbuch geht „mal eben“ privat.`],
 fehler:`Die alte Grundschuld nach der Rückzahlung im Grundbuch stehen lassen — beim späteren Verkauf sorgt das für Aufwand.`,
 tipp:`Nach der letzten Kreditrate aktiv die Löschung der Grundschuld anstoßen (oder bewusst als „Reserve“ behalten) — nicht einfach vergessen.`},
{id:"weg",n:"Eigentümergemeinschaft & Hausgeld",kat:"wohnen",typ:"schutz",
 kurz:`Wer eine Wohnung kauft, kauft Mitbestimmung — und Mitverantwortung fürs ganze Haus.`,
 lage:`Beim Kauf einer Eigentumswohnung wird man Teil der Wohnungseigentümergemeinschaft (WEG). Über gemeinsames Eigentum (Dach, Fassade, Treppenhaus) wird zusammen entschieden und bezahlt.`,
 punkte:[
  `Hausgeld: monatliche Zahlung für Betriebskosten, Verwaltung und die Erhaltungsrücklage.`,
  `Die Erhaltungsrücklage (früher „Instandhaltungsrücklage“) finanziert große Reparaturen — ihre Höhe vor dem Kauf prüfen.`,
  `Beschlüsse fallen in der Eigentümerversammlung per Mehrheit — man kann überstimmt werden.`,
  `Vor dem Kauf Protokolle der letzten Versammlungen und den Wirtschaftsplan lesen — sie verraten Streit, Sanierungsstau und Kosten.`],
 fehler:`Nur die Wohnung besichtigen, aber Rücklage, Protokolle und anstehende Sanierungen ignorieren — teure Sonderumlagen kommen dann als Überraschung.`,
 tipp:`Lies vor dem Kauf einer Eigentumswohnung die letzten drei Versammlungsprotokolle — kein Exposé verrät so ehrlich, was auf dich zukommt.`},
{id:"wohnnebenkosten",n:"Wohnnebenkosten, Wohngeld & Förderung",kat:"wohnen",typ:"planen",
 kurz:`Neben Miete oder Rate laufen die „zweite Miete“ und mögliche Zuschüsse.`,
 lage:`Betriebskosten, Energie und Instandhaltung machen einen erheblichen Teil der Wohnkosten aus. Zugleich gibt es staatliche Zuschüsse und Förderungen, die viele nicht kennen.`,
 punkte:[
  `Betriebskosten („zweite Miete“): Heizung, Wasser, Müll, Grundsteuer, Hausmeister — jährlich abrechnungspflichtig (siehe Kompendium „Papierkram“).`,
  `Wohngeld: ein staatlicher Zuschuss zu den Wohnkosten für Haushalte mit geringem Einkommen — auch für Eigentümer (Lastenzuschuss) möglich.`,
  `Förderung: zinsgünstige Kredite und Zuschüsse (z. B. der KfW) für Kauf, Sanierung und energetische Modernisierung — vor Auftragsvergabe beantragen.`,
  `Eigentümer: eine Instandhaltungsrücklage bilden — Faustwerte je Quadratmeter im Jahr helfen bei der Planung.`],
 fehler:`Förderungen erst NACH Vertragsabschluss oder Baubeginn beantragen — dann sind viele Programme nicht mehr möglich.`,
 tipp:`Vor jeder Sanierung erst Förderprogramme prüfen (KfW & Co.) und den Antrag VOR der Auftragsvergabe stellen — nachträglich gibt es das Geld meist nicht.`},
{id:"finanzabzocke",n:"Finanz-Fallen & Abzocke erkennen",kat:"invest",typ:"schutz",
 kurz:`Die verlockendsten Angebote sind die gefährlichsten — Druck und Traumrenditen sind die Alarmsignale.`,
 lage:`Rund ums Geld tummeln sich unseriöse Anbieter: dubiose „Anlageberater“, Krypto-Versprechen, geschlossene Beteiligungen mit Traumrenditen, Drückerkolonnen an der Haustür. Die Muster ähneln denen der Online-Betrüger.`,
 punkte:[
  `Alarmsignale: garantiert hohe Renditen, Zeitdruck („nur heute“), Geheimniskrämerei, angebliche Insider-Chancen, Zahlung ins Ausland oder in Krypto.`,
  `Grundregel: nur kaufen, was man versteht — und niemals unter Druck unterschreiben.`,
  `Vor jeder Geldanlage die Anbieter prüfen (BaFin-Warnliste, Verbraucherzentrale) und eine zweite, unabhängige Meinung einholen.`,
  `Provisionsgetriebene „Beratung“ hinterfragen: Wer am Abschluss verdient, ist selten neutral.`],
 fehler:`Aus Höflichkeit oder unter Zeitdruck am Küchentisch/Telefon einen Vertrag unterschreiben — seriöse Angebote vertragen jede Bedenkzeit.`,
 warn:`Dieselben Maschen laufen digital (siehe Kompendium „Sicher im Netz“: Romance Scam mit Krypto, gefälschte Handelsplattformen). „Zu schön, um wahr zu sein“ ist immer unwahr.`,
 tipp:`Nimm dir bei jeder Geldanlage das Recht auf eine Nacht Bedenkzeit — kein seriöses Angebot verschwindet über Nacht, jede Falle drängt.`}
];
