/* HeiBen — Selbermachen: kleine Reparaturen & Haushaltspflege.
   Datenbasis für haushalt.html. Schema je Eintrag:
   {id,n,kat,zw:["rep"|"pflege"|"vorb"],zeit:`Label`,zeitMin:Zahl,schwer:1-3,kosten,
    werkzeug,material,schritte:[`…`],fehler,sicherheit(optional),profi(optional),tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten. */

window.HH_KAT={bad:"Bad & Sanitär",kueche:"Küche & Geräte",waende:"Wände, Böden & Möbel",strom:"Strom & Licht",heizung:"Heizen & Lüften",wasch:"Wäsche & Textil",sicherheit:"Sicherheit & Notfall"};
window.HH_ZW={rep:"Reparieren",pflege:"Pflegen & Warten",vorb:"Vorbeugen"};

window.HAUSHALT=[
/* -- Bad & Sanitär -- */
{id:"abfluss",n:"Abfluss verstopft (Waschbecken & Dusche)",kat:"bad",zw:["rep"],zeit:`15–30 Min.`,zeitMin:15,schwer:1,kosten:`0–10 €`,
 werkzeug:`Saugglocke (Pümpel), Eimer, Gummihandschuhe; hartnäckig: Rohrreinigungsspirale`,material:``,
 schritte:[
  `Sichtbares zuerst: Haare und Seifenreste mit einem Haken (aufgebogene Büroklammer) aus dem Abflusssieb ziehen.`,
  `Pümpel: Überlauf mit nassem Lappen zuhalten, etwas Wasser einlaufen lassen und kräftig auf- und abpumpen.`,
  `Hilft das nicht: Eimer unterstellen, Siphon unter dem Becken von Hand abschrauben, ausleeren, reinigen, handfest montieren.`,
  `Mit heißem Wasser nachspülen und die Verschraubungen auf Dichtheit prüfen.`],
 fehler:`Chemischer Rohrreiniger als erstes Mittel — aggressiv, bei festen Pfropfen oft wirkungslos und schlecht für Rohre und Umwelt.`,
 sicherheit:`Wurde bereits Chemie eingesetzt: nicht zusätzlich pumpen — Spritzer sind ätzend.`,
 profi:`Gluckert es in mehreren Abflüssen gleichzeitig, sitzt das Problem im Fallrohr — Sache von Vermieter oder Fachbetrieb.`,
 tipp:`Ein Haarsieb für zwei Euro im Duschablauf verhindert neun von zehn Verstopfungen.`},
{id:"wcverstopft",n:"WC verstopft",kat:"bad",zw:["rep"],zeit:`10–20 Min.`,zeitMin:10,schwer:1,kosten:`0–15 €`,
 werkzeug:`WC-Pümpel mit großer Glocke, Eimer, Gummihandschuhe`,material:``,
 schritte:[
  `Nicht weiterspülen, wenn das Wasser steigt — erst den Pegel sinken lassen.`,
  `Pümpel dicht auf den Abgang setzen und mit kräftigen Stößen pumpen, bis es hörbar abläuft.`,
  `Alternativ Schwallspülung: einen Eimer Wasser zügig aus Hüfthöhe hineingießen.`,
  `Bleibt es zu: Rohrreinigungsspirale vorsichtig eindrehen statt Chemie.`],
 fehler:`Bei steigendem Wasser erneut spülen — die Schüssel läuft über.`,
 profi:`Sind WC und Dusche gleichzeitig betroffen, sitzt der Pfropf tiefer: erst den Vermieter informieren, bevor teuer ein Notdienst beauftragt wird.`,
 tipp:`Feuchttücher sind Verstopfer Nummer eins — auch „spülbare“ gehören in den Müll, nie ins WC.`},
{id:"spuelkasten",n:"WC-Spülung läuft nach",kat:"bad",zw:["rep"],zeit:`20–40 Min.`,zeitMin:20,schwer:2,kosten:`5–20 €`,
 werkzeug:`ggf. Schraubendreher; Essig oder Zitronensäure`,material:`Passende Dichtung, falls Reinigen nicht reicht`,
 schritte:[
  `Deckel abnehmen — meist nur aufgelegt oder über den Drückerknopf gesichert.`,
  `Heberglocke in der Mitte herausnehmen und die Dichtfläche entkalken (Essig, weicher Schwamm).`,
  `Schwimmer prüfen: Er muss sich frei bewegen und das Ventil rechtzeitig schließen — Höhe bei Bedarf justieren.`,
  `Ist die Dichtung verformt: passendes Ersatzteil für das Modell einsetzen.`],
 fehler:`Mit Gewalt am festsitzenden Deckel hebeln — Keramik bricht; erst den Mechanismus entriegeln.`,
 profi:`Unterputz-Spülkästen ohne Erfahrung lieber dem Fachmann überlassen. Ein Dauerläufer verschwendet hunderte Liter am Tag — in der Mietwohnung zügig dem Vermieter melden.`,
 tipp:`Meist ist nur Kalk auf der Dichtung schuld — Reinigen statt Tauschen reicht in der Hälfte der Fälle.`},
{id:"silikonfuge",n:"Silikonfuge erneuern",kat:"bad",zw:["rep"],zeit:`60–90 Min. + Trocknung`,zeitMin:60,schwer:2,kosten:`10–20 €`,
 werkzeug:`Cuttermesser oder Fugenkratzer, Kartuschenpistole, Kreppband, Sprühflasche mit Spüliwasser, Fugenglätter`,material:`Sanitärsilikon (fungizid, passender Farbton)`,
 schritte:[
  `Alte Fuge komplett herausschneiden und Reste rückstandslos entfernen — auf Altem hält nichts.`,
  `Fuge reinigen, entfetten und vollständig trocknen lassen.`,
  `Beidseitig mit Kreppband abkleben und das Silikon in einem gleichmäßigen Zug einspritzen.`,
  `Mit Spüliwasser einsprühen, mit dem Glätter abziehen und das Kreppband sofort entfernen.`,
  `24 Stunden nicht mit Wasser in Berührung bringen.`],
 fehler:`Neues Silikon über alte Reste ziehen — es haftet nicht und schimmelt doppelt so schnell.`,
 tipp:`Wer die Fuge nach dem Duschen kurz trocken abzieht, verdoppelt ihre Lebensdauer.`},
{id:"entkalken",n:"Duschkopf & Perlator entkalken",kat:"bad",zw:["pflege"],zeit:`10 Min. + Einwirkzeit`,zeitMin:10,schwer:1,kosten:`unter 5 €`,
 werkzeug:`Gefrierbeutel, Gummiband, Zange mit Tuch als Kratzschutz`,material:`Zitronensäure (oder verdünnte Essigessenz)`,
 schritte:[
  `Perlator (das Sieb an der Hahnspitze) mit Tuch und Zange abschrauben und zerlegen.`,
  `Teile 30 Minuten in warmer Zitronensäurelösung baden.`,
  `Duschkopf: gefüllten Beutel überstülpen, mit Gummiband fixieren, einwirken lassen.`,
  `Gründlich abspülen und wieder montieren.`],
 fehler:`Essigessenz unverdünnt auf Gummidichtungen und Chrom — greift beides an.`,
 tipp:`Kaum noch Druck am Hahn? Fast immer nur der verkalkte Perlator — ein Zwei-Minuten-Fix.`},
{id:"schimmelfugen",n:"Schimmel in Fugen entfernen",kat:"bad",zw:["rep","vorb"],zeit:`30 Min.`,zeitMin:30,schwer:1,kosten:`5–15 €`,
 werkzeug:`Sprühflasche, alte Zahnbürste, Gummihandschuhe`,material:`Schimmelentferner auf Alkoholbasis (mind. 70 %) oder Chlorbasis`,
 schritte:[
  `Fenster auf, Handschuhe an; Mittel aufsprühen und einwirken lassen.`,
  `Mit der Zahnbürste aus der Fuge bürsten und feucht nachwischen.`,
  `Fläche trocknen lassen und die Ursache angehen: stoßlüften, heizen, Wasser nach dem Duschen abziehen.`],
 fehler:`Nur oberflächlich wischen und weiter falsch lüften — der Schimmel ist in wenigen Wochen zurück.`,
 sicherheit:`Chlorreiniger niemals mit anderen Reinigern mischen — es entstehen giftige Dämpfe. Immer gut lüften.`,
 profi:`Großflächiger Befall (mehr als ein DIN-A4-Blatt) oder Schimmel unter der Oberfläche: Ursache klären lassen — in der Mietwohnung Vermietersache.`,
 tipp:`Sitzt der Schimmel schwarz IN der Silikonfuge, hilft kein Schrubben mehr — dann die Fuge erneuern.`},

/* -- Küche & Geräte -- */
{id:"spuelmaschine",n:"Spülmaschine reinigt schlecht",kat:"kueche",zw:["pflege"],zeit:`20 Min.`,zeitMin:20,schwer:1,kosten:`0–8 €`,
 werkzeug:`Zahnstocher, alte Zahnbürste`,material:`Maschinenreiniger oder Zitronensäure`,
 schritte:[
  `Sieb am Boden herausdrehen und unter fließendem Wasser ausspülen.`,
  `Sprüharme abnehmen und verstopfte Düsen mit dem Zahnstocher freimachen.`,
  `Türdichtungen und Kanten feucht auswischen.`,
  `Einen leeren Heißlauf mit Maschinenreiniger oder zwei Esslöffeln Zitronensäure fahren.`,
  `Salz und Klarspüler auffüllen.`],
 fehler:`Immer teurere Tabs kaufen, statt einmal das Sieb zu reinigen.`,
 tipp:`Einmal im Monat das Sieb — das erledigt vier von fünf „spült schlecht“-Fällen.`},
{id:"kuehlschrank",n:"Kühlschrank pflegen & richtig einräumen",kat:"kueche",zw:["pflege","vorb"],zeit:`20–30 Min.`,zeitMin:20,schwer:1,kosten:`0 €`,
 werkzeug:`Handtücher, Schüssel`,material:``,
 schritte:[
  `Zonen nutzen: über dem Gemüsefach ist es am kältesten (Fleisch, Fisch), in der Tür am wärmsten (Getränke, Soßen).`,
  `7 °C im mittleren Fach genügen — jedes Grad kälter kostet spürbar Strom.`,
  `Türdichtung mit Spülwasser abwischen; Papiertest: Rutscht ein eingeklemmtes Blatt leicht heraus, schließt die Dichtung nicht mehr.`,
  `Gefrierfach abtauen, sobald Eis ansetzt: Gerät aus, Handtücher auslegen, Schüssel mit heißem Wasser hineinstellen.`],
 fehler:`Eis mit dem Messer abstoßen — ein Stich ins Kühlrohr ist der Totalschaden.`,
 tipp:`Schon fünf Millimeter Eis treiben den Verbrauch deutlich hoch — Abtauen zahlt sich in Strom aus.`},
{id:"backofen",n:"Backofen ohne Chemie reinigen",kat:"kueche",zw:["pflege"],zeit:`30 Min. + über Nacht`,zeitMin:30,schwer:1,kosten:`unter 5 €`,
 werkzeug:`Schwamm, Schüssel, ggf. Sprühflasche`,material:`Natron und Wasser (als Paste), Spülmittel`,
 schritte:[
  `Paste aus Natron und wenig Wasser anrühren und auf die eingebrannten Flächen streichen.`,
  `Über Nacht einwirken lassen, dann feucht abwischen.`,
  `Roste und Bleche in der Spüle mit heißem Wasser und einem Spülmaschinentab einweichen.`,
  `Bei vielen Modellen lässt sich die Ofentür zerlegen — so kommt man zwischen die Scheiben.`],
 fehler:`Scheuermittel und Stahlschwamm auf Emaille — Kratzer, in denen es künftig erst recht einbrennt.`,
 tipp:`Der sauberste Ofen ist der, der gar nicht schmutzig wird: Backpapier und Fettpfanne konsequent nutzen.`},
{id:"dunstabzug",n:"Dunstabzug: Fettfilter reinigen",kat:"kueche",zw:["pflege"],zeit:`15 Min.`,zeitMin:15,schwer:1,kosten:`0–20 €`,
 werkzeug:``,material:`Bei Umluft: neuer Aktivkohlefilter etwa alle 6 Monate`,
 schritte:[
  `Metall-Fettfilter entriegeln und herausnehmen.`,
  `Im Geschirrspüler im heißesten Programm mitwaschen oder in heißer Spülilauge einweichen.`,
  `Bei Umluftbetrieb den Aktivkohlefilter regelmäßig tauschen — er lässt sich nicht auswaschen.`,
  `Gehäuse und Rand feucht abwischen.`],
 fehler:`Den Filter jahrelang vergessen — er zieht nicht mehr ab, und gesättigtes Fett über dem Herd ist ein Brandrisiko.`,
 tipp:`Termin ins Handy: alle zwei Monate Filter in die Spülmaschine — er kommt wie neu heraus.`},
{id:"messer",n:"Messer schärfen",kat:"kueche",zw:["pflege"],zeit:`10 Min.`,zeitMin:10,schwer:2,kosten:`0–30 €`,
 werkzeug:`Wetzstahl oder Abziehstein (etwa 1000er-Körnung); einfacher: Durchziehschärfer`,material:``,
 schritte:[
  `Winkel halten: etwa 15 Grad zwischen Klinge und Stahl bzw. Stein.`,
  `Wetzstahl: die Klinge abwechselnd links und rechts mit leichtem Druck von der Wurzel zur Spitze ziehen.`,
  `Abziehstein vorher wässern und die Klinge in ruhigen, gleichmäßigen Bahnen abziehen.`,
  `Schärfe am Papierblatt testen: sauberer Schnitt ohne Reißen.`],
 fehler:`Messer lose in der Schublade lagern — die Klingen schlagen aneinander und stumpfen ab.`,
 sicherheit:`Immer vom Körper weg arbeiten und die Schneide nie quer mit dem Daumen testen.`,
 tipp:`Ein scharfes Messer ist das sicherere Messer: Es rutscht nicht ab, weil niemand drücken muss.`},

/* -- Wände, Böden & Möbel -- */
{id:"duebel",n:"Bohren & Dübeln: sicher aufhängen",kat:"waende",zw:["rep"],zeit:`30 Min.`,zeitMin:30,schwer:2,kosten:`5–15 €`,
 werkzeug:`Bohrmaschine (Beton: Schlagbohrer), passende Bohrer, Leitungssucher, Wasserwaage, Bleistift`,material:`Dübel passend zu Wandtyp und Last`,
 schritte:[
  `Wandtyp bestimmen: Klopfen — hohler Klang heißt Leichtbau (Gipskarton), dumpfer massives Mauerwerk.`,
  `Leitungen prüfen: Leitungssucher nutzen; Faustregel: Leitungen laufen senkrecht und waagerecht von Schaltern und Steckdosen weg.`,
  `Bohrerdurchmesser gleich Dübelgröße; Beton mit Schlag bohren, Fliesen ohne Schlag und mit Kreppband gegen Verrutschen.`,
  `In Gipskarton Hohlraum- oder Kippdübel setzen — nie Universaldübel für schwere Lasten.`,
  `Loch ausblasen, Dübel bündig einstecken, Schraube eindrehen.`],
 fehler:`Universaldübel in Gipskarton für den Hängeschrank — reißt aus.`,
 sicherheit:`Nie blind direkt über, unter oder neben Steckdosen und Schaltern bohren.`,
 profi:`Schwere Lasten an unklaren Wänden (Altbau, unbekannter Hohlwand-Aufbau) im Zweifel vom Fachbetrieb setzen lassen.`,
 tipp:`Ein gefaltetes Post-it als Fangschale unter dem Bohrloch fängt den Bohrstaub auf.`},
{id:"loecher",n:"Dübellöcher verschließen",kat:"waende",zw:["rep"],zeit:`15 Min. + Trocknung`,zeitMin:15,schwer:1,kosten:`5–10 €`,
 werkzeug:`Spachtel, feines Schleifpapier, Zange`,material:`Reparaturspachtel, etwas Wandfarbe`,
 schritte:[
  `Dübel entfernen: eine Schraube zwei Umdrehungen eindrehen und mit der Zange samt Dübel gerade herausziehen.`,
  `Loch entstauben und Spachtelmasse leicht überstehend eindrücken.`,
  `Trocknen lassen, plan schleifen, überstreichen.`],
 fehler:`Zahnpasta als „Spachtel“ — hält nicht, vergilbt und ärgert den Nachmieter.`,
 tipp:`Der Schrauben-Zieh-Trick holt jeden Dübel heraus, ohne die Wand aufzureißen.`},
{id:"streichen",n:"Wand streichen wie vom Profi",kat:"waende",zw:["rep"],zeit:`3–5 Std. pro Zimmer`,zeitMin:180,schwer:2,kosten:`40–80 €`,
 werkzeug:`Abdeckfolie, Kreppband, Farbrolle mit Teleskopstiel, Pinsel für Kanten, Abstreifgitter`,material:`Wandfarbe mit Deckkraftklasse 1–2; auf sandenden Wänden vorher Tiefengrund`,
 schritte:[
  `Löcher spachteln, Steckdosenrahmen abnehmen, Boden und Kanten sauber abkleben (Band fest andrücken).`,
  `Zuerst Ecken und Kanten mit dem Pinsel vorstreichen.`,
  `Dann mit der Rolle nass in nass: die Farbe quer verteilen und in einem Zug senkrecht abrollen.`,
  `Kreppband abziehen, solange die Farbe noch leicht feucht ist — im 45-Grad-Winkel.`],
 fehler:`Billigfarbe, die drei Anstriche braucht — gute Farbe einmal ist am Ende günstiger und schneller.`,
 tipp:`Rolle und Pinsel zwischen zwei Anstrichen luftdicht in eine Tüte wickeln — spart das Auswaschen.`},
{id:"kratzer",n:"Kratzer in Holz & Parkett kaschieren",kat:"waende",zw:["rep"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`0–15 €`,
 werkzeug:`Weiches Tuch`,material:`Retuschierstift oder Hartwachs im Holzton; für geölte Böden Pflegeöl`,
 schritte:[
  `Flache Kratzer in hellem Holz: mit einem Walnusskern einreiben — die Öle dunkeln die Stelle nach.`,
  `Geölte Böden: Stelle reinigen und hauchdünn nachölen.`,
  `Tiefe Kratzer: Hartwachs im passenden Ton einschmelzen, Überschuss abziehen, polieren.`],
 fehler:`Lackierte Böden ölen — das gibt dauerhafte Flecken statt einer Reparatur.`,
 profi:`Viele tiefe Kratzer auf großer Fläche: schleifen und neu versiegeln — Maschine leihen oder den Profi holen.`,
 tipp:`Jeden Farbton erst an verdeckter Stelle testen — Holztöne täuschen enorm.`},
{id:"quietscht",n:"Quietschende Tür",kat:"waende",zw:["rep"],zeit:`5 Min.`,zeitMin:5,schwer:1,kosten:`0–8 €`,
 werkzeug:`Tuch; ggf. Hebel zum Anheben der Tür`,material:`Silikonspray, technische Vaseline oder etwas Fett`,
 schritte:[
  `Tür leicht anheben und den Bandstift freilegen.`,
  `Stift und Band sparsam einsprühen oder einfetten.`,
  `Tür mehrmals bewegen und überschüssiges Mittel abwischen.`],
 fehler:`Speiseöl nehmen — es verharzt, zieht Staub an und quietscht bald wieder.`,
 tipp:`Ein Hauch Vaseline am Bandstift hält länger als jedes Spray.`},
{id:"schleift",n:"Tür schleift oder klemmt",kat:"waende",zw:["rep"],zeit:`20–30 Min.`,zeitMin:20,schwer:2,kosten:`0–5 €`,
 werkzeug:`Inbusschlüssel oder Schraubendreher, Kreide; ggf. Unterlegring für den Bandstift`,material:``,
 schritte:[
  `Schleifstelle finden: Türkante mit Kreide einreiben und schließen — der Abrieb am Rahmen markiert die Stelle.`,
  `Zuerst alle Bandschrauben nachziehen.`,
  `Moderne 3D-Bänder mit dem Inbus in Höhe und Seite justieren — vorher ein Foto vom Ist-Zustand machen.`,
  `Alte Bänder: Tür aushängen und einen Unterlegring auf den Bandstift legen.`],
 fehler:`Wahllos an allen Stellschrauben drehen — ohne Foto findet man nie zur Ausgangslage zurück.`,
 profi:`Ist das Türblatt selbst verzogen, gehört das Abhobeln in Schreinerhand.`,
 tipp:`Meist reicht eine Vierteldrehung am richtigen Band — erst justieren, nie gleich hobeln.`},
{id:"kleben",n:"Aufhängen ohne Bohren",kat:"waende",zw:["vorb"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`5–15 €`,
 werkzeug:``,material:`Klebenägel oder Klebestreifen nach Traglast; Spiritus zum Entfetten`,
 schritte:[
  `Untergrund prüfen: tragfähig, glatt, staub- und fettfrei (kurz mit Spiritus abwischen).`,
  `Die Traglastangabe ernst nehmen und Reserve einplanen.`,
  `Fest anpressen und die Wartezeit des Herstellers vor dem Belasten einhalten.`,
  `Zum Entfernen die Lasche langsam parallel zur Wand in die Länge ziehen — nie abreißen.`],
 fehler:`Auf Raufaser oder frischer Farbe ans Traglast-Limit gehen — der Streifen nimmt die Tapete mit.`,
 tipp:`Der lange Zug parallel zur Wand ist das ganze Geheimnis rückstandsfreier Klebehaken.`},

/* -- Strom & Licht -- */
{id:"sicherung",n:"Sicherung fliegt raus & FI-Schalter",kat:"strom",zw:["rep"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`0 €`,
 werkzeug:``,material:``,
 schritte:[
  `Im Sicherungskasten den gefallenen Automaten finden (Hebel unten oder in Mittelstellung).`,
  `Den wahrscheinlichen Verursacher trennen: das zuletzt eingeschaltete Gerät ausstecken.`,
  `Automat wieder einschalten. Fliegt er sofort erneut, ist das Gerät defekt oder die Leitung hat ein Problem.`,
  `Beim FI-Schalter (RCD): alle Geräte des Kreises trennen, FI setzen, Geräte nacheinander einstecken — der Übeltäter wirft ihn erneut.`],
 fehler:`Einen „stärkeren“ Automaten einbauen lassen wollen — die Sicherung schützt die Leitung, nicht das Gerät.`,
 sicherheit:`Mit nassen Händen bleibt der Verteilerkasten tabu. Sicherungen niemals festhalten oder überbrücken.`,
 profi:`Fliegt die Sicherung wiederholt ohne erkennbaren Verursacher: Elektriker rufen — Leitungsfehler sind Brandgefahr.`,
 tipp:`Die Prüftaste am FI zweimal im Jahr drücken — dieser Schalter rettet Leben, aber nur, wenn er funktioniert.`},
{id:"lampe",n:"Deckenlampe anschließen",kat:"strom",zw:["rep"],zeit:`30 Min.`,zeitMin:30,schwer:2,kosten:`5–10 €`,
 werkzeug:`Zweipoliger Spannungsprüfer, Schraubendreher, Steckklemmen (z. B. Wago), stabile Leiter`,material:``,
 schritte:[
  `Sicherung des Raums ausschalten und einen Zettel an den Kasten hängen.`,
  `Spannungsfreiheit an ALLEN Adern mit dem zweipoligen Prüfer testen — erst dann anfassen.`,
  `Foto von der alten Klemmung machen, dann abklemmen.`,
  `Anschließen: Braun oder Schwarz (L) auf L, Blau (N) auf N, Grün-Gelb (PE) an die Erdungsklemme der Lampe.`,
  `Steckklemmen statt alter Lüsterklemmen verwenden, Zugentlastung schließen — erst dann die Sicherung wieder rein.`],
 fehler:`Nur den Lichtschalter ausschalten — bei ungünstig verdrahteten Dosen liegt trotzdem Spannung an.`,
 sicherheit:`Ein Phasenprüfer-Schraubendreher genügt NICHT. Ohne zweipoligen Spannungsprüfer und sicheres Gefühl: Finger weg.`,
 profi:`Unklare Adernfarben, fehlender Schutzleiter, alte Anlage: Elektrofachkraft rufen — das ist keine Schande, sondern Vernunft.`,
 tipp:`Das Vorher-Foto der Klemmen erspart beim Anschließen jedes Rätselraten.`},

/* -- Heizen & Lüften -- */
{id:"entlueften",n:"Heizkörper entlüften",kat:"heizung",zw:["pflege"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`2–5 €`,
 werkzeug:`Entlüftungsschlüssel (Vierkant, Baumarkt), Becher, Tuch`,material:``,
 schritte:[
  `Thermostat voll aufdrehen; in der eigenen Anlage die Umwälzpumpe kurz ausschalten und das Wasser zur Ruhe kommen lassen.`,
  `Becher unter das Entlüftungsventil halten (oben, gegenüber dem Thermostat).`,
  `Ventil vorsichtig eine halbe Umdrehung öffnen — die Luft zischt heraus.`,
  `Sobald Wasser blasenfrei kommt, sofort schließen.`,
  `Eigene Anlage: Anlagendruck prüfen und bei Bedarf auf etwa 1,5 bar nachfüllen.`],
 fehler:`Das Ventil ganz herausdrehen — es kann herausschießen, und das Wasser kommt gleich mit.`,
 profi:`In der Mietwohnung sinkt nach dem Entlüften der Druck der Zentralanlage — kommt die Luft immer wieder, den Vermieter informieren statt wöchentlich zu entlüften.`,
 tipp:`Gluckern und „oben kalt, unten warm“ heißt Luft — zehn Minuten Arbeit für einen spürbar wärmeren Raum.`},
{id:"lueften",n:"Richtig lüften, Schimmel vorbeugen",kat:"heizung",zw:["vorb"],zeit:`3× täglich 5 Min.`,zeitMin:5,schwer:1,kosten:`0–10 €`,
 werkzeug:``,material:`Hygrometer (ca. 10 €) als Kontrolle`,
 schritte:[
  `Stoßlüften statt kippen: Fenster mehrmals täglich 3–5 Minuten weit öffnen, am besten mit Durchzug.`,
  `Nach dem Duschen und Kochen sofort lüften und die Tür zu kühleren Räumen schließen.`,
  `Möbel mit einer Handbreit Abstand zu Außenwänden stellen.`,
  `Luftfeuchte im Blick behalten: 40–60 % sind das Ziel.`],
 fehler:`Das Fenster im Winter dauerhaft kippen — es tauscht kaum Luft, kühlt aber die Laibung aus: die klassische Schimmelecke.`,
 tipp:`Ein Hygrometer für zehn Euro sagt dir schwarz auf weiß, wann Lüften wirklich nötig ist.`},
{id:"thermostat",n:"Thermostat verstehen, Heizkosten senken",kat:"heizung",zw:["vorb"],zeit:`5 Min.`,zeitMin:5,schwer:1,kosten:`0 €`,
 werkzeug:``,material:``,
 schritte:[
  `Die Stufen sind Zieltemperaturen, kein Tempo: Stufe 3 entspricht etwa 20 °C — Stufe 5 heizt nicht schneller, nur höher.`,
  `Nachts und bei Abwesenheit auf 17–18 °C absenken, nicht ganz aus.`,
  `Heizkörper freihalten — Sofa und langer Vorhang davor kosten bares Geld.`,
  `Klemmt das Ventil (Heizung bleibt kalt): Thermostatkopf abschrauben und den Metallstift vorsichtig gangbar machen.`],
 fehler:`Stufe 5 zum „Schnellheizen“ — der Raum wird nicht schneller warm, nur teurer.`,
 tipp:`Ein Grad weniger spart grob sechs Prozent Heizenergie.`},
{id:"dichtung",n:"Zugluft am Fenster stoppen",kat:"heizung",zw:["rep"],zeit:`20–30 Min.`,zeitMin:20,schwer:1,kosten:`5–15 €`,
 werkzeug:`Schere, Reinigungstuch; ggf. Inbus für die Rollzapfen`,material:`Selbstklebendes Dichtungsband (EPDM) in passender Stärke`,
 schritte:[
  `Leck finden mit dem Papiertest: Klemmt ein Blatt beim Schließen kaum, ist die Dichtung an der Stelle platt.`,
  `Alte, plattgedrückte Dichtung entfernen und den Falz gründlich reinigen.`,
  `Neues EPDM-Band ohne Zug in einem Stück einkleben, Ecken sauber stoßen.`,
  `Anpressdruck prüfen: Viele Fenster lassen sich an den Rollzapfen im Beschlag minimal nachstellen.`],
 fehler:`Billiges Schaumstoffband an bewegten Fenstern — das hält keinen Winter.`,
 profi:`Verzogene Flügel und Beschläge stellt der Fensterbauer in Minuten ein — in der Mietwohnung Sache des Vermieters.`,
 tipp:`Der Papiertest kostet nichts und findet jede müde Dichtung.`},

/* -- Wäsche & Textil -- */
{id:"waschmaschine",n:"Waschmaschine stinkt: das Pflegeprogramm",kat:"wasch",zw:["pflege"],zeit:`30 Min.`,zeitMin:30,schwer:1,kosten:`0–5 €`,
 werkzeug:`Flache Schale, Handtuch, alte Zahnbürste`,material:`Pulver-Vollwaschmittel oder Zitronensäure`,
 schritte:[
  `Flusensieb (Klappe unten): Handtuch auslegen, flache Schale unterstellen und ERST das Restwasser über den kleinen Schlauch ablassen.`,
  `Sieb herausdrehen, Fusseln und Fremdkörper (Münzen!) entfernen.`,
  `Waschmittelfach herausnehmen und mit der Bürste reinigen; die Gummifalte der Tür auswischen.`,
  `Einen leeren 60- oder 90-Grad-Waschgang mit Pulver-Vollwaschmittel fahren.`,
  `Tür und Fach danach immer offen stehen lassen.`],
 fehler:`Nur 30-Grad-Wäschen mit Flüssigwaschmittel — der Biofilm in der Maschine ist genau die Geruchsquelle.`,
 sicherheit:`Beim Flusensieb immer zuerst das Wasser ablassen — sonst steht die Küche unter Wasser.`,
 tipp:`Einmal im Monat heiß waschen hält Maschine und Wäsche dauerhaft frisch.`},
{id:"symbole",n:"Pflegesymbole entschlüsseln",kat:"wasch",zw:["vorb"],zeit:`5 Min.`,zeitMin:5,schwer:1,kosten:`0 €`,
 werkzeug:``,material:``,
 schritte:[
  `Wanne = Waschen; die Zahl ist die Höchsttemperatur, die Hand bedeutet Handwäsche.`,
  `Quadrat = Trocknen; der Kreis im Quadrat ist der Trockner — durchgestrichen heißt: niemals.`,
  `Punkte sind die Temperatur-Logik: ein Punkt schonend, zwei normal — beim Trockner wie beim Bügeleisen.`,
  `Dreieck = Bleichen; ein Kreis allein = professionelle Reinigung.`],
 fehler:`Den durchgestrichenen Trockner ignorieren — so entstehen Kindergrößen aus Lieblingspullis.`,
 tipp:`Die Punkte-Logik einmal verstanden, braucht man nie wieder eine Legende.`},
{id:"flecken",n:"Flecken: Erste Hilfe",kat:"wasch",zw:["rep"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`0–5 €`,
 werkzeug:``,material:`Gallseife, Spülmittel, Mineralwasser, Salz`,
 schritte:[
  `Sofort handeln und tupfen statt reiben — immer von außen nach innen.`,
  `Eiweißhaltiges (Blut, Ei) nur KALT behandeln — Wärme lässt es gerinnen und setzt den Fleck fest.`,
  `Fett mit einem Tropfen Spülmittel vorbehandeln, Rotwein mit Mineralwasser und Salz tupfen, Gras mit Gallseife.`,
  `Danach normal waschen — und erst in den Trockner, wenn der Fleck wirklich raus ist.`],
 fehler:`Heiß waschen oder trocknen, solange der Fleck sichtbar ist — Hitze fixiert ihn für immer.`,
 tipp:`Gallseife ist der Allrounder: Ein Stück ersetzt zehn Spezialmittel.`},

/* -- Sicherheit & Notfall -- */
{id:"wasserschaden",n:"Wasserschaden: die ersten Minuten",kat:"sicherheit",zw:["rep"],zeit:`sofort`,zeitMin:5,schwer:1,kosten:`0 €`,
 werkzeug:``,material:``,
 schritte:[
  `Wasser stoppen: Eckventil am Gerät zudrehen; reicht das nicht — Haupthahn (meist in Bad, Küche oder Keller).`,
  `Strom im betroffenen Bereich abschalten, bevor du in Wassernähe hantierst.`,
  `Wasser aufnehmen, Möbel hochstellen und alles mit Fotos dokumentieren.`,
  `Vermieter bzw. Verwaltung informieren, bei laufendem Wasser den Notdienst — und die Nachbarn darunter warnen.`],
 fehler:`Erst wischen, dann absperren — die falsche Reihenfolge kostet Liter um Liter.`,
 sicherheit:`Steht Wasser in der Nähe von Steckdosen oder Geräten: zuerst die Sicherung raus.`,
 profi:`Leitungen in der Wand sind Sache von Fachfirma bzw. Vermieter — als Mieter melden statt selbst beauftragen (außer bei Gefahr im Verzug).`,
 tipp:`Finde HEUTE deinen Haupthahn — im Ernstfall zählt jede Minute, und niemand sucht gern im Wasserstrahl.`},
{id:"rauchmelder",n:"Rauchmelder piept — was nun?",kat:"sicherheit",zw:["pflege"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`0–25 €`,
 werkzeug:`Staubsauger oder Tuch, ggf. Leiter`,material:`Ersatzbatterie bzw. neuer Melder bei fest verbauter 10-Jahres-Batterie`,
 schritte:[
  `Kurzes Piepen im Minutentakt heißt: Batterie schwach — tauschen bzw. das Gerät ersetzen, wenn die Batterie fest verbaut ist.`,
  `Prüftaste drücken, bis der Alarm ertönt — das testet Elektronik und Batterie in einem.`,
  `Gerät außen absaugen oder abwischen, damit Staub keine Fehlalarme auslöst.`,
  `Fehlalarm durch Wasserdampf: lüften und Stummtaste — den Melder deshalb nie abhängen.`],
 fehler:`Die Batterie „nur bis morgen“ herausnehmen — vergessen ist im Brandfall tödlich.`,
 profi:`In vielen Bundesländern wartet der Vermieter oder ein Dienstleister die Melder — eigenmächtig abbauen ist keine Option.`,
 tipp:`Das Batterie-Piepen kommt gern nachts um drei: beim Uhrenumstellen gleich die Batterien mit tauschen.`},
{id:"ausgesperrt",n:"Ausgesperrt — ohne Abzocke zurück in die Wohnung",kat:"sicherheit",zw:["vorb"],zeit:`variabel`,zeitMin:30,schwer:1,kosten:`0–120 €`,
 werkzeug:``,material:``,
 schritte:[
  `Erst die günstigen Wege: Mitbewohner, Partner oder Nachbar mit Zweitschlüssel? Hausverwaltung oder Notdienst des Vermieters?`,
  `Ist die Tür nur zugezogen (nicht abgeschlossen), öffnet ein seriöser Dienst sie in Minuten — tagsüber deutlich unter 100 Euro.`,
  `Nur einen LOKALEN Schlüsseldienst rufen (Adresse prüfen) und am Telefon einen Festpreis nennen lassen.`,
  `Vor Ort nichts Überteuertes unterschreiben und immer eine Rechnung verlangen.`],
 fehler:`Den erstbesten „Ab 15 €“-Treffer aus der Onlinewerbung rufen — solche Lockangebote enden dreistellig.`,
 tipp:`Deponiere heute einen Zweitschlüssel bei einer Vertrauensperson — die billigste Versicherung deines Lebens.`},
{id:"stromausfall",n:"Stromausfall systematisch prüfen",kat:"sicherheit",zw:["rep"],zeit:`10 Min.`,zeitMin:10,schwer:1,kosten:`0 €`,
 werkzeug:`Taschenlampe (Handy)`,material:``,
 schritte:[
  `Erst orten: Ist nur die eigene Wohnung dunkel? Treppenhauslicht und Nachbarn geben die Antwort.`,
  `Nur die eigene Wohnung: Sicherungskasten prüfen — gefallenen Automaten oder FI wieder einschalten und den Verursacher trennen.`,
  `Ganzes Haus oder Viertel: die Störungsnummer des NETZBETREIBERS anrufen — nicht die 112, die ist für Notfälle da.`,
  `Kühlschrank und Gefrierfach geschlossen halten; Kerzen nie unbeaufsichtigt lassen.`],
 fehler:`Bei einem Ausfall im ganzen Viertel panisch am eigenen Sicherungskasten schalten — dort liegt der Fehler nicht.`,
 tipp:`Speichere die Störungsnummer deines Netzbetreibers ins Handy — der Netzbetreiber hilft, nicht der Stromvertrieb.`}
];
