/* HeiBen — Lebensmittel-Wissen: richtig lagern, Frische erkennen, Reste retten.
   Datenbasis für lebensmittel.html. Schema je Eintrag:
   {id,n,kat,ort:"kuehl"|"raum"|"dunkel"|"gefrier",kuehlfalle(optional true),
    haltbar,mhd(opt),lagern,frisch,einfrieren(opt),trennen(opt),rest(opt),warn(opt),tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten. */

window.LM_KAT={obst:"Obst",gemuese:"Gemüse & Salat",milch:"Milchprodukte & Eier",fleisch:"Fleisch & Fisch",vorrat:"Vorrat & Trockenes",reste:"Gekochtes & Gefrorenes"};
window.LM_ORT={kuehl:"Kühlschrank",raum:"Raumtemperatur",dunkel:"Dunkel & kühl",gefrier:"Gefrierfach"};

window.LEBENSMITTEL=[
/* -- Obst -- */
{id:"aepfel",n:"Äpfel",kat:"obst",ort:"dunkel",
 haltbar:`Kühl und dunkel mehrere Wochen; bei Zimmertemperatur nur Tage, dann mehlig.`,
 lagern:`Am liebsten kühl, dunkel und luftig — Keller, Speisekammer oder das Gemüsefach. Druckstellen vermeiden, angeschlagene Früchte zuerst essen.`,
 frisch:`Schrumpelige Schale und mehliges Fruchtfleisch heißen: schnell verarbeiten. Braune Faulstellen großzügig wegschneiden, bei muffigem Geruch entsorgen.`,
 trennen:`Der Reifegas-Riese: Äpfel verströmen viel Ethylen und lassen Bananen, Salat und anderes Obst daneben rasant altern — getrennt lagern.`,
 rest:`Schrumpelige Äpfel sind perfekt für Apfelmus, Kompott oder Kuchen.`,
 tipp:`Ein einzelner Apfel gezielt zu unreifen Früchten gelegt wirkt umgekehrt als natürlicher Nachreife-Turbo.`},
{id:"bananen",n:"Bananen",kat:"obst",ort:"raum",kuehlfalle:true,
 haltbar:`Bei Zimmertemperatur je nach Reifegrad 3–7 Tage.`,
 lagern:`Aufgehängt oder liegend bei Zimmertemperatur, fern von anderem Obst. Im Kühlschrank wird die Schale schwarz und das Aroma leidet.`,
 frisch:`Braune Punkte auf der Schale sind Reife, kein Verderb — erst matschiges, gärig riechendes Fruchtfleisch gehört weg.`,
 trennen:`Bananen sind selbst starke Ethylen-Spender: Neben Äpfeln gelagert reifen sie doppelt so schnell.`,
 rest:`Ganz braune Bananen sind die süßesten: ideal für Bananenbrot, Pancakes oder — geschält eingefroren — für Smoothies und „Nicecream“.`,
 tipp:`Braun heißt nicht Tonne, sondern Backofen: Kaum ein Lebensmittel wird so unnötig weggeworfen wie die reife Banane.`},
{id:"beeren",n:"Beeren (Erdbeeren, Himbeeren & Co.)",kat:"obst",ort:"kuehl",
 haltbar:`Sehr empfindlich: 1–3 Tage im Kühlschrank.`,
 lagern:`Ungewaschen, trocken und flach nebeneinander im Kühlschrank — Feuchtigkeit und Druck sind ihre Feinde. Erst unmittelbar vor dem Essen waschen.`,
 frisch:`Eine schimmelige Beere steckt die Nachbarn an: sofort aussortieren. Matschige, gärig riechende Früchte entsorgen.`,
 einfrieren:`Sehr gut: einzeln auf einem Brett vorfrieren, dann in den Beutel — so kleben sie nicht zusammen.`,
 rest:`Kurz vorm Kippen? Ein kurzes Bad in Wasser mit einem Schuss Essig (3:1), abtrocknen — das bremst Schimmelsporen und schenkt 1–2 Tage.`,
 tipp:`Beeren niemals auf Vorrat waschen — Wasser auf der Schale halbiert die Haltbarkeit.`},
{id:"trauben",n:"Weintrauben",kat:"obst",ort:"kuehl",
 haltbar:`Im Kühlschrank etwa 1 Woche.`,
 lagern:`Ungewaschen in einer offenen Schale oder perforierten Tüte ins Gemüsefach; der weißliche Duftfilm ist natürlicher Schutz, kein Schmutz.`,
 frisch:`Schrumpelige oder vom Stiel fallende Beeren zügig essen; schimmelige Nester großzügig entfernen.`,
 einfrieren:`Gefrorene Trauben sind ein Sommer-Snack und kühlen Getränke, ohne sie zu verwässern.`,
 tipp:`Erst kurz vor dem Essen waschen — der Duftfilm hält die Trauben länger frisch.`},
{id:"zitrus",n:"Zitrusfrüchte",kat:"obst",ort:"raum",kuehlfalle:true,
 haltbar:`Bei kühler Raumtemperatur 1–2 Wochen und länger.`,
 lagern:`Luftig bei 10–15 °C, etwa in einer Schale im kühlen Flur — nicht in Plastik und nicht ins kälteste Kühlschrankfach, das kostet Saft und Aroma.`,
 frisch:`Weiche Stellen und weißer oder grüner Schimmel: aussortieren, bevor die ganze Schale ansteckt wird.`,
 rest:`Vor dem Auspressen kräftig rollen — das löst die Zellen und bringt spürbar mehr Saft.`,
 tipp:`Für Abrieb nur „unbehandelt/Bio“ kaufen — bei allen anderen ist die Schale gewachst und behandelt.`},
{id:"steinobst",n:"Steinobst (Pfirsich, Pflaume & Co.)",kat:"obst",ort:"raum",
 haltbar:`Zum Nachreifen 2–4 Tage bei Zimmertemperatur, reif dann 2–3 Tage im Kühlschrank.`,
 lagern:`Hartes Steinobst reift bei Zimmertemperatur nach (schneller in der Papiertüte). Erst wenn es duftet und leicht nachgibt, in den Kühlschrank.`,
 frisch:`Duftet es süß und gibt auf Daumendruck minimal nach, ist es perfekt. Gärgeruch und braune Matschstellen heißen: sofort verwerten oder weg.`,
 trennen:`Reifes Steinobst gibt Ethylen ab — nicht neben empfindlichem Gemüse lagern.`,
 einfrieren:`Entsteint und geviertelt gut einzufrieren — ideal für Kompott und Kuchen.`,
 tipp:`Steinfrüchte mit der Schulter nach unten lagern — so drücken sie sich nicht gegenseitig matschig.`},
{id:"avocado",n:"Avocado",kat:"obst",ort:"raum",kuehlfalle:true,
 haltbar:`Unreif mehrere Tage bei Zimmertemperatur; reif hält sie im Kühlschrank noch 2–3 Tage.`,
 lagern:`Unreife Avocados reifen nur bei Zimmertemperatur — der Kühlschrank stoppt die Reifung dauerhaft. Erst die reife Frucht wandert ins Gemüsefach.`,
 frisch:`Reif ist sie, wenn sie auf sanften Druck leicht nachgibt und der Stielansatz sich grün löst. Faserig-braunes Fruchtfleisch großflächig: entsorgen.`,
 trennen:`Reife-Trick: zusammen mit Apfel oder Banane in eine Papiertüte — das Ethylen macht sie in 1–2 Tagen weich.`,
 rest:`Angeschnittene Hälfte mit Zitronensaft beträufeln und luftdicht abdecken — das bremst das Braunwerden wirklich (der Kern in der Schüssel ist ein Mythos).`,
 tipp:`Steinhart gekauft ist normal: Avocados reifen grundsätzlich erst nach der Ernte.`},
{id:"melone",n:"Melone",kat:"obst",ort:"raum",kuehlfalle:true,
 haltbar:`Ganz mehrere Tage bis Wochen bei Raumtemperatur; angeschnitten 2–3 Tage gekühlt.`,
 lagern:`Ganze Melonen gehören nicht in den Kühlschrank — sie verlieren Aroma. Erst die angeschnittene Melone abgedeckt kalt stellen.`,
 frisch:`Reife Wassermelone klingt beim Klopfen dunkel und hohl und hat einen gelben Bodenfleck. Gäriger Geruch an der Schnittfläche: weg damit.`,
 warn:`Auf der süßen, feuchten Schnittfläche vermehren sich Keime rasant — angeschnittene Melone immer abdecken, kühlen und binnen 2–3 Tagen essen.`,
 tipp:`Der gelbe „Liegefleck“ ist kein Makel, sondern das beste Reifezeichen der Wassermelone.`},

/* -- Gemüse & Salat -- */
{id:"tomaten",n:"Tomaten",kat:"gemuese",ort:"raum",kuehlfalle:true,
 haltbar:`Bei Zimmertemperatur bis zu 1 Woche.`,
 lagern:`Bei Zimmertemperatur, mit dem Strunk nach unten und nicht in Plastik. Im Kühlschrank verlieren Tomaten ihr Aroma und werden mehlig.`,
 frisch:`Runzelige Haut ist nur Wasserverlust — ab in die Soße. Schimmel am Strunk oder gärige Stellen: entsorgen.`,
 trennen:`Tomaten verströmen Ethylen — Gurken und Salat daneben altern deutlich schneller.`,
 rest:`Weiche Tomaten sind Soßen-Gold: kurz einritzen, überbrühen, häuten, einkochen.`,
 tipp:`Die Kühlschrank-Tomate ist der Klassiker unter den Lagerfehlern — Aroma kommt bei Kälte nie zurück.`},
{id:"kartoffeln",n:"Kartoffeln",kat:"gemuese",ort:"dunkel",kuehlfalle:true,
 haltbar:`Dunkel und kühl gelagert viele Wochen bis Monate.`,
 lagern:`Dunkel, kühl (nicht eiskalt) und luftig — Jutesack, Karton oder Kiste im Keller. Licht macht sie grün, der Kühlschrank macht sie unangenehm süßlich.`,
 frisch:`Kleine Keime und grüne Stellen großzügig wegschneiden. Stark gekeimte, schrumpelige oder großflächig grüne Knollen entsorgen.`,
 warn:`Grüne Stellen und Keime enthalten Solanin — großzügig entfernen; Kochen zerstört es nicht.`,
 trennen:`Nicht neben Zwiebeln lagern — beide verderben schneller. Ein Apfel dazwischen dagegen verzögert das Keimen spürbar.`,
 tipp:`Der Apfel-Trick funktioniert wirklich: Sein Reifegas hält Kartoffeln vom Austreiben ab.`},
{id:"zwiebeln",n:"Zwiebeln & Knoblauch",kat:"gemuese",ort:"dunkel",kuehlfalle:true,
 haltbar:`Trocken und dunkel mehrere Wochen bis Monate.`,
 lagern:`Trocken, dunkel und luftig — Netz oder offener Korb, nie Plastik oder Kühlschrank: Dort ziehen sie Feuchtigkeit, schimmeln und treiben aus.`,
 frisch:`Weiche Stellen, grauer Schimmel unter der Schale oder muffiger Geruch: entsorgen. Ein grüner Trieb ist essbar, kostet aber Aroma.`,
 trennen:`Von Kartoffeln fernhalten — deren Feuchtigkeit lässt Zwiebeln faulen.`,
 rest:`Angeschnittene Zwiebel in einer Dose im Kühlschrank binnen 1–2 Tagen verbrauchen.`,
 tipp:`Rote Zwiebeln und Frühlingszwiebeln sind die Ausnahme: Sie halten kurzfristig auch im Gemüsefach.`},
{id:"moehren",n:"Möhren",kat:"gemuese",ort:"kuehl",
 haltbar:`Im Gemüsefach 2–3 Wochen.`,
 lagern:`Das Grün sofort abdrehen — es zieht Wasser aus der Wurzel. Dann in Box oder feuchtem Tuch ins Gemüsefach.`,
 frisch:`Gummiartig weich ist nur Wasserverlust, kein Verderb. Schmierige Haut oder schwarze Stellen: weg damit.`,
 einfrieren:`Geschält, in Stücken und kurz blanchiert sehr gut einzufrieren.`,
 rest:`Schlappe Möhren werden in einem Glas Eiswasser über Nacht wieder knackig.`,
 tipp:`Das Bund-Grün ist der heimliche Frischekiller — abdrehen verlängert die Haltbarkeit um Wochen.`},
{id:"salat",n:"Blattsalat",kat:"gemuese",ort:"kuehl",
 haltbar:`Kopfsalat 2–4 Tage, feste Sorten wie Eisberg bis zu 1 Woche.`,
 lagern:`In ein leicht feuchtes Tuch gewickelt oder in einer Box mit Küchenpapier ins Gemüsefach — das Papier fängt Kondenswasser ab.`,
 frisch:`Welke Blätter sind nur schlapp, glitschig-braune sind hinüber: Betroffene Blätter entfernen, den Rest zügig essen.`,
 trennen:`Sehr ethylen-empfindlich: nicht neben Äpfel oder Tomaten legen, sonst gibt es braune Flecken.`,
 rest:`Welker (nicht verdorbener) Salat wird in Eiswasser binnen 30 Minuten wieder knackig.`,
 tipp:`Erst kurz vor dem Essen anmachen — Dressing lässt jeden Salat in Minuten zusammenfallen.`},
{id:"gurke",n:"Gurke",kat:"gemuese",ort:"kuehl",
 haltbar:`Im Gemüsefach etwa 1 Woche.`,
 lagern:`Gurken mögen es kühl, aber nicht eiskalt: Das Gemüsefach ist richtig, das kälteste Fach lässt sie glasig werden. Die Folienhülle der Salatgurke dranlassen.`,
 frisch:`Weiche, glasige oder gelbe Stellen und schmierige Enden: großzügig wegschneiden oder entsorgen.`,
 trennen:`Empfindlich gegenüber Ethylen — Abstand zu Tomaten, Äpfeln und Bananen.`,
 tipp:`Angeschnittene Gurke mit der Schnittfläche nach unten auf einen Teller stellen — hält ohne Folie frisch.`},
{id:"paprika",n:"Paprika",kat:"gemuese",ort:"kuehl",
 haltbar:`Im Gemüsefach 1–2 Wochen.`,
 lagern:`Ins Gemüsefach, ohne Plastikbeutel — Kondenswasser fördert Fäulnis. Paprika mag es kühl, aber nicht eisig.`,
 frisch:`Runzelige Haut heißt nur: bald verarbeiten. Weiche, nässende Stellen oder Schimmel am Strunk: weg.`,
 einfrieren:`Roh in Streifen geschnitten problemlos einzufrieren — perfekt für Pfannengerichte.`,
 tipp:`Rot, gelb, grün ist dieselbe Frucht in drei Reifegraden — rote sind am süßesten und vitaminreichsten.`},
{id:"pilze",n:"Pilze",kat:"gemuese",ort:"kuehl",
 haltbar:`2–4 Tage im Kühlschrank.`,
 lagern:`In der Papiertüte oder offenen Schale ins Gemüsefach — niemals in Plastik, dort schwitzen und schmieren sie.`,
 frisch:`Trockene Druckstellen sind harmlos, schmierige Häute und stechender Geruch nicht: dann entsorgen.`,
 rest:`Pilze nicht waschen, nur abbürsten oder mit feuchtem Tuch abreiben — sie saugen sich sonst voll.`,
 tipp:`Gegen Erdreste reicht der Backpinsel — Wasser ruiniert die Konsistenz.`},
{id:"kraeuter",n:"Frische Kräuter (Basilikum & Co.)",kat:"gemuese",ort:"raum",kuehlfalle:true,
 haltbar:`Basilikum im Wasserglas mehrere Tage; robuste Kräuter im feuchten Tuch bis 1 Woche gekühlt.`,
 lagern:`Basilikum ist kälteempfindlich: wie ein Blumenstrauß ins Wasserglas bei Zimmertemperatur. Petersilie, Schnittlauch und Koriander dagegen ins feuchte Tuch im Kühlschrank.`,
 frisch:`Schwarze, matschige Blätter aussortieren; leicht welke Kräuter in Eiswasser auffrischen.`,
 einfrieren:`Gehackt in Eiswürfelformen mit etwas Wasser oder Öl — portionsweise Würze für Monate.`,
 tipp:`Der Kräuter-Eiswürfel schlägt jedes getrocknete Töpfchen — Aroma wie frisch, immer griffbereit.`},

/* -- Milchprodukte & Eier -- */
{id:"milch",n:"Milch",kat:"milch",ort:"kuehl",
 haltbar:`Geöffnet etwa 3 Tage; ungeöffnete H-Milch monatelang.`,
 mhd:`Das MHD ist ein Frische-Versprechen, kein Wegwerfdatum — ungeöffnete Milch hält oft Tage darüber hinaus. Nase und Auge entscheiden.`,
 lagern:`Nicht ins Türfach! Dort schwankt die Temperatur bei jedem Öffnen — Milch gehört in die kalte Mitte oder nach unten.`,
 frisch:`Säuerlicher Geruch und Flocken beim Eingießen: hinüber. Frisch geöffnete H-Milch neutral riechend: unbedenklich.`,
 tipp:`Das Türfach ist der wärmste Ort im Kühlschrank — ausgerechnet dort steht bei den meisten die Milch.`},
{id:"joghurt",n:"Joghurt & Quark",kat:"milch",ort:"kuehl",
 haltbar:`Ungeöffnet oft 1–2 Wochen über das MHD hinaus.`,
 mhd:`Der MHD-Klassiker: Ungeöffneter Joghurt ist fast immer weit über das Datum hinaus einwandfrei. Prüfen statt wegwerfen.`,
 lagern:`Gut gekühlt lagern; angebrochene Becher abgedeckt binnen 2–3 Tagen verbrauchen.`,
 frisch:`Gewölbter Deckel, Schimmelpunkte oder hefig-gäriger Geschmack: entsorgen. Abgesetzte Molke oben ist dagegen völlig normal — einfach unterrühren.`,
 tipp:`Die Wasserschicht auf dem Joghurt ist Molke voller Eiweiß — unterrühren, nicht abgießen.`},
{id:"kaese",n:"Käse",kat:"milch",ort:"kuehl",
 haltbar:`Hartkäse mehrere Wochen, Weichkäse etwa 1 Woche nach Anbruch.`,
 lagern:`In Käse- oder Butterbrotpapier statt luftdichter Folie — Käse muss atmen, sonst schwitzt er und schimmelt schneller.`,
 frisch:`Bei Hartkäse einzelne Schimmelstellen großzügig (gut 2 cm) wegschneiden. Weichkäse, Frischkäse und geriebener Käse mit Schimmel: komplett entsorgen.`,
 einfrieren:`Hartkäse gerieben einfrieren — perfekt zum Überbacken direkt aus dem Fach.`,
 rest:`Harte Kanten und Reste mitkochen: Sie geben Suppen und Soßen Würze, die Parmesanrinde ist ein Klassiker im Sugo.`,
 tipp:`Frischhaltefolie ist der falsche Freund des Käses — Papier hält ihn Wochen länger gut.`},
{id:"butter",n:"Butter",kat:"milch",ort:"kuehl",
 haltbar:`Gekühlt mehrere Wochen; die kleine Portion in der Butterdose einige Tage bei Zimmertemperatur.`,
 lagern:`Vorrat gut verpackt in den Kühlschrank — Butter nimmt Fremdgerüche an. Die Wochenration darf in eine geschlossene Butterdose auf den Tisch.`,
 frisch:`Ranziger Geruch und ein dunklerer, glasiger Rand: Diesen Rand abschaben oder die Butter entsorgen.`,
 einfrieren:`Butter lässt sich monatelang einfrieren — Angebote lohnen sich.`,
 tipp:`Streichzart ohne Mikrowelle: die Tagesration in der Keramikdose, der Rest bleibt kalt.`},
{id:"eier",n:"Eier",kat:"milch",ort:"kuehl",
 haltbar:`Etwa 4 Wochen ab Legedatum; danach nur noch gut durcherhitzt verwenden.`,
 mhd:`Das MHD liegt 28 Tage nach dem Legen. Danach nicht automatisch schlecht — aber roh (Tiramisu, Mayonnaise) nur ganz frische Eier verwenden.`,
 lagern:`Einmal gekühlt, immer gekühlt: Zu Hause gehören Eier in den Kühlschrank, mit der Spitze nach unten und fern von Geruchsquellen.`,
 frisch:`Schwimmtest: Liegt das Ei im Wasserglas, ist es frisch; steht es auf, ist es alt (durcherhitzen); schwimmt es oben, entsorgen. Endgültig entscheidet die Nase am aufgeschlagenen Ei.`,
 warn:`Alte oder beschädigte Eier nie roh verzehren — Salmonellengefahr. Im Zweifel gut durcherhitzen.`,
 tipp:`Das aufsteigende Ei ist nicht „schlecht“, sondern alt — als hartgekochtes Ei oder im Kuchen völlig in Ordnung.`},

/* -- Fleisch & Fisch -- */
{id:"fleisch",n:"Frisches Fleisch",kat:"fleisch",ort:"kuehl",
 haltbar:`Je nach Art 1–3 Tage an der kältesten Stelle.`,
 mhd:`Auf Fleisch steht meist ein VERBRAUCHSdatum — und das ist, anders als das MHD, eine harte Grenze: danach entsorgen.`,
 lagern:`Ausgepackt oder in der Originalverpackung auf einem Teller an die kälteste Stelle (über dem Gemüsefach). Tropfsaft darf nichts anderes berühren.`,
 frisch:`Graue Färbung allein ist kein Alarm — schmierige Oberfläche und süßlich-stechender Geruch sind es: dann entsorgen.`,
 einfrieren:`Portioniert und luftdicht 3–12 Monate (fettes Fleisch kürzer). Im Kühlschrank auftauen, nie bei Zimmertemperatur.`,
 tipp:`Fleisch immer ganz unten im Kühlschrank lagern — so tropft nie etwas auf verzehrfertige Lebensmittel.`},
{id:"hack",n:"Hackfleisch",kat:"fleisch",ort:"kuehl",
 haltbar:`Der empfindlichste Frischkauf: am Kauftag verbrauchen.`,
 mhd:`Verbrauchsdatum strikt einhalten — bei Hackfleisch gibt es keinen Spielraum.`,
 lagern:`Sofort nach dem Einkauf an die kälteste Stelle; die Kühlkette so kurz wie möglich unterbrechen (Kühltasche im Sommer).`,
 frisch:`Grau-glänzend, schmierig oder säuerlich riechend: entsorgen, nicht „durchbraten und hoffen“.`,
 warn:`Durch die große Oberfläche vermehren sich Keime in Hack rasant — es ist das heikelste frische Lebensmittel im Kühlschrank.`,
 einfrieren:`Am Kauftag flach gedrückt einfrieren — flache Pakete tauen schnell und gleichmäßig auf.`,
 tipp:`Hack flach wie eine Tafel einfrieren: schneller gefroren, in Minuten aufgetaut, bricht portionsweise.`},
{id:"fisch",n:"Frischer Fisch",kat:"fleisch",ort:"kuehl",
 haltbar:`Am Kauftag, spätestens am Folgetag verbrauchen.`,
 lagern:`So kalt wie möglich: an der kältesten Stelle, ideal in einer Schale auf Eis oder Kühlakku.`,
 frisch:`Frischer Fisch riecht nach Meer, nicht nach „Fisch“: klare Augen, rote Kiemen, festes Fleisch. Stechender Geruch: entsorgen.`,
 einfrieren:`Sehr frisch gut einzufrieren; schonend im Kühlschrank auftauen.`,
 tipp:`Der Geruchstest ist beim Fisch unbestechlich — riecht er streng, hilft auch Braten nicht mehr.`},
{id:"aufschnitt",n:"Wurst & Aufschnitt",kat:"fleisch",ort:"kuehl",
 haltbar:`Geöffnet 3–4 Tage.`,
 lagern:`Angebrochene Packungen in eine Dose umlagern und ins kalte Fach — die aufgerissene Folie schützt nicht.`,
 frisch:`Schmieriger Glanz, milchiger Belag oder säuerlicher Geruch: weg damit. Angetrocknete Ränder bei Salami sind dagegen harmlos.`,
 einfrieren:`Aufschnitt lässt sich portionsweise (mit Backpapier zwischen den Scheiben) gut einfrieren.`,
 tipp:`Backpapier zwischen die Scheiben legen — dann lassen sich einzelne Portionen gefroren abnehmen.`},

/* -- Vorrat & Trockenes -- */
{id:"brot",n:"Brot",kat:"vorrat",ort:"raum",kuehlfalle:true,
 haltbar:`Mischbrot 3–5 Tage, Vollkorn bis 1 Woche, Weißbrot 1–2 Tage.`,
 lagern:`Bei Zimmertemperatur im Brotkasten oder Steinguttopf, Schnittfläche nach unten. Der Kühlschrank macht Brot am schnellsten altbacken.`,
 frisch:`Altbacken ist kein Verderb — Schimmel schon: Bei Schimmelstellen das ganze Brot entsorgen, das Geflecht sitzt unsichtbar tiefer.`,
 einfrieren:`Der beste Brot-Speicher: in Scheiben einfrieren und einzeln im Toaster auffrischen — wie frisch gebacken.`,
 rest:`Altbackenes Brot wird zu Croutons, Semmelbröseln, Arme Rittern oder kurz befeuchtet im Ofen wieder knusprig.`,
 tipp:`In Scheiben einfrieren statt gähnen lassen: Toast-Taste drücken und das Brot ist besser als am zweiten Tag aus dem Kasten.`},
{id:"mehl",n:"Mehl, Reis & Nudeln",kat:"vorrat",ort:"dunkel",
 haltbar:`Trocken gelagert weit über das MHD hinaus — oft Jahre.`,
 mhd:`Trockene Vorräte „verderben“ kaum, sie altern: Nach dem MHD leidet höchstens das Aroma. Prüfen statt wegwerfen.`,
 lagern:`Kühl, trocken und vor allem LUFTDICHT in Gläsern oder Dosen — das hält Lebensmittelmotten draußen.`,
 frisch:`Gespinste, Klümpchen oder krabbelnde „Mitbewohner“: betroffene Packung entsorgen und den Schrank auswischen. Muffiger Geruch bei Vollkorn: ranzig.`,
 tipp:`Einmal Motten im Haus? Neue Vorräte konsequent in Schraubgläser umfüllen — Papiertüten sind für Motten keine Hürde.`},
{id:"oel",n:"Speiseöle",kat:"vorrat",ort:"dunkel",kuehlfalle:true,
 haltbar:`Ungeöffnet 1–2 Jahre, geöffnet einige Monate.`,
 lagern:`Dunkel, kühl und fest verschlossen — Licht und Luft machen Öl ranzig. Olivenöl gehört nicht in den Kühlschrank: Es flockt (harmlos, aber unnötig).`,
 frisch:`Ranziges Öl riecht muffig-kratzig wie alte Nüsse und schmeckt bitter — dann entsorgen, es liefert nur noch schlechte Fette.`,
 tipp:`Natives Öl in der Klarglasflasche neben dem Herd ist doppelt falsch: Licht plus Wärme — dunkle Flasche, dunkler Schrank.`},
{id:"gewuerze",n:"Gewürze",kat:"vorrat",ort:"dunkel",
 haltbar:`Ganz mehrere Jahre, gemahlen etwa 1 Jahr volles Aroma.`,
 mhd:`Gewürze werden nicht „schlecht“, sondern fade — das MHD ist hier reine Aromagarantie.`,
 lagern:`Dunkel, trocken und fest verschlossen — und nicht direkt über dem dampfenden Herd, wo Wärme und Feuchte das Aroma killen.`,
 frisch:`Riecht ein Gewürz nach nichts, würzt es auch nach nichts — großzügiger dosieren oder ersetzen. Verklumpt und muffig: entsorgen.`,
 tipp:`Ganze Gewürze kaufen und frisch mörsern — Pfefferkörner halten Jahre, gemahlener Pfeffer schmeckt nach Monaten wie Staub.`},
{id:"honig",n:"Honig",kat:"vorrat",ort:"raum",kuehlfalle:true,
 haltbar:`Praktisch unbegrenzt.`,
 mhd:`Honig ist das MHD-Kuriosum: Richtig gelagert hält er quasi ewig — das aufgedruckte Datum ist reine Formsache.`,
 lagern:`Dunkel, trocken und fest verschlossen bei Zimmertemperatur. Kein Kühlschrank — dort kristallisiert er nur schneller.`,
 frisch:`Kristallisierter Honig ist NICHT schlecht: im Wasserbad bei maximal 40 °C sanft wieder verflüssigen.`,
 warn:`Kein Honig für Säuglinge unter einem Jahr — er kann Sporen enthalten, die für Babys gefährlich sind (Säuglingsbotulismus).`,
 tipp:`Fest geworden heißt naturbelassen, nicht verdorben — das Wasserbad macht ihn wieder golden.`},
{id:"konserven",n:"Konserven & Gläser",kat:"vorrat",ort:"dunkel",
 haltbar:`Meist Jahre über das MHD hinaus.`,
 mhd:`Unversehrte Konserven gehören zu den haltbarsten Lebensmitteln überhaupt — das MHD ist hier sehr konservativ.`,
 lagern:`Kühl, trocken, dunkel; geöffnete Dosen umfüllen und wie Frischware behandeln.`,
 frisch:`Zischt es beim Öffnen falsch herum (Überdruck), schäumt oder riecht der Inhalt untypisch: sofort entsorgen.`,
 warn:`Gewölbte Deckel oder aufgeblähte Dosen (Bombage) niemals probieren — Gefahr gefährlicher Keime. Tiefe Dellen an der Naht: ebenfalls weg.`,
 tipp:`Der Deckel-Check am Glas: Ploppt der Knopf beim Öffnen hoch, war das Vakuum intakt — bestes Zeichen.`},
{id:"kaffee",n:"Kaffee",kat:"vorrat",ort:"dunkel",kuehlfalle:true,
 haltbar:`Ganze Bohnen einige Wochen nach Anbruch voll aromatisch, gemahlen deutlich kürzer.`,
 lagern:`Luftdicht, dunkel und trocken bei Zimmertemperatur. Nicht in den Kühlschrank: Kondenswasser und Fremdgerüche ruinieren das Aroma.`,
 frisch:`Kaffee verdirbt kaum, er verduftet — riecht das Pulver flach und pappig, ist das Aroma dahin.`,
 tipp:`Bohnen erst direkt vor dem Brühen mahlen — gemahlener Kaffee verliert sein Aroma in Tagen, Bohnen halten Wochen.`},

/* -- Gekochtes & Gefrorenes -- */
{id:"restekochen",n:"Gekochte Reste",kat:"reste",ort:"kuehl",
 haltbar:`Abgedeckt im Kühlschrank 2–3 Tage.`,
 lagern:`Reste binnen zwei Stunden abkühlen lassen und abgedeckt in den Kühlschrank — große Mengen flach umfüllen, dann kühlen sie schneller durch.`,
 frisch:`Saurer Geruch, Bläschen oder Schimmelpunkte: entsorgen. Beim Aufwärmen einmal richtig durcherhitzen, nicht nur lauwarm machen.`,
 einfrieren:`Fast alle Gerichte lassen sich portionsweise einfrieren — beschriften nicht vergessen.`,
 tipp:`„Einmal heiß, nicht dreimal lauwarm“: Reste nur einmal wieder aufwärmen — und dann richtig.`},
{id:"reis",n:"Gekochter Reis",kat:"reste",ort:"kuehl",
 haltbar:`Maximal 1 Tag im Kühlschrank.`,
 lagern:`Reisreste so schnell wie möglich abkühlen (flach ausbreiten) und sofort kühlen — nicht stundenlang im Topf stehen lassen.`,
 frisch:`Riecht der Reis säuerlich oder ist er schmierig: weg. Beim Aufwärmen dampfend heiß werden lassen.`,
 warn:`Reis kann Sporen von Bacillus cereus enthalten, die das Kochen überleben und bei Zimmertemperatur Giftstoffe bilden — deshalb: schnell kühlen, nur 1 Tag lagern, kräftig durcherhitzen.`,
 tipp:`Gebratener Reis gelingt sogar am besten mit dem gekühlten Reis von gestern — genau dafür ist er da.`},
{id:"einfrieren",n:"Richtig einfrieren",kat:"reste",ort:"gefrier",
 haltbar:`Je nach Lebensmittel 1–12 Monate; Gefrierbrand ist unschön, aber ungefährlich.`,
 lagern:`Portionsweise, möglichst flach und luftarm verpacken, immer mit Inhalt und Datum beschriften. Heißes erst abkühlen lassen.`,
 frisch:`Weiß-trockene Stellen sind Gefrierbrand: kein Gesundheitsrisiko, nur Qualitätsverlust — großzügig wegschneiden.`,
 rest:`Nicht einfrieren: rohe Kartoffeln, Blattsalat und sehr wasserreiches rohes Gemüse — sie werden matschig. Blanchieren löst das Problem bei vielen Sorten.`,
 tipp:`Flach gefroren ist doppelt gewonnen: schneller durchgefroren, in Minuten aufgetaut, platzsparend gestapelt.`},
{id:"auftauen",n:"Sicher auftauen",kat:"reste",ort:"kuehl",
 haltbar:`Aufgetautes zügig verarbeiten und nicht roh wieder einfrieren.`,
 lagern:`Die sichere Methode: über Nacht abgedeckt im Kühlschrank auftauen. Schneller geht es im kalten Wasserbad im dichten Beutel — nie stundenlang warm auf der Fensterbank.`,
 frisch:`Einmal Aufgetautes durchgegart darf wieder eingefroren werden; roh wieder einfrieren ist tabu.`,
 warn:`Tauwasser von Geflügel sofort wegschütten und alles, was es berührt hat, heiß abwaschen — Salmonellengefahr.`,
 tipp:`„Auftauen bei Zimmertemperatur“ ist die Keim-Einladung schlechthin — der Kühlschrank braucht länger, ist aber der einzig saubere Weg.`}
];
