/* HeiBen — Ordnung im Papierkram: aufbewahren, kündigen, entsorgen.
   Datenbasis für papierkram.html. Schema je Eintrag:
   {id,n,kat,typ:"lebenslang"|"jahre"|"laufend",dauer:`Klartext`,warum,ablage,digital,
    entsorgen(opt),frist(opt: Kündigungs-/Handlungsfrist),warn(opt),tipp}
   Alle Texte in Backticks. Nur ans Ende ergänzen; ids stabil halten.
   Rechtsangaben bewusst konservativ formuliert („in der Regel", „meist"). */

window.PK_KAT={geld:"Geld & Steuern",wohnen:"Wohnen & Energie",vertraege:"Verträge & Abos",versicherung:"Versicherungen",arbeit:"Arbeit & Rente",familie:"Familie & fürs Leben"};
window.PK_TYP={lebenslang:"Lebenslang",jahre:"Mehrere Jahre",laufend:"Solange es läuft"};

window.PAPIERKRAM=[
/* -- Geld & Steuern -- */
{id:"kontoauszuege",n:"Kontoauszüge",kat:"geld",typ:"jahre",dauer:`3 Jahre (empfohlen)`,
 warum:`Beweis für Zahlungen: Miete, Kaufpreise, Rückzahlungen. Die regelmäßige Verjährung vieler Ansprüche beträgt drei Jahre — so lange sollte der Nachweis greifbar sein.`,
 ablage:`Ein Ordner „Bank“, chronologisch — oder das elektronische Postfach der Bank konsequent nutzen.`,
 digital:`Scan oder PDF aus dem Online-Banking reicht im Alltag völlig. Achtung: Viele Banken stellen alte Auszüge nur begrenzt bereit — rechtzeitig herunterladen.`,
 entsorgen:`Nach Ablauf schreddern, nie in den Papiermüll — Name, IBAN und Umsätze sind ein Identitätsdiebstahl-Buffet.`,
 tipp:`Einmal im Jahr alle PDF-Auszüge herunterladen und in einen Jahresordner legen — fünf Minuten, die Jahre absichern.`},
{id:"steuerbescheid",n:"Steuerbescheide & Steuererklärungen",kat:"geld",typ:"lebenslang",dauer:`Dauerhaft (empfohlen)`,
 warum:`Bescheide belegen Einkommen und gezahlte Steuern — wichtig für Rente, Elterngeld, Kredite und spätere Rückfragen. Belege zur Erklärung braucht es, bis der Bescheid endgültig (bestandskräftig) ist.`,
 ablage:`Ordner „Steuern“, ein Register pro Jahr: Bescheid vorn, Erklärung und Belege dahinter.`,
 digital:`Bescheide kommen zunehmend digital (ELSTER) — als PDF sichern reicht. Eingereichte Belege nach Bestandskraft nur noch bei „Vorbehalt der Nachprüfung“ aufheben.`,
 tipp:`Der Steuerbescheid ist dein amtlicher Einkommensnachweis — dauerhaft aufheben kostet einen Zentimeter Ordner und erspart Rennerei.`},
{id:"gehaltsabrechnung",n:"Gehaltsabrechnungen",kat:"geld",typ:"jahre",dauer:`Bis das Rentenkonto geklärt ist`,
 warum:`Sie beweisen Beschäftigungszeiten und Beiträge, falls im Rentenkonto Lücken auftauchen. Die Dezember-Abrechnung fasst das ganze Jahr zusammen.`,
 ablage:`Ordner „Arbeit“ pro Arbeitgeber; mindestens jede Dezember-/Jahresabrechnung dauerhaft.`,
 digital:`Digitale Abrechnungen als PDF sichern — Portale verschwinden mit dem Jobwechsel.`,
 entsorgen:`Erst nach der Kontenklärung bei der Rentenversicherung schreddern — vorher sind sie dein einziger Beweis.`,
 tipp:`Beim Jobwechsel am letzten Tag alle Abrechnungen aus dem Mitarbeiterportal ziehen — danach ist der Zugang weg.`},
{id:"kassenbon",n:"Kassenbons",kat:"geld",typ:"jahre",dauer:`2 Jahre bei allem, was kaputtgehen kann`,
 warum:`Der Bon ist der einfachste Kaufnachweis für Umtausch, Gewährleistung (2 Jahre) und Garantie. Ohne geht es oft auch (Kontoauszug), aber mühsamer.`,
 ablage:`Eine Klarsichthülle „Bons Wertsachen“ im Ordner reicht — Alltagsbons dürfen sofort weg.`,
 digital:`Unbedingt abfotografieren: Thermopapier verblasst in Monaten zu weißem Nichts.`,
 entsorgen:`Alltagsbons zeitnah entsorgen; Bons zu Elektronik, Möbeln und Schmuck erst nach 2 Jahren.`,
 tipp:`Bon direkt an der Kasse fotografieren und ins Album „Belege“ — das Original darf dann ruhig verblassen.`},
{id:"garantie",n:"Rechnungen & Garantiebelege",kat:"geld",typ:"jahre",dauer:`Gewährleistung 2 Jahre; Garantie laut Hersteller (oft länger)`,
 warum:`Die gesetzliche Gewährleistung läuft 2 Jahre ab Kauf, Herstellergarantien teils 5 oder 10 Jahre — ohne Rechnung wird jede Reklamation zäh.`,
 ablage:`Ordner oder Box „Geräte“: Rechnung zusammen mit Garantiekarte und Kurzanleitung je Gerät.`,
 digital:`Scan reicht in der Praxis fast immer — Händler akzeptieren PDF-Rechnungen ohnehin.`,
 entsorgen:`Wenn das Gerät entsorgt wird, darf auch sein Papier gehen.`,
 tipp:`Aufs Gerät einen kleinen Aufkleber mit Kaufdatum — so weißt du ohne Suchen, ob die Frist noch läuft.`},
{id:"handwerker",n:"Handwerkerrechnungen",kat:"geld",typ:"jahre",dauer:`Pflicht: 2 Jahre — klug: 5 Jahre`,
 warum:`Bei Arbeiten am Haus gilt eine Gewährleistung von bis zu 5 Jahren — die Rechnung ist dein Anspruchsbeweis. Außerdem: Steuerbonus für Handwerkerleistungen nur mit Rechnung und Überweisung.`,
 ablage:`Ordner „Wohnung/Haus“, Register „Handwerker“ — zusammen mit Angebot und Abnahmeprotokoll.`,
 digital:`Scan zusätzlich sinnvoll; das Papier für die Pflichtfrist behalten.`,
 warn:`Privatleute MÜSSEN Rechnungen über Arbeiten am Grundstück 2 Jahre aufbewahren (steht meist auf der Rechnung) — sonst droht ein Bußgeld. Und: Handwerker nie bar zahlen, sonst ist der Steuerbonus weg.`,
 tipp:`Immer überweisen, nie bar — nur so gibt es die Steuerermäßigung, und der Zahlungsnachweis ist gratis dabei.`},
{id:"kredit",n:"Kreditverträge & Darlehensunterlagen",kat:"geld",typ:"jahre",dauer:`Bis 3 Jahre nach vollständiger Rückzahlung`,
 warum:`Vertrag, Tilgungsplan und die Bestätigung „vollständig zurückgezahlt“ schützen vor späten Nachforderungen — Ansprüche verjähren regelmäßig erst nach drei Jahren.`,
 ablage:`Ordner „Finanzierung“; bei Immobilienkrediten die Löschungsbewilligung fürs Grundbuch dauerhaft dazu.`,
 digital:`Vertrag im Original behalten, Rest als Scan.`,
 entsorgen:`Frühestens 3 Jahre nach Schlussrate — die Abschlussbestätigung am besten dauerhaft behalten.`,
 tipp:`Nach der letzten Rate aktiv eine Erledigungsbestätigung anfordern — dieses eine Blatt beendet jede spätere Diskussion.`},

/* -- Wohnen & Energie -- */
{id:"mietvertrag",n:"Mietvertrag",kat:"wohnen",typ:"jahre",dauer:`Bis lange nach dem Auszug: mindestens 1 Jahr, besser 3`,
 warum:`Während der Mietzeit regelt er alles; nach dem Auszug verjähren Vermieteransprüche wegen Schäden zwar schon nach 6 Monaten, Streit um Kaution und Nebenkosten zieht sich aber oft länger.`,
 ablage:`Ordner „Wohnung“ ganz vorn — zusammen mit allen Nachträgen und dem Schriftverkehr.`,
 digital:`Original aufheben; ein Scan zusätzlich macht ihn im Streitfall sofort greifbar.`,
 frist:`Mieter kündigen in der Regel mit 3 Monaten zum Monatsende — schriftlich, von allen Mietern unterschrieben.`,
 tipp:`Kündigung immer so, dass du den Zugang beweisen kannst: persönlich gegen Quittung oder per Einwurf-Einschreiben.`},
{id:"uebergabeprotokoll",n:"Übergabeprotokoll (Ein- & Auszug)",kat:"wohnen",typ:"jahre",dauer:`Bis Kaution zurück ist — besser noch 1 Jahr länger`,
 warum:`Es ist DER Beweis für den Zustand der Wohnung. Ohne Einzugsprotokoll haften Mieter schnell für Schäden der Vorgänger; Ansprüche des Vermieters verjähren 6 Monate nach Rückgabe.`,
 ablage:`Direkt hinter den Mietvertrag — mit Fotos vom Ein- und Auszug (Datum!).`,
 digital:`Fotos sowieso digital; das unterschriebene Protokoll im Original.`,
 tipp:`Beim Auszug jede Wand, jeden Boden und die Zählerstände fotografieren — zehn Minuten, die die Kaution retten.`},
{id:"nebenkosten",n:"Nebenkostenabrechnung",kat:"wohnen",typ:"jahre",dauer:`3 Jahre`,
 warum:`Du hast 12 Monate ab Zugang Zeit, Einwendungen zu erheben und Belege einzusehen — und für Vergleiche der Folgejahre sind alte Abrechnungen Gold wert.`,
 ablage:`Ordner „Wohnung“, Register „Nebenkosten“, Jahr für Jahr.`,
 digital:`Scan reicht.`,
 frist:`Einwendungen gegen die Abrechnung nur innerhalb von 12 Monaten nach Erhalt — danach ist sie praktisch festgeschrieben.`,
 entsorgen:`Nach 3 Jahren schreddern, die jeweils letzte behalten.`,
 tipp:`Jede Abrechnung einmal gegen das Vorjahr halten — Ausreißer bei Heizung oder Hauswart fallen so sofort auf.`},
{id:"immobilienkauf",n:"Kaufvertrag & Grundbuchunterlagen (Immobilie)",kat:"wohnen",typ:"lebenslang",dauer:`Solange dir die Immobilie gehört — und darüber hinaus`,
 warum:`Notarvertrag, Grundbuchauszug und alle Baurechnungen belegen Eigentum, Kaufpreis und Investitionen — steuerlich relevant bis weit nach einem Verkauf (Spekulationsfrist 10 Jahre).`,
 ablage:`Eigener Ordner „Immobilie“, sicher gelagert; Kopien getrennt vom Original.`,
 digital:`Originale zwingend behalten (Notarurkunden!); Scans zusätzlich.`,
 tipp:`Auch jede Modernisierungsrechnung hierhin — sie mindert später einmal die Steuer beim Verkauf.`},
{id:"stromgas",n:"Strom- & Gasvertrag",kat:"wohnen",typ:"laufend",dauer:`Solange der Vertrag läuft + letzte Jahresrechnung 3 Jahre`,
 warum:`Vertrag und Preisgarantie entscheiden, wann sich ein Wechsel lohnt; die Jahresabrechnungen belegen Verbrauch und Guthaben.`,
 ablage:`Ordner „Wohnung“, Register „Energie“ — Wechseldatum und Fristende notieren.`,
 digital:`Alles digital völlig ausreichend.`,
 frist:`In der Grundversorgung jederzeit mit 2 Wochen kündbar; Sonderverträge laut Vertrag — und bei jeder Preiserhöhung gilt ein Sonderkündigungsrecht.`,
 tipp:`Die Preiserhöhungs-Post ist deine Wechsel-Einladung: Sonderkündigung nutzen statt zähneknirschend zahlen.`},

/* -- Verträge & Abos -- */
{id:"handy",n:"Handy- & Internetvertrag",kat:"vertraege",typ:"laufend",dauer:`Solange der Vertrag läuft + Kündigungsbestätigung 3 Jahre`,
 warum:`Vertrag und Auftragsbestätigung belegen Konditionen und Laufzeitende — die Basis, um pünktlich zu kündigen oder zu verhandeln.`,
 ablage:`Ordner „Verträge“; das Laufzeitende zusätzlich in den Kalender.`,
 digital:`Digital reicht komplett.`,
 frist:`Nach der Mindestlaufzeit sind Handy- und Internetverträge monatlich mit nur 1 Monat Frist kündbar — automatische Jahresverlängerungen sind hier Geschichte.`,
 tipp:`Direkt am Abschlusstag die Kündigung zum Laufzeitende vormerken — verhandeln kannst du dann immer noch.`},
{id:"fitness",n:"Fitnessstudio-Vertrag",kat:"vertraege",typ:"laufend",dauer:`Solange die Mitgliedschaft läuft + Kündigungsnachweis 3 Jahre`,
 warum:`Studios sind berüchtigt für stillschweigende Verlängerungen — Vertrag und Kündigungsbestätigung sind deine Versicherung gegen Weiterzahlung.`,
 ablage:`Ordner „Verträge“; Laufzeitende in den Kalender.`,
 digital:`Digital reicht; die Kündigungsbestätigung unbedingt sichern.`,
 frist:`Bei neueren Verträgen gilt: Nach der Erstlaufzeit ist monatlich mit 1 Monat Frist Schluss — Verlängerung um ein ganzes Jahr ist nicht mehr zulässig.`,
 tipp:`Kündigung nur mit Nachweis (Mail mit Bestätigung, Einwurf-Einschreiben) — „habe ich am Tresen abgegeben“ verliert jeden Streit.`},
{id:"streaming",n:"Streaming- & App-Abos",kat:"vertraege",typ:"laufend",dauer:`Nur den Überblick — Papier fällt kaum an`,
 warum:`Kleine Monatsbeträge summieren sich unbemerkt zu Hunderten Euro im Jahr. Das „Dokument“ ist hier die eigene Abo-Liste.`,
 ablage:`Eine simple Liste (Notiz oder Tabelle): Dienst, Preis, Abrechnungsdatum, Kündigungsweg.`,
 digital:`Komplett digital — wichtig ist nur, dass die Liste existiert.`,
 frist:`Meist monatlich zum Ende des Abrechnungszeitraums kündbar — oft direkt im Konto-Menü oder über den App-Store.`,
 tipp:`Einmal im Jahr die Kontoauszüge nach Abos durchkämmen — der klassische Fund: zwei Dienste, die niemand mehr nutzt.`},
{id:"zeitschrift",n:"Zeitungs- & Zeitschriften-Abo",kat:"vertraege",typ:"laufend",dauer:`Solange das Abo läuft + Kündigungsnachweis`,
 warum:`Print-Abos verlängern sich traditionell still und leise; die Auftragsbestätigung verrät Laufzeit und Frist.`,
 ablage:`Ordner „Verträge“ — oder direkt in die Abo-Liste eintragen.`,
 digital:`Digital reicht.`,
 frist:`Fristen stehen im Kleingedruckten; bei neueren Verträgen gilt nach der Erstlaufzeit die Monatskündigung. Werbegeschenk-Abos enden fast nie von allein.`,
 tipp:`„Geschenkt für 3 Monate“ heißt fast immer: Kündigung sofort nach Abschluss schreiben — dann war es wirklich geschenkt.`},
{id:"kuendigungsnachweis",n:"Kündigungsschreiben & Bestätigungen",kat:"vertraege",typ:"jahre",dauer:`3 Jahre nach Vertragsende`,
 warum:`Die Kündigung nützt nichts, wenn du ihren Zugang nicht beweisen kannst — Bestätigungen sind der Schlussstrich unter jeden Vertrag.`,
 ablage:`Pro Vertrag direkt zum Vertrag heften: Kündigung + Bestätigung + letztes Schreiben.`,
 digital:`Mails mit Bestätigung archivieren; bei Papier: Einwurf-Einschreiben-Beleg dazu.`,
 entsorgen:`Nach 3 Jahren darf das Paket komplett in den Schredder.`,
 tipp:`Viele Anbieter haben einen gesetzlichen Kündigungs-Button auf der Website — Screenshot der Bestätigungsseite machen.`},

/* -- Versicherungen -- */
{id:"policen",n:"Versicherungspolicen",kat:"versicherung",typ:"laufend",dauer:`Solange der Vertrag läuft — Lebens-/Rentenpolicen dauerhaft`,
 warum:`Die Police ist dein Leistungsversprechen: Versicherungsschein, Bedingungen und Nachträge entscheiden im Schadenfall über jeden Euro.`,
 ablage:`Ordner „Versicherungen“, ein Register pro Vertrag: Schein vorn, Bedingungen und Schriftwechsel dahinter.`,
 digital:`Digital zulässig und praktisch — Lebens- und Rentenpolicen zusätzlich im Original verwahren.`,
 tipp:`Eine einseitige Übersicht vorn in den Ordner: Vertrag, Nummer, Hotline — im Ernstfall zählt Tempo, nicht Blättern.`},
{id:"schadenakte",n:"Schadenunterlagen",kat:"versicherung",typ:"jahre",dauer:`Bis 3 Jahre nach Abschluss des Schadenfalls`,
 warum:`Fotos, Schriftwechsel und die Abrechnung sichern dich ab, falls Folgeschäden auftauchen oder die Zahlung strittig wird.`,
 ablage:`Pro Schadenfall eine Hülle: Meldung, Fotos, Gutachten, Abrechnung.`,
 digital:`Fotos sofort sichern; der Rest digital völlig okay.`,
 entsorgen:`3 Jahre nach der letzten Zahlung schreddern.`,
 tipp:`Im Schadenfall zuerst fotografieren, dann aufräumen — Beweise verschwinden schneller als man denkt.`},
{id:"kfz",n:"Kfz-Unterlagen (Fahrzeugschein & -brief)",kat:"versicherung",typ:"laufend",dauer:`Solange dir das Fahrzeug gehört`,
 warum:`Zulassungsbescheinigung Teil I (Schein) muss bei Fahrten mit, Teil II (Brief) beweist das Eigentum — er ist das wertvollste Blatt am Auto.`,
 ablage:`Teil I ins Portemonnaie oder Handschuhfach-Etui, Teil II NACH HAUSE in den Ordner „Auto“ — zusammen mit Kaufvertrag und Serviceheft.`,
 digital:`Kopien helfen bei Verlust — die Originale sind Pflicht.`,
 frist:`Kfz-Versicherung wechseln: bei Verträgen mit Kalenderjahr ist der 30. November der klassische Stichtag (1 Monat Frist zum Ablauf).`,
 warn:`Teil II (Fahrzeugbrief) niemals im Auto lassen — wer Brief und Auto hat, kann es faktisch verkaufen. Auto weg plus Brief weg ist der Versicherungs-Albtraum.`,
 tipp:`Der 30.11. gehört in jeden Kalender — kein Vertrag lässt sich so leicht und lohnend wechseln wie die Kfz-Versicherung.`},
{id:"verskuendigen",n:"Versicherung kündigen oder wechseln",kat:"versicherung",typ:"laufend",dauer:`Nachweise 3 Jahre aufheben`,
 warum:`Sach-Versicherungen verlängern sich still um ein Jahr — wer die Frist kennt, verhandelt aus einer Position der Stärke oder wechselt sauber.`,
 ablage:`Fristen aller Policen auf die Übersichtsseite im Versicherungsordner + Kalendereintrag.`,
 digital:`Kündigung per Mail/Portal mit Bestätigung sichern.`,
 frist:`Üblich sind 1–3 Monate zum Ende des Versicherungsjahres (steht in der Police). Nach einem Schadenfall oder einer Beitragserhöhung gibt es zusätzlich ein Sonderkündigungsrecht.`,
 tipp:`Erst neue Zusage, dann alte kündigen — bei Pflichtversicherungen wie Kfz darf keine Lücke entstehen.`},

/* -- Arbeit & Rente -- */
{id:"arbeitsvertrag",n:"Arbeitsverträge",kat:"arbeit",typ:"jahre",dauer:`Bis 3 Jahre nach Ende des Arbeitsverhältnisses`,
 warum:`Vertrag plus Änderungen belegen Gehalt, Urlaub und Ansprüche — auch nach dem Ausscheiden können Nachforderungen (in beide Richtungen) auftauchen.`,
 ablage:`Ordner „Arbeit“, pro Arbeitgeber ein Register: Vertrag, Änderungen, Kündigung/Aufhebung, Zeugnis.`,
 digital:`Original behalten; Scan zusätzlich.`,
 tipp:`Jede Vertragsänderung nur schriftlich akzeptieren — „das machen wir mündlich“ ist im Streit nichts wert.`},
{id:"arbeitszeugnis",n:"Arbeitszeugnisse",kat:"arbeit",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Zeugnisse sind der lückenlose Beleg deines Berufswegs — Bewerbungen fragen auch nach 20 Jahren noch nach Stationen.`,
 ablage:`Register „Zeugnisse“ im Arbeitsordner — Originale knickfrei.`,
 digital:`Hochauflösend scannen für Bewerbungen; Originale behalten.`,
 tipp:`Beim Abschied immer ein qualifiziertes Zeugnis verlangen — darauf besteht ein Anspruch, und später wird es zäh.`},
{id:"rente",n:"Rentenunterlagen & Versicherungsverlauf",kat:"arbeit",typ:"lebenslang",dauer:`Lebenslang — bis der Rentenbescheid endgültig ist`,
 warum:`Der Versicherungsverlauf entscheidet über deine Rente. Jede fehlende Zeit (Ausbildung, Kindererziehung, Auslandsjahr) kostet bares Geld — beweisen musst du sie selbst.`,
 ablage:`Eigenes Register „Rente“: Renteninformationen, Versicherungsverlauf, Bescheide, Nachweise für Lücken.`,
 digital:`Nachweise (Ausbildungsverträge, Abrechnungen) sicher doppelt: Papier + Scan.`,
 warn:`Nicht bis 67 warten: Die Kontenklärung bei der Rentenversicherung (ab Mitte 40 angeboten) deckt Lücken auf, solange sich Belege noch beschaffen lassen.`,
 tipp:`Die jährliche Renteninformation nicht abheften, sondern LESEN — eine falsche Lücke jetzt zu melden dauert Minuten, mit 66 Monate.`},
{id:"fortbildung",n:"Zertifikate & Fortbildungsnachweise",kat:"arbeit",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Abschlüsse und Zertifikate sind Karriere-Kapital — manche Berechtigung (Schein, Lizenz) lässt sich ohne Nachweis nicht verlängern.`,
 ablage:`Zu den Zeugnissen ins Register — chronologisch.`,
 digital:`Scan für Bewerbungen, Original behalten.`,
 tipp:`Direkt nach jedem Kurs das Zertifikat einscannen und ablegen — nach drei Umzügen sucht man sonst vergeblich.`},

/* -- Familie & fürs Leben -- */
{id:"geburtsurkunde",n:"Geburtsurkunde & Stammbuch",kat:"familie",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Urkunden braucht es bei Heirat, Kindergeld, Erbfall und Behördengängen — immer im Original oder als beglaubigte Abschrift.`,
 ablage:`Dokumentenmappe an einem festen, geschützten Ort — ideal zusammen im Notfallordner.`,
 digital:`Scans sind praktisch, ersetzen die Urkunde aber nicht. Bei Verlust stellt das Standesamt des Geburtsorts gegen Gebühr neue aus.`,
 tipp:`Von jeder Urkunde eine Kopie an einem zweiten Ort (oder verschlüsselt in der Cloud) — Feuer und Wasserschaden fragen nicht.`},
{id:"schulzeugnisse",n:"Schul- & Ausbildungszeugnisse",kat:"familie",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Abschlusszeugnisse werden bei Bewerbungen, Studienplätzen und Anerkennungen immer wieder verlangt — Ersatz ist mühsam bis unmöglich.`,
 ablage:`Dokumentenmappe, knickfrei; die Abschlusszeugnisse zu den wichtigsten Papieren.`,
 digital:`Hochauflösender Scan als Arbeitskopie; Original nie aus der Hand geben, nur beglaubigte Kopien verschicken.`,
 tipp:`Ein für alle Mal ein Set beglaubigter Kopien anfertigen lassen — dann bleibt das Original für immer im Ordner.`},
{id:"impfpass",n:"Impfpass & wichtige Gesundheitsunterlagen",kat:"familie",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Der Impfpass dokumentiert lebenslangen Schutz; OP-Berichte, Allergiepass und Befunde ersparen Doppeluntersuchungen und Fehlbehandlungen.`,
 ablage:`Register „Gesundheit“ pro Familienmitglied; Impfpass dort, wo man ihn findet.`,
 digital:`Impfungen zusätzlich abfotografieren; bei Verlust können Ärzte Einträge aus der Akte teils nachtragen.`,
 tipp:`Vor jeder größeren Reise ein Foto vom aktuellen Impfpass aufs Handy — der Pass selbst bleibt zu Hause sicher.`},
{id:"vorsorge",n:"Vorsorgevollmacht & Patientenverfügung",kat:"familie",typ:"lebenslang",dauer:`Lebenslang — regelmäßig aktualisieren`,
 warum:`Ohne Vollmacht dürfen selbst Ehepartner vieles nicht entscheiden — dann bestellt das Gericht einen Betreuer. Diese zwei Dokumente regeln, wer für dich handelt und was du medizinisch willst.`,
 ablage:`Original im Notfallordner; die Bevollmächtigten erhalten eine Kopie und kennen den Ort.`,
 digital:`Das Original zählt. Zusätzlich beim Zentralen Vorsorgeregister registrieren — dort schauen Gerichte nach.`,
 warn:`Die beste Vollmacht ist wertlos, wenn niemand weiß, dass es sie gibt oder wo sie liegt — Auffindbarkeit ist der halbe Schutz.`,
 tipp:`Alle paar Jahre Datum prüfen, neu unterschreiben — ein frisches Datum nimmt jedem Zweifel an der Aktualität den Wind.`},
{id:"testament",n:"Testament",kat:"familie",typ:"lebenslang",dauer:`Lebenslang`,
 warum:`Ohne Testament gilt die gesetzliche Erbfolge — die oft niemand so wollte. Ein handschriftliches Testament ist gültig, muss aber gefunden werden.`,
 ablage:`Sicherste Lösung: amtliche Verwahrung beim Nachlassgericht gegen einmalige, kleine Gebühr — dann wird es im Erbfall garantiert eröffnet.`,
 digital:`Nur das eigenhändig geschriebene und unterschriebene Original zählt — kein Ausdruck, kein Scan.`,
 warn:`Nicht ins Bankschließfach: Das dürfen Erben oft erst öffnen, wenn sie das Erbe nachweisen — wofür sie das Testament bräuchten. Ein Kreisverkehr ohne Ausfahrt.`,
 tipp:`Handschriftlich, mit Ort, Datum, Unterschrift — und in die amtliche Verwahrung. Sicherer wird es nicht.`},
{id:"notfallordner",n:"Der Notfallordner",kat:"familie",typ:"lebenslang",dauer:`Laufend gepflegt — ein Leben lang`,
 warum:`Wenn dir etwas zustößt, müssen andere in Stunden finden, wofür du Jahre sortiert hast: Vollmachten, Versicherungen, Konten, Verträge, Zugangsdaten-Hinweis.`,
 ablage:`EIN Ordner, klar beschriftet: Vollmachten vorn, dann Urkunden(-kopien), Policen-Übersicht, Konten- und Vertragsliste, Ansprechpartner.`,
 digital:`Papier gewinnt im Notfall — ergänzt um einen Hinweis, wo digitale Zugänge (Passwort-Manager) geregelt sind.`,
 tipp:`Der wichtigste Schritt ist der letzte: Zwei Menschen deines Vertrauens sagen, DASS es den Ordner gibt und WO er steht.`}
];
